Description of getEventsFromSwitches
Home > fun > eventExtraction > getEventsFromSwitches.m
getEventsFromSwitches
PURPOSE
% Get stance phases
SYNOPSIS
function [LHS,RHS,LTO,RTO] = getEventsFromSwitches(Lft_sw,Rft_sw,fsample)
DESCRIPTION
% Get stance phases
CROSS-REFERENCE INFORMATION
This function calls:
checkEventConsistency
getEventsFromStance First step:
getStanceFromSwitches Get stance from acceleration
This function is called by:
SOURCE CODE
function [LHS,RHS,LTO,RTO] = getEventsFromSwitches(Lft_sw,Rft_sw,fsample)
%% Get stance phases
[stanceL] = getStanceFromSwitches(Lft_sw, fsample);
[stanceR] = getStanceFromSwitches(Rft_sw, fsample);
%% Get events from stance
[LHS,RHS,LTO,RTO] = getEventsFromStance(stanceL,stanceR);
%% Check consistency
[consistent] = checkEventConsistency(LHS,RHS,LTO,RTO);
end