Description of rawTrialData
Home > labTools > classes > dataStructs > @rawTrialData > rawTrialData.m
rawTrialData
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
rawTrialData
rawLabData
This function is called by:
rawTrialData
TorqueCalculator TORQUECALCULATOR Calculate torque at each leg joint using inverse dynamics
reviseExperimentInfo REVISEEEXPERIMENTINFO Revise experimental session information in MAT files
loadSubject loadSubject Load, organize, process, and save experimental session
loadTrials loadTrials Generates rawTrialData instances for each trial.
SUBFUNCTIONS
function this = rawTrialData(metaData, markerData, EMGData,
SOURCE CODE
classdef rawTrialData < rawLabData
    %rawTrialData  Raw data container for individual trial data
    %
    %   rawTrialData extends rawLabData to enforce that the metadata is
    %   of trialMetaData type rather than the more general labMetaData
    %   type. This ensures proper trial-specific metadata is associated
    %   with the data.
    %
    %rawTrialData properties:
    %   (inherits all properties from rawLabData and labData)
    %
    %rawTrialData methods:
    %   rawTrialData - constructor for raw trial data
    %
    %See also: rawLabData, labData, trialMetaData, processedTrialData
    %% Properties
    properties
    end
    %% Constructor
    methods
        function this = rawTrialData(metaData, markerData, EMGData, ...
                GRFData, beltSpeedSetData, beltSpeedReadData, accData, ...
                EEGData, footSwitches, HreflexPin)
            %rawTrialData  Constructor for rawTrialData class
            %
            %   this = rawTrialData(metaData, markerData, EMGData,
            %   GRFData, beltSpeedSetData, beltSpeedReadData, accData,
            %   EEGData, footSwitches, HreflexPin) creates a raw trial
            %   data object with specified data and metadata
            %
            %   Inputs:
            %       metaData - trialMetaData or derivedMetaData object
            %       markerData - orientedLabTimeSeries with marker
            %                    trajectories
            %       EMGData - labTimeSeries with EMG signals
            %       GRFData - orientedLabTimeSeries with ground reaction
            %                 forces
            %       beltSpeedSetData - labTimeSeries with commanded belt
            %                          speeds
            %       beltSpeedReadData - labTimeSeries with actual belt
            %                           speeds
            %       accData - orientedLabTimeSeries with acceleration
            %                 data
            %       EEGData - labTimeSeries with EEG signals
            %       footSwitches - labTimeSeries with foot switch data
            %       HreflexPin - labTimeSeries with H-reflex stimulus
            %                    timing
            %
            %   Outputs:
            %       this - rawTrialData object
            %
            %   See also: rawLabData, trialMetaData, processedTrialData
            if ~isa(metaData, 'trialMetaData') && ...
                    ~isa(metaData, 'derivedMetaData') && ~isempty(metaData)
                ME = MException('rawTrialData:Constructor', ...
                    'First argument is not a trialMetaData object.');
                throw(ME);
            end
            this@rawLabData(metaData, markerData, EMGData, GRFData, ...
                beltSpeedSetData, beltSpeedReadData, accData, EEGData, ...
                footSwitches, HreflexPin);
        end
    end
end