Description of demean
Home > labTools > fun > ext > pitools > math > demean.m
demean
PURPOSE
DEMEAN Remove the column-wise mean from a matrix.
SYNOPSIS
function Y = demean(X)
DESCRIPTION
DEMEAN Remove the column-wise mean from a matrix.
   Subtracts the mean of each column from the corresponding column of X.
 NaN values are ignored when computing the mean.
 Inputs:
   X - (N×C) double, input data matrix
 Outputs:
   Y - (N×C) double, mean-subtracted data (same size as X)
 Toolbox Dependencies: None
 See also COLUMNNORM.
CROSS-REFERENCE INFORMATION
This function calls:
mean mean Computes mean across strides
This function is called by:
alignedTimeSeries
labTimeSeries
SOURCE CODE
function Y = demean(X)
%DEMEAN Remove the column-wise mean from a matrix.
%
%   Subtracts the mean of each column from the corresponding column of X.
% NaN values are ignored when computing the mean.
%
% Inputs:
%   X - (N×C) double, input data matrix
%
% Outputs:
%   Y - (N×C) double, mean-subtracted data (same size as X)
%
% Toolbox Dependencies: None
%
% See also COLUMNNORM.
arguments
    X (:,:) double
end
colMeans = mean(X, 1, 'omitnan');  % (1×C) column means
Y        = X - colMeans;           % broadcast subtraction
end