Description of appendBodyCOM
Home > labTools > fun > parameterCalculation > appendBodyCOM.m
appendBodyCOM
PURPOSE
APPENDBODYCOM Approximate whole-body center of mass from marker data.
SYNOPSIS
function markerDataOut = appendBodyCOM(markerData, BW)
DESCRIPTION
APPENDBODYCOM Approximate whole-body center of mass from marker data.
   Estimates the whole-body center of mass (COM) from kinematic marker
 data using segment inertial parameters. If a HAT (head-arms-trunk)
 marker is present, the COM is computed from six body segments (foot,
 shank, and thigh bilaterally plus HAT) using anthropometric fractions
 from Winter and USAARL-88-5. If no HAT marker is present, the average
 hip marker position is used as a proxy. Arm motion is assumed to
 cancel (arms swing in opposite phase) and is excluded from the
 computation. The computed body COM (BCOMx/y/z) is appended to the
 input dataset.
 Inputs:
   markerData - orientedLabTimeSeries containing marker trajectories;
                must include RHIP and LHIP; if HAT is present, RANK,
                LANK, RKNE, LKNE, RTOE, and LTOE are also required
   BW         - subject body weight (kg)
 Outputs:
   markerDataOut - input markerData with channels BCOMx, BCOMy, and
                   BCOMz appended
 Toolbox Dependencies:
   None
 See also COMPUTECOM, APPENDDATA, ORIENTEDLABTIMESERIES.
 Author: CJS 5/2017
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
appendData appendData Adds new parameters to dataset
mean mean Computes mean across strides
appendData appendData Adds more data as new labels
appendData appendData Appends new parameters
orientationInfo
This function is called by:
computeCOM COMPUTECOM Compute stride-by-stride COM kinematics relative to each ankle.
SOURCE CODE
function markerDataOut = appendBodyCOM(markerData, BW)
%APPENDBODYCOM Approximate whole-body center of mass from marker data.
%
%   Estimates the whole-body center of mass (COM) from kinematic marker
% data using segment inertial parameters. If a HAT (head-arms-trunk)
% marker is present, the COM is computed from six body segments (foot,
% shank, and thigh bilaterally plus HAT) using anthropometric fractions
% from Winter and USAARL-88-5. If no HAT marker is present, the average
% hip marker position is used as a proxy. Arm motion is assumed to
% cancel (arms swing in opposite phase) and is excluded from the
% computation. The computed body COM (BCOMx/y/z) is appended to the
% input dataset.
%
% Inputs:
%   markerData - orientedLabTimeSeries containing marker trajectories;
%                must include RHIP and LHIP; if HAT is present, RANK,
%                LANK, RKNE, LKNE, RTOE, and LTOE are also required
%   BW         - subject body weight (kg)
%
% Outputs:
%   markerDataOut - input markerData with channels BCOMx, BCOMy, and
%                   BCOMz appended
%
% Toolbox Dependencies:
%   None
%
% See also COMPUTECOM, APPENDDATA, ORIENTEDLABTIMESERIES.
%
% Author: CJS 5/2017
arguments
    markerData (1,1)
    BW         (1,1) double
end
%% Get Orientation and Hip Markers
if isempty(markerData.orientation)
    warning('appendBodyCOM:noOrientation', ...
        'Assuming default orientation of axes for marker data.');
    orientation = orientationInfo([0, 0, 0], 'x', 'y', 'z', 1, 1, 1);
else
    orientation = markerData.orientation;
end
rHip = markerData.getDataAsVector({ ...
    ['RHIP' orientation.sideAxis], ...
    ['RHIP' orientation.foreaftAxis], ...
    ['RHIP' orientation.updownAxis]});
rHip = [orientation.sideSign    * rHip(:, 1), ...
    orientation.foreaftSign * rHip(:, 2), ...
    orientation.updownSign  * rHip(:, 3)];
lHip = markerData.getDataAsVector({ ...
    ['LHIP' orientation.sideAxis], ...
    ['LHIP' orientation.foreaftAxis], ...
    ['LHIP' orientation.updownAxis]});
lHip = [orientation.sideSign    * lHip(:, 1), ...
    orientation.foreaftSign * lHip(:, 2), ...
    orientation.updownSign  * lHip(:, 3)];
%% Compute Body Center of Mass
if isempty(markerData.getLabelsThatMatch('HAT'))
    % No HAT marker: use mean hip position as a proxy.
    % NOTE: pelvis ASIS/PSIS markers would be more accurate, but hip
    %   markers are more reliably present in typical datasets
    warning('appendBodyCOM:insufficientMarkers', ...
        ['Not enough markers to compute the COM; ' ...
        'using average hip position as proxy.']);
    bCOM = [mean([rHip(:, 1) lHip(:, 1)], 2), ...
        mean([rHip(:, 2) lHip(:, 2)], 2), ...
        mean([rHip(:, 3) lHip(:, 3)], 2)];
else
    %% Compute Segment Centers of Mass
    % Retrieve segment marker data (ankle, knee, toe, HAT)
    rAnk = markerData.getDataAsVector({ ...
        ['RANK' orientation.sideAxis], ...
        ['RANK' orientation.foreaftAxis], ...
        ['RANK' orientation.updownAxis]});
    rAnk = [orientation.sideSign    * rAnk(:, 1), ...
        orientation.foreaftSign * rAnk(:, 2), ...
        orientation.updownSign  * rAnk(:, 3)];
    lAnk = markerData.getDataAsVector({ ...
        ['LANK' orientation.sideAxis], ...
        ['LANK' orientation.foreaftAxis], ...
        ['LANK' orientation.updownAxis]});
    lAnk = [orientation.sideSign    * lAnk(:, 1), ...
        orientation.foreaftSign * lAnk(:, 2), ...
        orientation.updownSign  * lAnk(:, 3)];
    rKnee = markerData.getDataAsVector({ ...
        ['RKNE' orientation.sideAxis], ...
        ['RKNE' orientation.foreaftAxis], ...
        ['RKNE' orientation.updownAxis]});
    rKnee = [orientation.sideSign    * rKnee(:, 1), ...
        orientation.foreaftSign * rKnee(:, 2), ...
        orientation.updownSign  * rKnee(:, 3)];
    lKnee = markerData.getDataAsVector({ ...
        ['LKNE' orientation.sideAxis], ...
        ['LKNE' orientation.foreaftAxis], ...
        ['LKNE' orientation.updownAxis]});
    lKnee = [orientation.sideSign    * lKnee(:, 1), ...
        orientation.foreaftSign * lKnee(:, 2), ...
        orientation.updownSign  * lKnee(:, 3)];
    rToe = markerData.getDataAsVector({ ...
        ['RTOE' orientation.sideAxis], ...
        ['RTOE' orientation.foreaftAxis], ...
        ['RTOE' orientation.updownAxis]});
    rToe = [orientation.sideSign    * rToe(:, 1), ...
        orientation.foreaftSign * rToe(:, 2), ...
        orientation.updownSign  * rToe(:, 3)];
    lToe = markerData.getDataAsVector({ ...
        ['LTOE' orientation.sideAxis], ...
        ['LTOE' orientation.foreaftAxis], ...
        ['LTOE' orientation.updownAxis]});
    lToe = [orientation.sideSign    * lToe(:, 1), ...
        orientation.foreaftSign * lToe(:, 2), ...
        orientation.updownSign  * lToe(:, 3)];
    hatPos = markerData.getDataAsVector({ ...
        ['HAT' orientation.sideAxis], ...
        ['HAT' orientation.foreaftAxis], ...
        ['HAT' orientation.updownAxis]});
    hatPos = [orientation.sideSign    * hatPos(:, 1), ...
        orientation.foreaftSign * hatPos(:, 2), ...
        orientation.updownSign  * hatPos(:, 3)];
    % Segment COM fractions from distal to proximal endpoint (Winter 1990)
    footCOMFrac  = 0.5;       % foot COM: midpoint between ankle and toe
    shankCOMFrac = 0.567;     % shank COM: 56.7% from ankle toward knee
    thighCOMFrac = 0.567;     % thigh COM: 56.7% from knee toward hip
    % NOTE: verify shank and thigh fractions; 0.567 may need recalculation
    hatCOMFrac   = 1 - 0.697; % HAT COM: 30.3% from HAT marker toward hip
    % (fraction derived from Winter and USAARL-88-5 pilot data)
    rFootCOM  = abs(rAnk  - rToe)  .* footCOMFrac  + rToe;
    lFootCOM  = abs(lAnk  - lToe)  .* footCOMFrac  + lToe;
    rShankCOM = abs(rKnee - rAnk)  .* shankCOMFrac + rAnk;
    lShankCOM = abs(lKnee - lAnk)  .* shankCOMFrac + lAnk;
    rThighCOM = abs(rHip  - rKnee) .* thighCOMFrac + rKnee;
    lThighCOM = abs(lHip  - lKnee) .* thighCOMFrac + lKnee;
    hipMidpoint = (rHip + lHip) ./ 2;
    hipMeanPos  = mean([rHip; lHip], 'omitnan');  % grand mean of all hip samples
    hatCOM = abs(hipMidpoint - hatPos) .* hatCOMFrac + hipMeanPos;
    %% Compile Whole-Body Center of Mass
    % Segment mass fractions (Winter 1990 anthropometric tables)
    footMassFrac  = 0.0145;  % foot mass as fraction of BW
    shankMassFrac = 0.0465;  % shank mass as fraction of BW
    thighMassFrac = 0.1;     % thigh mass as fraction of BW
    hatMassFrac   = 0.71;    % HAT mass as fraction of BW
    footWeight  = footMassFrac  .* BW;
    shankWeight = shankMassFrac .* BW;
    thighWeight = thighMassFrac .* BW;
    hatWeight   = hatMassFrac   .* BW;
    rightLegCOM = rFootCOM*footWeight + rShankCOM*shankWeight + ...
        rThighCOM*thighWeight;
    leftLegCOM  = lFootCOM*footWeight + lShankCOM*shankWeight + ...
        lThighCOM*thighWeight;
    bodyCOM = (1/BW) .* ...
        (rightLegCOM + leftLegCOM + hatCOM*hatWeight);
    bCOM = bodyCOM;
    % CJS note: change here to change what is stored in the COM dataset
    segCOMData = [rFootCOM lFootCOM rShankCOM lShankCOM ...
        rThighCOM lThighCOM hatCOM bodyCOM];
    segLabels = { ...
        'RfCOMx', 'RfCOMy', 'RfCOMz', ...
        'LfCOMx', 'LfCOMy', 'LfCOMz', ...
        'RsCOMx', 'RsCOMy', 'RsCOMz', ...
        'LsCOMx', 'LsCOMy', 'LsCOMz', ...
        'RtCOMx', 'RtCOMy', 'RtCOMz', ...
        'LtCOMx', 'LtCOMy', 'LtCOMz', ...
        'HATCOMx', 'HATCOMy', 'HATCOMz', ...
        'BCOMx', 'BCOMy', 'BCOMz'};
end
%% Append Body COM to Marker Dataset
labelsBody    = {'BCOMx', 'BCOMy', 'BCOMz'};
% Pablo: creating orientedLabTS
% COMTS = orientedLabTimeSeries(segCOMData, markerData.Time(1), ...
%     markerData.sampPeriod, segLabels(:), markerData.orientation);
markerDataOut = appendData(...
    markerData, bCOM, labelsBody, markerData.orientation);
end