Description of computeAngleParameters
Home > labTools > fun > parameterCalculation > computeAngleParameters.m
computeAngleParameters
PURPOSE
COMPUTEANGLEPARAMETERS Compute joint angle parameters per stride.
SYNOPSIS
function out = computeAngleParameters(angleData, gaitEvents, slowLeg,eventTypes)
DESCRIPTION
COMPUTEANGLEPARAMETERS Compute joint angle parameters per stride.
   Computes stride-by-stride joint angle parameters and returns a
 parameterSeries object that can be concatenated with other parameter
 series objects (e.g., from computeTemporalParameters).
 Inputs:
   angleData  - labTimeSeries containing limb angle data, with
                channel labels prefixed by leg side ('L' or 'R')
   gaitEvents - labTimeSeries of gait events for the trial
   slowLeg    - char specifying the slow-belt leg ('L' or 'R')
   eventTypes - cell array of gait event type strings as constructed
                in calcParameters (e.g., {'LHS','RTO','RHS','LTO'})
 Outputs:
   out - parameterSeries object containing all angle parameters,
         including discrete stride-level measures and heel strike
         angle parameters
 Toolbox Dependencies:
   None
 See also COMPUTETEMPORALPARAMETERS, COMPUTESPATIALPARAMETERS,
   COMPUTEFORCEPARAMETERS, COMPUTETSDISCRETEPARAMETERS,
   COMPUTEHSPARAMETERS, PARAMETERSERIES, CALCPARAMETERS.
CROSS-REFERENCE INFORMATION
This function calls:
cat cat Concatenates alignedTimeSeries
cat cat Concatenates (override)
cat cat Concatenates two parameterSeries
getOtherLeg
computeHSParameters COMPUTEHSPARAMETERS Compute heel-strike-aligned parameters per stride.
computeTSDiscreteParameters COMPUTETSDISCRETEPARAMETERS Discretize time series into stride phases.
This function is called by:
calcParameters CALCPARAMETERS Compute stride-by-stride parameters for analysis.
SOURCE CODE
function out = computeAngleParameters(angleData, gaitEvents, slowLeg, ...
    eventTypes)
%COMPUTEANGLEPARAMETERS Compute joint angle parameters per stride.
%
%   Computes stride-by-stride joint angle parameters and returns a
% parameterSeries object that can be concatenated with other parameter
% series objects (e.g., from computeTemporalParameters).
%
% Inputs:
%   angleData  - labTimeSeries containing limb angle data, with
%                channel labels prefixed by leg side ('L' or 'R')
%   gaitEvents - labTimeSeries of gait events for the trial
%   slowLeg    - char specifying the slow-belt leg ('L' or 'R')
%   eventTypes - cell array of gait event type strings as constructed
%                in calcParameters (e.g., {'LHS','RTO','RHS','LTO'})
%
% Outputs:
%   out - parameterSeries object containing all angle parameters,
%         including discrete stride-level measures and heel strike
%         angle parameters
%
% Toolbox Dependencies:
%   None
%
% See also COMPUTETEMPORALPARAMETERS, COMPUTESPATIALPARAMETERS,
%   COMPUTEFORCEPARAMETERS, COMPUTETSDISCRETEPARAMETERS,
%   COMPUTEHSPARAMETERS, PARAMETERSERIES, CALCPARAMETERS.
arguments
    angleData  (1,1)
    gaitEvents (1,1)
    slowLeg    (1,:) char
    eventTypes (1,:) cell
end
%% Pre-Process Angle Labels
% Rename channel labels from L/R convention to s/f convention so that
% downstream parameter names are leg-agnostic
fastLeg = getOtherLeg(slowLeg);
slowLabels = angleData.getLabelsThatMatch(['^' slowLeg]);
fastLabels = angleData.getLabelsThatMatch(['^' fastLeg]);
% Silence renameLabels warning temporarily during relabeling
warning('off', 'labTS:renameLabels:dont');
angleData = angleData.renameLabels(...
    slowLabels, regexprep(slowLabels, ['^' slowLeg], 's'));
angleData = angleData.renameLabels(...
    fastLabels, regexprep(fastLabels, ['^' fastLeg], 'f'));
angleData = angleData.renameLabels(...
    angleData.labels, strcat(angleData.labels, {'Angle'}));
warning('on', 'labTS:renameLabels:dont');
%% Compute and Output Angle Parameters
Angles_alt = computeTSDiscreteParameters(...
    angleData, gaitEvents, eventTypes);
Angles_HS  = computeHSParameters(angleData, gaitEvents, eventTypes);
out = cat(Angles_alt, Angles_HS);
end