Description of processedLabData
Home > labTools > classes > dataStructs > @processedLabData > processedLabData.m
processedLabData
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
getStrideInfo getStrideInfo Returns stride timing information
getStridedField getStridedField Extracts stride-segmented field data across
recomputeEvents recomputeEvents Recalculates gait events and parameters
reduce reduce Creates reducedLabData for all trials
labData
recomputeEvents recomputeEvents Re-calculates gait events from angle data
calcAdaptParams calcAdaptParams Re-computes adaptation parameters
getArrayedEvents getArrayedEvents Retrieves events organized as an array
getStepInfo getStepInfo Returns step count and timing information
getStrideInfo getStrideInfo Returns stride count and timing information
getStridedField getStridedField Extracts field data organized by stride
processedLabData
recomputeEvents recomputeEvents Re-computes gait events and adaptation parameters
reduce reduce Aligns and resamples all timeseries to the same indexes and puts
separateIntoDoubleStrides separateIntoDoubleStrides Splits data into 2-stride segments
separateIntoStrides separateIntoStrides Splits data into individual stride segments
separateIntoSuperStrides separateIntoSuperStrides Splits data into 1.5-stride segments
getArrayedEvents getArrayedEvents Extracts event times as array
sliceTS sliceTS Slices at given time breakpoints
calcExperimentalParams CALCEXPERIMENTALPARAMS Compute experimental parameters per stride.
This function is called by:
processedLabData
strideData
processedTrialData
SUBFUNCTIONS
function this = processedLabData(metaData, markerData, EMGData,
function this = set.gaitEvents(this, events)
function this = set.procEMGData(this, procEMG)
function this = set.angleData(this, angleData)
function this = set.adaptParams(this, adaptData)
function partialGaitEvents = getPartialGaitEvents(this, eventName)
function [alignedField, bad] = getAlignedField(this, field,
function expParams = get.experimentalParams(this)
function b = get.isSingleStride(this)
function [stridedField, bad, initTime, events] =
SOURCE CODE
classdef processedLabData < labData
    %processedLabData  Extends labData to include processed data derived
    %from the raw data.
    %
    %processedLabData properties:
    %   gaitEvents - labTS object with HS and TO events
    %   procEMGdata - processedEMGTS object
    %   angleData - labTS object with angles calculated from marker data
    %   adaptParams - parameterSeries adaptation values on a
    %                 stride-by-stride basis
    %   isSingleStride - boolean flag to check length of data
    %   experimentalParams - parameterSeries for testing new
    %                        adaptation parameters
    %
    %processedLabData methods:
    %
    %   getProcEMGData - accessor for processed EMGs
    %   getProcEMGList - returns list of processed EMG labels
    %   getPartialGaitEvents - accessor for specific events
    %   getEventList - returns list of event labels
    %   getAngleData - accessor for angle data
    %   getParam - accessor for adaptation parameters
    %   getExpParam - accessor for experimental adaptation parameters
    %   calcAdaptParams - re-computes adaptation parameters
    %
    %   separateIntoStrides - splits data into individual stride segments
    %   separateIntoSuperStrides - splits data into 1.5-stride
    %                              segments for parameter calculation
    %   separateIntoDoubleStrides - splits data into 2-stride
    %                               segments for parameter calculation
    %   getStrideInfo - returns stride count and timing information
    %   getStridedField - extracts field data organized by stride
    %   getAlignedField - time-aligns field data to gait events
    %
    %See also: labData, labTimeSeries, processedEMGTimeSeries,
    %          parameterSeries
    %% Properties
    properties % (SetAccess = private)  Cannot set to private,
        % because labData will try to set it when using split()
        gaitEvents % labTS
        procEMGData % processedEMGTS
        angleData % labTS (angles based off kinematics)
        adaptParams % paramterSeries (parameters which characterize
        % adaptation process) --> must be calculated,
        % therefore not part of constructor.
        % EMGData, which is inherited from labData, saves the
        % FILTERED EMG data used for processing afterwards (not the
        % RAW, which is saved in the not-procesed labData)
        COPData
        COMData
        jointMomentsData
    end
    properties (Dependent)
        isSingleStride % ever used?
        experimentalParams
    end
    %% Constructor
    methods
        function this = processedLabData(metaData, markerData, EMGData, ...
                GRFData, beltSpeedSetData, beltSpeedReadData, accData, ...
                EEGData, footSwitches, events, procEMG, angleData, ...
                COPData, COMData, jointMomentsData, HreflexPin)
            % processedLabData  Constructor for processedLabData class
            %
            %   All arguments are mandatory
            if nargin < 16 % metaData does not get replaced!
                markerData = [];
                EMGData = [];
                GRFData = [];
                beltSpeedSetData = [];
                beltSpeedReadData = [];
                accData = [];
                EEGData = [];
                footSwitches = [];
                events = [];
                procEMG = [];
                angleData = [];
                COPData = [];
                COMData = [];
                jointMomentsData = [];
                HreflexPin = [];
            end
            this@labData(metaData, markerData, EMGData, GRFData, ...
                beltSpeedSetData, beltSpeedReadData, accData, ...
                EEGData, footSwitches, HreflexPin);
            this.gaitEvents = events;
            this.procEMGData = procEMG;
            this.angleData = angleData;
            this.COPData = COPData;
            this.COMData = COMData;
            this.jointMomentsData = jointMomentsData;
        end
    end
    %% Property Setters
    methods
        function this = set.gaitEvents(this, events)
            if isa(events, 'labTimeSeries') || isempty(events)
                this.gaitEvents = events;
            else
                ME = MException('processedLabData:Constructor', ...
                    'events parameter is not a labTimeSeries object.');
                throw(ME);
            end
        end
        function this = set.procEMGData(this, procEMG)
            if isa(procEMG, 'processedEMGTimeSeries') || ...
                    isempty(procEMG)
                this.procEMGData = procEMG;
            else
                ME = MException('processedLabData:Constructor', ...
                    'procEMG parameter is not a processedEMGTimeSeries object.');
                throw(ME);
            end
        end
        function this = set.angleData(this, angleData)
            if isa(angleData, 'labTimeSeries') || ...
                    isempty(angleData)
                this.angleData = angleData;
            else
                ME = MException('processedLabData:Constructor', ...
                    'angleData parameter is not a labTimeSeries object.');
                throw(ME);
            end
        end
        function this = set.adaptParams(this, adaptData)
            if isa(adaptData, 'parameterSeries') || ...
                    isa(adaptData, 'labTimeSeries')
                this.adaptParams = adaptData;
            else
                ME = MException('processedLabData:Constructor', ...
                    'adaptParams parameter is not a parameterSeries object.');
                throw(ME);
            end
        end
    end
    %% Data Access Methods
    methods
        % Access method for fields not defined in raw class.
        % function partialProcEMGData = getProcEMGData(this, muscleName)
        %     partialProcEMGData = this.getPartialData('procEMGData', muscleName);
        % end
        % function list = getProcEMGList(this)
        %     list = this.getLabelList('procEMGData');
        % end
        function partialGaitEvents = getPartialGaitEvents(this, eventName)
            partialGaitEvents = ...
                this.getPartialData('gaitEvents', eventName);
        end
        % function list = getEventList(this)
        %     list = this.getLabelList('gaitEvents');
        % end
        % function partialAngleData = getAngleData(this, angleName)
        %     partialAngleData = this.getPartialData('angleData', angleName);
        % end
        % function partialParamData = getParam(this, paramName)
        %     partialParamData = this.getPartialData('adaptParams', paramName);
        % end
        % function partialParamData = getExpParam(this, paramName)
        %     partialParamData = this.getPartialData('experimentalParams', paramName);
        % end
        adaptParams = calcAdaptParams(this)
        function [alignedField, bad] = getAlignedField(this, field, ...
                events, alignmentLengths)
            [alignedField, bad] = this.(field).align(this.gaitEvents, ...
                events, alignmentLengths);
        end
    end
    %% Data Transformation Methods
    methods
        reducedThis = reduce(this, eventLabels, N)
        newThis = recomputeEvents(this)
    end
    %% Dependent Property Getters
    methods
        function expParams = get.experimentalParams(this)
            expParams = calcExperimentalParams(this);
        end
        function b = get.isSingleStride(this)
            b = isa(this, 'strideData');
        end
    end
    %% Event Processing Methods
    methods
        arrayedEvents = getArrayedEvents(this, eventList)
        [numStrides, initTime, endTime] = ...
            getStrideInfo(this, triggerEvent, endEvent)
        [numSteps, initTime, endTime, initEventSide] = ...
            getStepInfo(this, triggerEvent)
    end
    %% Stride Segmentation Methods
    methods
        [steppedDataArray, initTime, endTime] = ...
            separateIntoStrides(this, triggerEvent)
        [steppedDataArray, initTime, endTime] = ...
            separateIntoSuperStrides(this, triggerEvent)
        [steppedDataArray, initTime, endTime] = ...
            separateIntoDoubleStrides(this, triggerEvent)
        function [stridedField, bad, initTime, events] = ...
                getStridedField(this, field, events)
            warning('This is very slow and has been deprecated. Please don''t use.');
            if isa(events,'char')
                events={events};
            end
            %Step 1: separate strides by the first event
            [numStrides,initTime,endTime]=getStrideInfo(this,events{1});
            M=numStrides;
            N=length(events);
            %Step 2: for each stride, find the other events (if any)
            intermediateTimes=nan(M,N-1);
            bad=false(M,1);
            for i=1:M
                for j=1:N-1
                    aux=find(this.gaitEvents.getDataAsVector(events{j+1}) & this.gaitEvents.Time>=initTime(i) & this.gaitEvents.Time<endTime(i));
                    if length(aux)==1 %Found only one event, as expected
                        intermediateTimes(i,j) = this.gaitEvents.Time(aux);
                    else
                        bad(i)=true;
                    end
                end
            end
            %Step 3: slice timeseries
            timeBreakpoints=[initTime, intermediateTimes]';
            [slicedTS,~,~]=sliceTS(this.(field),[timeBreakpoints(:); endTime(end)],0);
            %Step 4: reshape & set to [] the slices which didn't have
            %proper events
            stridedField=reshape(slicedTS,N,M)';
        end
    end
end