Description of flipEMGdata
Home > labTools > fun > EMGanalysis > flipEMGdata.m
flipEMGdata
PURPOSE
This function swaps the first and second half of EMGdata along phaseDim,
SYNOPSIS
function [flippedEMGData] =flipEMGdata(EMGdata,phaseDim,muscleDim)
DESCRIPTION
This function swaps the first and second half of EMGdata along phaseDim,
but only for the SECOND half of the array EMGdata along dimension muscleDim
CROSS-REFERENCE INFORMATION
This function calls:
cat cat Concatenates alignedTimeSeries
fftshift fftshift Shifts alignment by half cycle
cat cat Concatenates (override)
cat cat Concatenates two parameterSeries
sliceArray sliceArray returns a subset of 'slices' of an array (indexed by inds)
This function is called by:
SOURCE CODE
function [flippedEMGData] =flipEMGdata(EMGdata,phaseDim,muscleDim)
%This function swaps the first and second half of EMGdata along phaseDim,
%but only for the SECOND half of the array EMGdata along dimension muscleDim
N=size(EMGdata,muscleDim);
EMGdata1=sliceArray(EMGdata,1:N/2,muscleDim);
EMGdata2=sliceArray(EMGdata,(N/2+1):N,muscleDim);
flippedEMGData=cat(muscleDim, EMGdata1, fftshift(EMGdata2,phaseDim));
end