Description of cell2mat
Home > labTools > classes > dataStructs > @strideData > cell2mat.m
cell2mat
PURPOSE
cell2mat Converts cell array of strideData to matrix
SYNOPSIS
function strideMat = cell2mat(strides, field, N)
DESCRIPTION
cell2mat  Converts cell array of strideData to matrix
   strideMat = cell2mat(strides, field, N) converts a cell
   array of strideData objects to a 3D matrix by extracting and
   resampling the specified field
   Inputs:
       strides - cell array of strideData objects
       field - name of property to extract (e.g.,
               'markerData', 'procEMGData')
       N - number of samples for resampling
   Outputs:
       strideMat - 3D matrix (samples x channels x strides)
                   containing resampled data
   See also: plotCell, plotCellAvg
CROSS-REFERENCE INFORMATION
This function calls:
cellisa
This function is called by:
BiofeedbackPerception
BiofeedbackSL
BiofeedbackSLBF_Percp
BiofeedbackSL_c3d
BiofeedbackVazE2B
SombricTaiChi
adaptationData
removeBiasV2
scatterPlotLab Plots up to 3 parameters as coordinates in a single cartesian axes system
experimentData
flushAndRecomputeParameters FLUSHANDRECOMPUTEPARAMETERS Discard existing parameters and recompute all.
getAlignedField getAlignedField Extracts time-aligned field data across
getStridedField getStridedField Extracts stride-segmented field data across
recomputeEvents recomputeEvents Recalculates gait events and parameters
recomputeParameters RECOMPUTEPARAMETERS Recalculate stride-by-stride adaptation parameters.
AnovaEpochs %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
groupAdaptationData
strideData
getEpochData getEpochData Returns data from all subjects in all groups for each epoch
experimentMetaData
getConditionIdxsFromName getConditionIdxsFromName Returns condition indices from names
getTrialsInCondition getTrialsInCondition Returns trial numbers in each condition
validateTrialsInCondition validateTrialsInCondition Validates trial organization
discretize discretize Averages data across phases
discretize discretize Discretizes by averaging across phases
anova anova Performs one-way ANOVA on parameters
ClusteredSynergySetCollection
plotCal PLOTCAL Plot the H-reflex recruitment or ratio calibration curve.
AddPythonData Script to process a python biofeedback data file and add the columns of
naiveDistances
JSONtxt2cell JSONtxt2cell uses json_parse and i/o to open a txt file and parse it into a cell
compareExperimentData COMPAREEXPERIMENTDATA Compare structure of two experimentData objects.
generateHreflexRecruitmentCurves % Generate H-Reflex Calibration Recruitment Curves & Other Figures
getOGspeed must load subject before running function
extractKinematicDataAtEvents EXTRACTKINEMATICDATAATEVENTS Extract markers and angles at gait event times.
reviseExperimentInfo REVISEEEXPERIMENTINFO Revise experimental session information in MAT files
GetInfoGUI GetInfoGUI GUI for collecting experimental session information.
SepCondsInExpByAudioCue Separate 1 condition into multiple in expData using timing information from audioCue.
SyncDatalog Synchronize the datlog with the rawExpData using the force signal.
GetInfoGUIbeta GETINFOGUIBETA MATLAB code for GetInfoGUIbeta.fig
errorProofInfobeta Checks feilds of GetInfoGUI to ensure entry is valid and reasonable.
errorProofInfo errorProofInfo Validates and extracts all fields from GetInfoGUI.
loadTrials loadTrials Generates rawTrialData instances for each trial.
SOURCE CODE
function strideMat = cell2mat(strides, field, N)
%cell2mat  Converts cell array of strideData to matrix
%
%   strideMat = cell2mat(strides, field, N) converts a cell
%   array of strideData objects to a 3D matrix by extracting and
%   resampling the specified field
%
%   Inputs:
%       strides - cell array of strideData objects
%       field - name of property to extract (e.g.,
%               'markerData', 'procEMGData')
%       N - number of samples for resampling
%
%   Outputs:
%       strideMat - 3D matrix (samples x channels x strides)
%                   containing resampled data
%
%   See also: plotCell, plotCellAvg
strideMat = [];
if isa(strides, 'cell') && all(cellisa(strides, 'strideData'))
    auxLst = properties('strideData');
    if any(strcmp(auxLst, field))
        eval(['testField = strides{1}.' field ';']);
        if isa(testField, 'labTimeSeries')
            M = length(strides);
            for i = 1:M
                eval(['testField = strides{i}.' field ';']);
                strideMat(:, :, i) = testField.resampleN(N)...
                    .getDataAsVector(testField.getLabels);
            end
        elseif ~isa(testField, 'double')
            for i = 1:length(strides)
                eval(['testField = strides{i}.' field ';']);
                strideMat(:, :, i) = testField;
            end
        end
    else
        ME = MException('strideDataCell2mat:unknownField', ...
            ['The provided fieldname is not a property of ' ...
            'strideData objects, or is not of labTS type.']);
        throw(ME);
    end
else
    ME = MException('strideDataCell2mat:wrongInput', ...
        'Input needs to be a cell array of strideData objects.');
    throw(ME);
end
end