Description of getSingleStanceL
Home > labTools > classes > dataStructs > @strideData > getSingleStanceL.m
getSingleStanceL
PURPOSE
getSingleStanceL Extracts left single stance phase
SYNOPSIS
function [int, dur] = getSingleStanceL(this)
DESCRIPTION
getSingleStanceL  Extracts left single stance phase
   [int, dur] = getSingleStanceL(this) extracts the phase from
   right toe off to right heel strike (left single stance)
   Inputs:
       this - strideData object
   Outputs:
       int - strideData object containing single stance phase
       dur - duration of phase in seconds
   See also: getSingleStanceR, getSwingR, getIntervalBtwEvents
CROSS-REFERENCE INFORMATION
This function calls:
getIntervalBtwEvents getIntervalBtwEvents Extracts data between two gait events
This function is called by:
getSwingR getSwingR Extracts right swing phase
strideData
SOURCE CODE
function [int, dur] = getSingleStanceL(this)
%getSingleStanceL  Extracts left single stance phase
%
%   [int, dur] = getSingleStanceL(this) extracts the phase from
%   right toe off to right heel strike (left single stance)
%
%   Inputs:
%       this - strideData object
%
%   Outputs:
%       int - strideData object containing single stance phase
%       dur - duration of phase in seconds
%
%   See also: getSingleStanceR, getSwingR, getIntervalBtwEvents
int = getIntervalBtwEvents(this, 'RTO', 'RHS');
dur = int.gaitEvents.timeRange;
end