Description of getSingleStanceR
Home > labTools > classes > dataStructs > @strideData > getSingleStanceR.m
getSingleStanceR
PURPOSE
getSingleStanceR Extracts right single stance phase
SYNOPSIS
function [int, dur] = getSingleStanceR(this)
DESCRIPTION
getSingleStanceR  Extracts right single stance phase
   [int, dur] = getSingleStanceR(this) extracts the phase from
   left toe off to left heel strike (right single stance)
   Inputs:
       this - strideData object
   Outputs:
       int - strideData object containing single stance phase
       dur - duration of phase in seconds
   See also: getSingleStanceL, getSwingL, getIntervalBtwEvents
CROSS-REFERENCE INFORMATION
This function calls:
getIntervalBtwEvents getIntervalBtwEvents Extracts data between two gait events
This function is called by:
getSwingL getSwingL Extracts left swing phase
strideData
SOURCE CODE
function [int, dur] = getSingleStanceR(this)
%getSingleStanceR  Extracts right single stance phase
%
%   [int, dur] = getSingleStanceR(this) extracts the phase from
%   left toe off to left heel strike (right single stance)
%
%   Inputs:
%       this - strideData object
%
%   Outputs:
%       int - strideData object containing single stance phase
%       dur - duration of phase in seconds
%
%   See also: getSingleStanceL, getSwingL, getIntervalBtwEvents
int = getIntervalBtwEvents(this, 'LTO', 'LHS');
dur = int.gaitEvents.timeRange;
end