set(handles.plot_button,'Enable','off');
set(handles.next_button,'Enable','off');
set(handles.back_button,'Enable','off');
set(handles.delete_button,'Enable','off');
set(handles.deleteNbutton,'Enable','off');
set(handles.save_button,'Enable','off');
set(handles.add_button,'Enable','off');
set(handles.BPdataType,'Enable','off');
set(handles.BPfield,'Enable','off');
set(handles.TPdataType,'Enable','off');
set(handles.TPfield,'Enable','off');
set(handles.condMenu, 'Enable','off');
set(handles.trialMenu,'Enable','off');
set(handles.timeSlider,'Enable','off');
set(handles.maxCheck,'Enable','off');
set(handles.defaultRadio,'Enable','off');
set(handles.kinematicRadio,'Enable','off');
set(handles.forceRadio,'Enable','off');