Description of adaptationData
Home > labTools > classes > dataStructs > @adaptationData > adaptationData.m
adaptationData
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
isaLabel isaLabel Checks if label(s) exist in dataset
isempty isempty Checks if the date equals the default value.
isaLabel isaLabel Checks if label(s) exist in dataset
subjectData
Correlations Set colors order
adaptationData
getBaseData Returns data from last 40 strides of baseline, exempting the last 5.
getEarlyLateData_v2 obtain the earliest and late data points for conditions
getEarlyLateIdxs obtain the earliest and late data points for conditions
plotAvgTimeCourse adaptDataList must be cell array of 'param.mat' file names
plotGroupedSubjectsBars
plotGroupedSubjectsBarsv2
plotGroupedSubjectsTimeCourse
plotParamBarsByConditionsv2 TODO: this file should be updated to call upon plotGroupedBars
removeBiasV2
removeBiasV3 removeBias('condition') or removeBias({'Condition1','Condition2',...})
removeBiasV4 removeBias('condition') or removeBias({'Condition1','Condition2',...})
scatterPlotLab Plots up to 3 parameters as coordinates in a single cartesian axes system
groupAdaptationData
cell2mat cell2mat Converts cell array of strideData to matrix
flipLR flipLR Flips left/right alignment
isaLabel isaLabel Checks if labels exist
minus minus Subtracts two alignedTimeSeries
isaLabel isaLabel Checks if string is contained in label array
minus minus Subtracts two labTimeSeries
parameterSeries
colorScheme Define color scheme
This function is called by:
adaptationData
removeBiasV2
removeBiasV3 removeBias('condition') or removeBias({'Condition1','Condition2',...})
removeBiasV4 removeBias('condition') or removeBias({'Condition1','Condition2',...})
makeDataObjNew makeDataObjNew Internal method to create adaptationData object
groupAdaptationData
AddPythonData Script to process a python biofeedback data file and add the columns of
SyncPython_forStatic function to incorporate biofeedback data from Python scripts into labtools
SUBFUNCTIONS
function this=adaptationData(meta,sub,data)
function this=set.data(this,data)
function tT=trialTypes(this)
function [newThis,baseValues,typeList]=removeBias(this,conditions,padWithNaNFlag,numStrides,medianFlag)
function [newThis]=removeAltBias(this,condName,strideNo,exemptStrides,medianFlag,normalizeFlag,removeBadFlag)
function [newThis,baseValues,typeList]=normalizeBias(this,conditions)
function [newThis]=normalizeToBaseline(this,labelPrefix,baseConds2)
function [newThis]=normalizeToBaselineEpoch(this,labelPrefix,baseEpoch,noMinNormFlag)
function [newThis]=removeBaselineEpoch(this,baseEpoch,labels)
function newThis=removeBadStrides(this,markAsNaNflag)
function newThis=addNewParameter(this,newParamLabel,funHandle,inputParameterLabels,newParamDescription)
function newThis=replaceLR(this)
function [biasTM,biasOG]=getBias(this,labels)
function newThis=markBadWhenMissingAny(this,labels)
function newThis=markBadWhenMissingAll(this,labels)
function newThis=renameParams(this,oldLabels,newLabels)
function newThis=getPartialParameters(this,labels)
function ageInMonths=getSubjectAgeAtExperimentDate(this)
function newThis=medianFilter(this,N)
function newThis=monoLS(this,trialBased,order,Nregularization)
function newThis=substituteNaNs(this,method)
function [labelList,descriptionList]=getParameterList(this)
function [data,inds,auxLabel]=getParamInTrial(this,label,trial)
function [data,inds,auxLabel,origTrials]=getParamInCond(this,label,condition,removeBias)
function [boolFlag,labelIdx]=isaCondition(this,cond)
function [veryEarlyPoints,earlyPoints,latePoints]=getEarlyLateData(this,labels,conds,removeBiasFlag,earlyNumber,lateNumber,exemptLast)
function [data,validStrides,everyStrideData]=getEpochData(this,epochs,labels,padWithNaNFlag)
function flags=validateEpochs(this,epochs)
function [dataE,labels,allData]=getPrefixedEpochData(this,labelPrefix,epochs,padWithNaNFlag)
function conditionIdxs=getConditionIdxsFromName(this,conditionNames)
function inds=getIndsInCondition(this,conditionNames)
function trialNums=getTrialsInCond(this,conditionNames)
function newThis=reduce(this, parametersToKeep)
function [p,anovatab,stats,postHoc,postHocEstimate,data]=anova1(this,param,conds,groupingStrides,exemptFirst,exemptLast)
function [p,anovatab,stats,postHoc,postHocEstimate,data]=kruskalwallis(this,param,conds,groupingStrides,exemptFirst,exemptLast)
function [figHandle,plotHandles]=plotParamTimeCourse(this,label,runningBinSize,trialMarkerFlag,conditions,medianFlag,plotHandles)
function dataPoints=getDataFromInds(this,inds,labels,padWithNaNFlag)
function [fh,ph]=plotTimeAndBars(this,labels,conds,binwidth,trialMarkerFlag,medianFlag,ph,numberOfStrides,monoLSfitFlag)
function [fh,ph,labels,dataE,dataRef]=plotCheckerboards(this,labelPrefix,epochs,fh,ph,refEpoch,flipLR, summFlag)
function [dataE,dataRef,labels,groups]=getCheckerboardsData(this,labelPrefix,epochs,refEpoch,flipLR)
function gAD=createSingleSubjGroup(this)
function badSubj=RemoveBadMuscles(this,badMuscles)
function [fh,ph,allData]=plotGroupedTimeAndBars(adaptDataGroups,labels,conds,binwidth,trialMarkerFlag,indivFlag,indivSubs,colorOrder,biofeedback,removeBiasFlag,groupNames,medianFlag,plotHandles,numberOfStrides)
function[fh,ph,allData]=plotGroupedTimeAndEpochBars(adaptDataGroups,labels,eps,binwidth,trialMarkerFlag,indivFlag,indivSubs,colorOrder,biofeedback,groupNames,medianFlag,removeBaseEpochFlag,alignEnd,significanceThreshold,posthocGroupFlag,posthocEpochFlag,posthocGroupByEpochFlag,posthocEpochByGroupFlag);
function groupData=createGroupAdaptData(adaptDataList, parametersToKeep, rmvDatlog)
function [veryEarlyPoints,earlyPoints,latePoints,pEarly,pLate,pChange,pSwitch]=getGroupedData(adaptDataList,label,conds,removeBiasFlag,earlyNumber,lateNumber,exemptLast);
function this=loadobj(this)
SOURCE CODE
classdef adaptationData
%ADAPTATIONDATA - Class to store all parameters of interest for every stride
%in an experiment
%   Objects of this class can be generated from experimentData by calling
%   experimentData.makeDataObj
%
%adaptationData properties:
%   metaData - object of the experimentMetaData class
%   subData - object of the subjectData class
%   data - object of the parameterSeries class
%
%adaptationData methods:
%   removeBias - subtract off mean baseline values
%   normalizeBias -
%   getParameterList - obtain an array of strings with the labels of the all parameters
%   getParamInTrial - obtain data for a parameter in a specific trial
%   getParamInCond - obtain data for a parameter in a specific condition
%   isaCondition - check whether a condition exitsts in an experiment
%   getEarlyLateData -
%   getBias -
%   getConditionIdxsFromName -
%   getIndsInCondition -
%   plotParamTimeCourse - plot the time course of a parameter
%   plotGroupedSubjectsTimeCourse -
%   plotGroupedSubjects -
%   plotGroupedSubjectsBars -
%   getGroupedData -
%   plotAvgTimeCourse -
%   groupedScatterPlot -
%   correlations -
%   See also: experimentData
    properties
        metaData %cell array with information related with the experiment (type of protocol, date, experimenter, conditions...)in a experimentMetaData object
        subData %cell array with information of the subject (DOB, sex, height, weight...)in a subjectData object
        data %cell array of parameterSeries type
    end
    properties(Hidden)
        TMbias_=[];
        OGbias_=[];
        INbias_=[];
        NIMbias_=[];
    end
    methods
        %Constructor
        function this=adaptationData(meta,sub,data)
            if nargin>0 && isa(meta,'experimentMetaData')
                this.metaData=meta;
            else
                ME=MException('adaptationData:Constructor','metaData is not an experimentMetaData type object.');
                throw(ME);
            end
            if nargin>1 && isa(sub,'subjectData')
                this.subData=sub;
            else
                ME=MException('adaptationData:Constructor','Subject data is not a subjectData type object.');
                throw(ME);
            end
            if nargin>2 && (isa(data,'parameterSeries') || isa(data,'paramData'))
                this.data=data;
            else
                ME=MException('adaptationData:Constructor','Data is not a parameterSeries type object.');
                throw(ME);
            end
        end
        function this=set.data(this,data)
          if nargin>1 && (isa(data,'parameterSeries') || isa(data,'paramData'))
              this.data=data;
          else
              ME=MException('adaptationData:setData','Data is not a parameterSeries type object.');
              throw(ME);
          end
        end
        function tT=trialTypes(this)
            if ~isempty(this.data.trialTypes)
                tT=this.data.trialTypes; %Tries to read from parameterSeries' trialType field, if it was populated, as we expect it to be with newer versions
            else %If the field was not populated, make an educated guess.
                tT=cell(1,this.metaData.Ntrials);
                for i=1:this.metaData.Ntrials
                    condInd=nan;
                   for j=1:length(this.metaData.conditionName)
                      if any(this.metaData.trialsInCondition{j}==i)
                          condInd=j;
                          break
                      end
                   end
                   if isnan(condInd)
                       tT{i}='mis';
                   elseif ~isempty(strfind(this.metaData.conditionName{condInd},'OG'))
                    tT{i}='OG';
                   elseif ~isempty(strfind(this.metaData.conditionName{condInd},'incline')) || ~isempty(strfind(this.metaData.conditionName{condInd},'hill'))
                       tT{i}='IN';
                   elseif ~isempty(strfind(this.metaData.conditionName{condInd},'NIM'))
                       tT{i}='NIM';
                   else
                       tT{i}='TM';
                   end
                end
            end
        end
        %Modifiers
        [newThis,baseValues,typeList]=removeBiasV2(this,conditions,normalizeFlag) %Going to deprecate in favor of removeBiasV3's simpler code
        [newThis,baseValues,typeList]=removeBiasV3(this,conditions,normalizeFlag)
        [newThis,baseValues,typeList]=removeBiasV4(this,conditions,normalizeFlag,padWithNaNFlag,numStrides,medianFlag)
        function [newThis,baseValues,typeList]=removeBias(this,conditions,padWithNaNFlag,numStrides,medianFlag)
        % Removes baseline value for all parameters.
        % removeBias('condition') or removeBias({'Condition1','Condition2',...})
        % removes the median value of every parameter from each trial of the
        % same type as the condition entered. If no condition is
        % specified, then the condition name that contains both the
        % type string and the string 'base' is used as the baseline
        % condition.
        %
        %INPUTS:
        %this: experimentData object
        %conditions: conditions to use as reference
        %
        %OUTPUTS:
        %newThis: experimentData object with the bias remove
        %baseValues: values used to calculated the average used to remove the bias
        %typeList; type of condition (OG or TM)
        %
        %EX:[newThis,baseValues,typeList]=adaptData.removeBias('TM base');
            if nargin<2
                conditions=[];
            end
            if nargin<3
                padWithNaNFlag=false;
            end
            if nargin<4
                numStrides=[];
            end
            if nargin<5
                medianFlag=[];
            end
            %             [newThis,baseValues,typeList]=removeBiasV3(this,conditions);
            %             %Marcela Commented this for the R01
            [newThis,baseValues,typeList]=removeBiasV4(this,conditions,[],padWithNaNFlag,numStrides,medianFlag);
            newThis.TMbias_=baseValues(strcmp(typeList,'TM'),:);
            newThis.OGbias_=baseValues(strcmp(typeList,'OG'),:);
            newThis.INbias_=baseValues(strcmp(typeList,'IN'),:);
            newThis.NIMbias_=baseValues(strcmp(typeList,'NIM'),:);
        end
        function [newThis]=removeAltBias(this,condName,strideNo,exemptStrides,medianFlag,normalizeFlag,removeBadFlag)
           %Same as removeBias, but for an arbitrary subset of strides
           %(e.g. remove the mean of the first 20 strides of adaptation)
           if nargin<7 || isempty(removeBadFlag) || removeBadFlag==0
               base=getEarlyLateData_v2(this,[],condName,0,strideNo,exemptStrides,exemptStrides); %Not removing bad strides
           else
               base=getEarlyLateData_v2(this.removeBadStrides,[],condName,0,strideNo,exemptStrides,exemptStrides); %Removing bad strides for the purpose of baseline computations
           end
           if nargin<5 || isempty(medianFlag) || medianFlag==0
               base=nanmean(squeeze(base{1}));
           else
               base=nanmedian(squeeze(base{1}));
           end
           newThis=this;
           dataOld=this.data.Data;
            if normalizeFlag==0
                %added lines to ensure that if certain parameters never
                %have a baseline to remove the bias, they are not assigned
                %as NaN from the bsxfun @minus.
                %data(isnan(data))=-100000;
                base(isnan(base))=0;%do not subtract a bias if there is no bias to remove
                newData=bsxfun(@minus,dataOld,base); %Substracting baseline
            else
                base(isnan(base))=1;%do not subtract a bias if there is no bias to remove
                newData=bsxfun(@rdivide,dataOld,base); %Dividing by baseline
            end
            M=newThis.data.fixedParams;
            newThis.data.Data(:,M+1:end)=newData(:,newThis.data.fixedParams+1:end); %Not removing bias for 'fixed' params: initTime, finalTime, trial, good, bad
            %newData(isnan(data))=nan;
            if isempty(this.TMbias_) %Default if bias was not removed previously
                newThis.TMbias_=[zeros(1,M) base(M+1:end)];
                newThis.OGbias_=[zeros(1,M) base(M+1:end)];
            else
                if normalizeFlag==0
                    newThis.TMbias_=newThis.TMbias_+[zeros(1,M) base(M+1:end)];
                    newThis.OGbias_=newThis.OGbias_+[zeros(1,M) base(M+1:end)];
                else
                    newThis.TMbias_=newThis.TMbias_.*[zeros(1,M) base(M+1:end)];
                    newThis.OGbias_=newThis.OGbias_.*[zeros(1,M) base(M+1:end)];
                end
            end
        end
        function [newThis,baseValues,typeList]=normalizeBias(this,conditions)
            if nargin<2
                conditions=[];
            end
            [newThis,baseValues,typeList]=removeBiasV3(this,conditions,1);
        end
        function [newThis]=normalizeToBaseline(this,labelPrefix,baseConds2)
           %This normalization takes the last N strides from a given
           %'baseline' condition and uses it to normalize values of the
           %parameter for the whole experiment.
           %Meant to be used for EMG parameters ONLY
           %It creates NEW parameters with the same name, and the 'Norm' prefix.
           %See also: EMGnormalization (example) parameterSeries.normalizeToBaseline
           error('Deprecated. Use normalizeToBaselineEpoch instead.')
            warning('This function is meant to be used for EMG parameters only. Use at own risk.')
            if nargin<3
                baseConds2=[];
            end
            if nargin<2
                error('Need to provide a prefix for parameters')
            end
            if isa(labelPrefix,'char')
                labelPrefix={labelPrefix};
            end
            if nargin<2 || isempty(baseConds2)
                [baseConds,tType]=this.getBaseConditions;
            else
                baseConds=baseConds2;
            end
            if length(baseConds)>1 %More than 1 baseline found
               idx=find(strcmp(tType,'TM'));
               warning(['More than 1 baseline condition found or provided. Using the first that matches TM type trials: ' baseConds{idx}])
               baseCond=baseConds{idx};
            end
            for i=1:length(labelPrefix)
                %First: get all parameters with given prefix
                labels=this.data.getLabelsThatMatch(['^' labelPrefix{i} '\d+$']);
                %Second: get baseline data for those
                [baseData]=getBaseData(this,baseCond,labels);
                range=squeeze(nanmean(baseData,2));
                rangeValues=[min(range) max(range)];
                this.data=this.data.normalizeToBaseline(labels,rangeValues);
            end
            newThis=this;
        end
        function [newThis]=normalizeToBaselineEpoch(this,labelPrefix,baseEpoch,noMinNormFlag)
           %This normalization takes the last N strides from a given
           %'baseline' condition and uses it to normalize values of the
           %parameter for the whole experiment.
           %Meant to be used for EMG parameters ONLY
           %It creates NEW parameters with the same name, and the 'Norm' prefix.
           %See also: EMGnormalization (example) parameterSeries.normalizeToBaseline
            warning('This function is meant to be used for EMG parameters only. Use at own risk.')
            if nargin<2
                error('Need to provide a prefix for parameters')
            end
            if isa(labelPrefix,'char')
                labelPrefix={labelPrefix};
            end
            if nargin<4 || isempty(noMinNormFlag)
                noMinNormFlag=0;
            end
            [baseData,label]=this.getPrefixedEpochData(labelPrefix,baseEpoch);
            baseData=reshape(baseData,size(label,1),numel(labelPrefix));
            rangeValues=[min(baseData); max(baseData)];
            if noMinNormFlag==1
                rangeValues(1,:)=0;
            end
            for i=1:length(labelPrefix)
                if ismember('Description',baseEpoch.Properties.VarNames)
                    this.data=this.data.linearStretch(label(:,i),rangeValues(:,i),['baseEcpoh Info: ' baseEpoch.Description{1}]);
                else
                    this.data=this.data.linearStretch(label(:,i),rangeValues(:,i));
                end
            end
            newThis=this;
        end
        function [newThis]=removeBaselineEpoch(this,baseEpoch,labels)
            if nargin<3 || isempty(labels)
                %nop
                labels=this.data.labels;
            else
                this=this.getPartialParameters(labels);
            end
            [baseData]=this.getEpochData(baseEpoch,labels);
            newThis=this.removeBias;
            %newThis.data.Data=this.data.Data-baseData';
            %fix any parameters that should not have bias removal
            [~,idxs]=this.data.isaParameter({'bad','good','trial','initTime','finalTime','direction'});
            if ~isempty(idxs)
                newThis.data.Data(:,idxs(idxs>0))=this.data.Data(:,idxs(idxs>0));
            end
        end
        function newThis=removeBadStrides(this,markAsNaNflag)
            if nargin<2 || isempty(markAsNaNflag)
               markAsNaNflag=false;
            end
            if isa(this.data,'paramData') %What does this do?
                newParamData=this.data;
            else
                aux=this.data;
                inds=~aux.bad;
                if ~markAsNaNflag
                    newParamData=parameterSeries(aux.Data(inds,:),aux.labels,aux.hiddenTime(inds),aux.description);
                    newParamData=newParamData.setTrialTypes(aux.trialTypes);
                else
                    newParamData=this.data.markBadStridesAsNan;
                end
            end
            newThis=adaptationData(this.metaData,this.subData,newParamData);
        end
        function newThis=addNewParameter(this,newParamLabel,funHandle,inputParameterLabels,newParamDescription)
           %This function allows to compute new parameters from other existing parameters and have them added to the data.
           %This is useful when trying out new parameters without having to
           %recompute all existing parameters.
           %INPUT:
           %newPAramLAbel: string with the name of the new parameter
           %funHandle: a function handle with N input variables, whose
           %result will be used to compute the new parameter
           %inputParameterLabels: the parameters that will replace each of
           %the variables in the funHandle
           %EXAMPLE:
           %I want to define a new normalized version of the contributions,
           %that divides contributions by avg. step time and avg. step
           %velocity, so that the velocity contribution is now a
           %measure of belt-speed ratio. In order to do that, I will take
           %the velocityContributionAlt (which already exists and is
           %velocityContribution divided by strideTime, so it is just half
           %the difference of velocities) and then divide it by velocity sum.
           %Velocity sum can be computed by dividing stepTimeContribution
           %by stepTimeDifference (there are other possibilities to compute
           %the same thing. The final equation will look like this:
           %newVelocityContribution = velocityContributionAlt./(2*stepTimeContribution/stepTimeDiff)
           %This can be implemented as:
           %newThis = this.addNewParameter('newVelocityContribution',@(x,y,z)x./(2*y./z),{'velocityContributionAlt','stepTimeContribution','stepTimeDiff'},'velocityContribution normalized to strideTime times average velocity');
           newPS=this.data.addNewParameter(newParamLabel,funHandle,inputParameterLabels,newParamDescription);
           this.data=newPS;
           newThis=this;
        end
        function newThis=replaceLR(this)
            %Idea: get any label that uses 'L' or 'R' and replace it by 'S'
            %and 'F' as corresponds.
            %Also need to write the inverse function
        end
        function [biasTM,biasOG]=getBias(this,labels)
            if isempty(this.TMbias_)
                warning('This adaptationData object is not unbiased.')
                bias=[];
            else
                if nargin>1 && ~isempty(labels)
                    [boolFlag,idx]=this.data.isaLabel(labels);
                    biasOG=this.OGbias_(idx(boolFlag));
                    biasTM=this.TMbias_(idx(boolFlag));
                else %Fast eval
                    biasOG=this.OGbias_;
                    biasTM=this.TMbias_;
                end
            end
        end
        function newThis=markBadWhenMissingAny(this,labels)
            newThis=this;
            newThis.data=newThis.data.markBadWhenMissingAny(labels);
        end
        function newThis=markBadWhenMissingAll(this,labels)
            newThis=this;
            newThis.data=newThis.data.markBadWhenMissingAll(labels);
        end
        function newThis=renameParams(this,oldLabels,newLabels)
              [b,ii]=isaLabel(this.data,oldLabels);
              if any(b)
              newL=this.data.labels;
              newL(ii(b))=newLabels(b);
              newParam=parameterSeries(this.data.Data,newL,this.data.hiddenTime,this.data.description,this.data.trialTypes);
              newThis=this;
              newThis.data=newParam;
              %unique(this.data.stridesTrial)
              %unique(newThis.data.stridesTrial)
              else
                  newThis=this;
              end
        end
        function newThis=getPartialParameters(this,labels)
           newThis=this;
           newThis.data=this.data.getDataAsPS(labels);
        end
        function ageInMonths=getSubjectAgeAtExperimentDate(this)
            if ~isempty(this.subData.age)
                ageInMonths=this.subData.age*12; %In months
            elseif ~isempty(this.subData.dateOfBirth)
                warning('expData:subjectDOB','subject metadata contains DOB, this may be a privacy issue.')
                dob=this.subData.dateOfBirth;
                testData=this.metaData.date;
                [ageInMonths]=testData.timeSince(dob);
            else
                error('expData:subjectDOB','Could not establish subject age at experiment time.')
            end
        end
        function newThis=medianFilter(this,N)
            newThis=this;
            newThis.data=this.data.medianFilter(N);
        end
        function newThis=monoLS(this,trialBased,order,Nregularization)
            %TODO: check that the submodule containing monoLS is in the
            %path, or this will fail
            newThis=this;
            %For each condition, or trial:
            if trialBased==1
                t=unique(this.data.getDataAsVector('trial'));
                for i=1:length(t)
                    [partialData,indData]=this.getParamInTrial([],t(i));
                    aux=monoLS(partialData(:,6:end),[],order,Nregularization);
                    newThis.data.Data(indData,6:end)=aux;
                end
            else %Condition based
                for i=1:length(this.metaData.trialsInCondition)
                    [partialData,indData]=this.getParamInCond([],i);
                    if ~isempty(partialData)
                      aux=monoLS(partialData(:,6:end),[],order,Nregularization);
                      newThis.data.Data(indData,6:end)=aux;
                    end
                end
            end
        end
        function newThis=substituteNaNs(this,method)
            if nargin<2 || isempty(method)
                method='linear';
            end
            newThis=this;
            newThis.data=this.data.substituteNaNs(method);
        end
        %Other I/O functions:
        function [labelList,descriptionList]=getParameterList(this)
        %obtain an array of strings with the labels of the all parameters
        %INPUT:
        %this: experimentData object
        %
        %OUTPUT:
        %labelList: array of strings with the labels name
        %
        %EX: labelList=adaptData.getParameters;
            labelList=this.data.labels;
            descriptionList=this.data.description;
        end
        function [data,inds,auxLabel]=getParamInTrial(this,label,trial)
        %Obtain strides information for a parameter in a specific trial
        %
        %INPUTS:
        %this: experimentData object
        %label: Specific parameter to required information (alphaFast,Sout,velocityContribution....)
        %trial: number of the trial that information is needed
        %
        %OUTPUTS:
        %data: information of the parameter in the trial
        %inds: Position of data points in the matrix
        %auxLabel: Parameter evaluated
        %
        %Ex: [data,inds,auxLabel]=adaptData.getParamInTrial('alphaFast',2)
        %See also: adaptationData.getParamInCond
            if isempty(label)
                label=getParameterList(this);
            end
            if isa(label,'char')
                auxLabel={label};
            else
                auxLabel=label;
            end
            % validate label(s)
            [boolFlag,labelIdx]=this.data.isaParameter(auxLabel);
            % validate trial(s)
            trialNum = [];
            for t=trial
                if isempty(this.data.indsInTrial(t))
                    warning(['Trial number ' num2str(t) ' is not a trial in this experiment.'])
                else
                    trialNum(end+1)=t;
                end
            end
            %get data
            inds=cell2mat(this.data.indsInTrial(trialNum));
            data=this.data.Data(inds,labelIdx(boolFlag==1));
            auxLabel=this.data.labels(labelIdx(boolFlag==1));
        end
        function [data,inds,auxLabel,origTrials]=getParamInCond(this,label,condition,removeBias)
        %Obtain strides information for a parameter in a condition.
        %INPUTS:
        %this: experimentData object
        %label: Specific parameter to required information (alphaFast,Sout,velocityContribution....)
        %condition: Specific condition that information is needed
        %removeBias: 1 to activate function to remove bias, 0 or empty to no activate function
        %
        %OUTPUTS:
        %data: information of the parameter in the trial
        %inds: Position of data points in the matrix
        %auxLabel: Parameter evaluated
        %origTrials: Numbers of trials that compose the condition
        %
        %EX: adaptData.getParamInCond('alphaFast','OG base',0)
        %See also: adaptationData.getParamInTrial
        %          adaptationData.removeBias
%             if nargin<4 || isempty(removeBias)
%                 removeBias=0;
%             end
            if nargin<2 || isempty(label)
                label=this.data.labels;
            end
            if isa(label,'char')
                auxLabel={label};
            else
                auxLabel=label;
            end
            % validate label(s)
            [boolFlag,labelIdx]=this.data.isaParameter(auxLabel);
            % validate condition(s)
            if nargin<3 || isempty(condition) || (~isa(condition,'cell') && any(isnan(condition)))
                condition=this.metaData.conditionName(~cellfun(@isempty,this.metaData.conditionName));
            end
            condNum = [];
            if isa(condition,'char')
                condition={condition};
            end
            if isa(condition,'cell')
                condNum=this.metaData.getConditionIdxsFromName(condition);
                if any(isnan(condNum))
                    warning([this.subData.ID ' did not perform condition ''' condition{isnan(condNum)} ''''])
                end
                condNum(isnan(condNum))=[];
            elseif isa(condition,'double')
                condNum=condition;
            else
                ME=MException('AdaptData.getParamInCond','Condition has to be char, cell of char, or double');
                throw(ME)
            end
            %get data
            if nargin>3 && ~isempty(removeBias) %Default: no bias removal
                error('Remove bias is no longer supported from within getParamInCond. Remove bias first and then call this function')
            end
            trials=cell2mat(this.metaData.trialsInCondition(condNum));
            inds=cell2mat(this.data.indsInTrial(trials));
            origTrials=[];
            for i=1:length(trials)
                origTrials(end+1:end+length(this.data.indsInTrial(i)))=i; %What's the purpose of this??
            end
            data=this.data.Data(inds,labelIdx(boolFlag==1));
            auxLabel=this.data.labels(labelIdx(boolFlag==1));
        end
        function [boolFlag,labelIdx]=isaCondition(this,cond)
            if isa(cond,'char')
                auxCond{1}=cond;
            elseif isa(cond,'cell')
                auxCond=cond;
            elseif isa(cond,'double')
                auxCond=this.metaData.conditionName(cond);
            end
            N=length(auxCond);
            boolFlag=false(N,1);
            labelIdx=zeros(N,1);
            for j=1:N
                for i=1:length(this.metaData.conditionName)
                    if strcmpi(auxCond{j},this.metaData.conditionName{i})
                        boolFlag(j)=true;
                        labelIdx(j)=i;
                        break;
                    end
                end
            end
            for i=1:length(boolFlag)
                if boolFlag(i)==0
                    warning([this.subData.ID ' did not perform condition ''' cond{i} ''' or the condition is misspelled.'])
                end
            end
        end
        function [veryEarlyPoints,earlyPoints,latePoints]=getEarlyLateData(this,labels,conds,removeBiasFlag,earlyNumber,lateNumber,exemptLast)
        %obtain the earliest and late data points for conditions
        %allow to eliminate very late data points
        %Predefine values:
        %earlyNumber=5
        %veryEarlyPoints=3
        %latePoints=20
        %exemptLast=5
        %
        %INPUTS:
        %this:experimentData object
        %labels: parameters to plot
        %conds: condition that information is needed
        %removeBiasFlag:1 to activate function to remove bias, 0 or empty to no activate function
        %earlyNumber:number of strides to take as earliest values
        %lateNumber: number of strides to take as late values
        %exemptLast: number of strides to discard
        %OUTPUTS:
        %veryEarlyPoints:  value of the 3 strides on the condition
        %earlyPoints: value of the earliest strides
        %latePoints: value of the late strides
        %
        %EX:[veryEarlyPoints,earlyPoints,latePoints]=adaptData.getEarlyLateData({'Sout'},{'TM base'},1,5,40,5);
            N1=3;%all(cellfun(@(x) isa(x,'char'),conds))
            if isa(conds,'char')
                conds={conds};
            elseif ~isa(conds,'cell') && ~all(cellfun(@(x) isa(x,'char'),conds))
                error('adaptationData:getEarlyLateData','Conditions must be a string or a cell array containing strings.');
            end
            nConds=length(conds);
            if nargin<2 || ~(isa(labels,'char') || (isa(labels,'cell') && all(cellfun(@(x) isa(x,'char'),labels)) ))
                error('adaptationData:getEarlyLateData','Labels must be a string or a cell array containing strings.')
            end
            if nargin<5 || isempty(earlyNumber)
                N2=5; %early number of points
            else
                N2=earlyNumber;
            end
            if nargin<6 || isempty(lateNumber)
                N3=20; %late number of points
            else
                N3=lateNumber;
            end
            if nargin<7 || isempty(exemptLast)
                Ne=5;
            else
                Ne=exemptLast;
            end
            if nargin<4 || isempty(removeBiasFlag)
                removeBiasFlag=1; %Default
            end
            [dataPoints]=getEarlyLateData_v2(this,labels,conds,removeBiasFlag,[N1,N2,-N3],Ne,0);
            veryEarlyPoints=dataPoints{1};
            earlyPoints=dataPoints{2};
            latePoints=dataPoints{3};
            warning('adaptationData:getEarlyLateData','This function is being deprecated, use getEarlyLateDatav2 instead')
        end
        function [data,validStrides,everyStrideData]=getEpochData(this,epochs,labels,padWithNaNFlag)
            %INPUTS:
            %this must be adaptationData object
            %epochs must be a dataset created with defineEpochs()
            %labels is string or cell-array of strings to be used as parameter names
            %OUTPUT:
            %data: length(labels) x length(epochs) matrix containing requested data
            %Ex:[data,validStrides,everyStrideData]=adaptData.getEpochData(epochs,{'doubleSupportFast'},0);
            %Manage inputs:
            if isa(labels,'char')
                labels={labels};
            end
            if nargin<4 || isempty(padWithNaNFlag)
                padWithNaNFlag=false;
            end
            %First: validate epochs:
            valid=this.validateEpochs(epochs);
            %Second: get data
            removeBiasFlag=0;
            conds=epochs.Condition;
            numberOfStrides=epochs.Stride_No .* sign(epochs.EarlyOrLate-.5);
            exemptLast=epochs.ExemptLast;
            exemptFirst=epochs.ExemptFirst;
            data=nan(length(labels),length(epochs));
            validStrides=nan(length(epochs),1);
            summaryFlag=epochs.summaryMethod;
            allData=cell(length(valid),1);
            for i=1:length(valid) %Each valid epoch
                if valid(i)
                    [dataPoints]=getEarlyLateData_v2(this,labels,conds{i},removeBiasFlag,numberOfStrides(i),exemptLast(i),exemptFirst(i),padWithNaNFlag);%Get data
                    %Summarize it:
                    summFun=str2func(summaryFlag{i});
                    allData{i}=reshape(dataPoints{1},abs(numberOfStrides(i)),numel(labels));
                    data(:,i)=reshape(summFun(allData{i},1),numel(labels),1);
                    validStrides(i)=sum(any(~isnan(allData{i}))); %Counting non-nan values for any label involved (if one parameter is non-nan for a stride, the stride is valid)
                else
                    warning('Invalid epoch found, returning NaNs')
                    data(:,i)=nan(numel(labels),1);
                    allData{i}=nan(abs(numberOfStrides(i)),numel(labels));
                end
            end
            if nargout>2
                everyStrideData=allData;
            end
        end
        function flags=validateEpochs(this,epochs)
            flags=true(length(epochs),1);
            for i=1:length(epochs) %for each epoch
                if this.isaCondition(epochs.Condition(i)) %all good
                    %nop
                else
                    warning(['Invalid epoch ' epochs.Properties.ObsNames{i} ' for subject ' this.subData.ID])
                    flags(i)=false;
                end
            end
        end
        function [dataE,labels,allData]=getPrefixedEpochData(this,labelPrefix,epochs,padWithNaNFlag)
            %This is meant to be used with parameters that end in
            %'s1...s12' as are computed for EMG and angles. The 's' must be
            %included in the labelPrefixes (to allow for other options too)
            if isa(labelPrefix,'char')
                labelPrefix={labelPrefix};
            end
            if nargin<4 || isempty(padWithNaNFlag)
                padWithNaNFlag=false; %DMMO
            end
            labelPrefix=reshape(labelPrefix,1,numel(labelPrefix)); %Putting in row form
            aux=this.data.getLabelsThatMatch(['^' labelPrefix{1} '[ ]?\d+$']); %Assuming same suffix for all
            if isempty(aux)
                error('Fail: did not find any parameters with the given prefixes')
                return
            end
            Np=length(aux);
            suffixes=cellfun(@(x) x(length(labelPrefix{1})+1:end),aux,'UniformOutput',false); %Extracting suffixes, I am lazy
            labels=strcat(repmat(labelPrefix,Np,1),repmat(suffixes,1,length(labelPrefix))); %To do
            [dataE,~,allData]=this.getEpochData(epochs,labels(:),padWithNaNFlag);
        end
        function conditionIdxs=getConditionIdxsFromName(this,conditionNames)
            %Looks for condition names that are similar to the ones given
            %in conditionNames and returns the corresponding condition idx
            %ConditionNames should be a cell array containing a string or
            %another cell array of strings in each of its cells.
            %E.g. conditionNames={'Base','Adap',{'Post','wash'}}
            conditionIdxs=this.metaData.getConditionIdxsFromName(conditionNames);
        end
        function inds=getIndsInCondition(this,conditionNames)
            %Get condition indexes if not already provided:
            if isa(conditionNames,'char') || isa(conditionNames,'cell')
                conditionIdxs=this.metaData.getConditionIdxsFromName(conditionNames);
            else
                conditionIdxs=conditionNames;
            end
            inds={};
            for i=1:length(conditionIdxs)
                if ~isnan(conditionIdxs)
                    %Get trials in each condition:
                    trials=cell2mat(this.metaData.trialsInCondition(conditionIdxs(i)));
                    %Now, get inds in each trial:
                    inds{i}=cell2mat(this.data.indsInTrial(trials));
                else
                    inds{i}=[];
                end
            end
        end
        function trialNums=getTrialsInCond(this,conditionNames)
            trialNums=this.metaData.getTrialsInCondition(conditionNames);
        end
        function newThis=reduce(this, parametersToKeep)
            newThis=this;
            newThis.data=newThis.data.getDataAsPS(parametersToKeep);
        end
        %Stats testing:
        % 1) Multiple groups
        function [p,anovatab,stats,postHoc,postHocEstimate,data]=anova1(this,param,conds,groupingStrides,exemptFirst,exemptLast)
            warning('This needs to be moved to studyData or something like that')
            %Post-hoc is Bonferroni corrected t-test
            [data]=getEarlyLateData_v2(this,param,conds,0,groupingStrides,exemptLast,exemptFirst);
            for i=1:length(data)
                group{i}=repmat([1:length(conds)]',1,abs(groupingStrides(i))) + (i-1)*length(conds);
            end
            newData=cell2mat(data); %This concatenates (cat) the data along the second dimension by default, new Data should be a 2-D array of conditionxs x strides
            newGroups=cell2mat(group);
            [p,anovatab,stats]=anova1(newData(:),newGroups(:),'off');
            %Tukey-Kramer post-hoc:
            c=multcompare(stats); %By default uses tukey-kramer / honest signficant difference
            M=length(conds)*length(groupingStrides);
            postHoc=nan(M);
            postHocEstimate=nan(M);
            postHoc(sub2ind([M,M],c(:,1),c(:,2)))=c(:,6);
            postHocEstimate(sub2ind([M,M],c(:,1),c(:,2)))=c(:,4);
        end
        function [p,anovatab,stats,postHoc,postHocEstimate,data]=kruskalwallis(this,param,conds,groupingStrides,exemptFirst,exemptLast)
            warning('This needs to be moved to studyData or something like that')
            if isa(param,'char')
                param={param};
            end
            if length(param)>1
                for i=1:length(param)
                [p{i},anovatab{i},stats{i},postHoc{i},postHocEstimate{i},data{i}]=kruskalwallis(this,param{i},conds,groupingStrides,exemptFirst,exemptLast);
                end
            else
            %Post-hoc is a Bonferroni corrected Mann-Whitney-Wilcoxon U
            %(ranked sum) test.
            [data]=getEarlyLateData_v2(this,param,conds,0,groupingStrides,exemptLast,exemptFirst);
            for i=1:length(data)
                group{i}=repmat([1:length(conds)]',1,abs(groupingStrides(i))) + (i-1)*length(conds);
            end
            newData=cell2mat(data); %This concatenates (cat) the data along the second dimension by default, new Data should be a 2-D array of conditionxs x strides
            newGroups=cell2mat(group);
            [p,anovatab,stats]=kruskalwallis(newData(:),newGroups(:),'off');
            M=length(conds)*length(groupingStrides);
            postHoc=nan(M);
            postHocEstimate=nan(M);
            %Tukey-Kramer post-hoc:
            %c=multcompare(stats); %By default uses tukey-kramer / honest signficant difference
            %postHoc(sub2ind([M,M],c(:,1),c(:,2)))=c(:,6);
            %postHocEstimate(sub2ind([M,M],c(:,1),c(:,2)))=c(:,4);
            %MWW-U post-hoc:
            for i=1:M
                for j=i+1:M
                    [p,~,s]=ranksum(newData(newGroups==i),newData(newGroups==j));
                    postHoc(i,j)=p;
                    postHocEstimate(i,j)=s.zval;
                end
            end
            end
        end
        %function [p,data]=twoSampleTtest()
        %
        %end
        %function [p,data]=twoSampleMWWU()
        %
        %end
        %Display functions:
        function [figHandle,plotHandles]=plotParamTimeCourse(this,label,runningBinSize,trialMarkerFlag,conditions,medianFlag,plotHandles)
                    %Plot of the behaviour of parameters through the different conditions
            %specify the parameter behaviour on each condition and trial
            %
            %INPUTS:
            %this:experimentData object
            %label: parameters to plot
            %runningBinSize: number of data points to considered to make an average
            %trialMarkerFlag: 1 to identify the different trials that compose a single condition.
            %
            %OUTPUT:
            %figHandle: number of the figure where is the plot
            %
            %EX: adaptData.plotParamTimeCourse('spatialContribution',2,1)
            if isa(label,'char')
                label={label};
            end
            if nargin<4 || isempty(trialMarkerFlag)
                trialMarkerFlag=0;
            end
            if nargin<3 || isempty(runningBinSize)
                runningBinSize=1;
            end
            if nargin<5 || isempty(conditions)
                conditions=this.metaData.conditionName;
            end
            if nargin<6 || isempty(medianFlag)
                medianFlag=[];
            end
            if nargin<7
                plotHandles=[];
            end
            figHandle=adaptationData.plotAvgTimeCourse({this},label(:)',conditions,runningBinSize,trialMarkerFlag,[],[],[],[],[],[],medianFlag,plotHandles);
        end
        [inds,names]=getEarlyLateIdxs(this,conds,numberOfStrides,exemptLast,exemptFirst)
        [dataPoints]=getEarlyLateData_v2(this,labels,conds,removeBiasFlag,numberOfStrides,exemptLast,exemptFirst,padWithNaN)
        [figHandle,plotHandles]=plotParamBarsByConditionsv2(this,label,number,exemptLast,exemptFirst,condList,mode,plotHandles);
        function dataPoints=getDataFromInds(this,inds,labels,padWithNaNFlag)
            %Returns data associated to certain stride indexes (e.g. strides 1, 3, 10:15, 21)
            %Inds comes from a call to getEarlyLateIdxs:
            %[inds]=this.getEarlyLateIdxs(conds,numberOfStrides,exemptLast,exemptFirst);
            if nargin<3 || isempty(labels) %More efficient call for when we want everything
                data=this.data.Data;
            else
                data=this.data.getDataAsVector(labels);
            end
            if nargin<4 || isempty(padWithNaNFlag)
               padWithNaNFlag=false;
            end
            nConds=size(inds{1},2);
            nLabels=size(data,2);
            for j=1:length(inds)
                nSteps=size(inds{j},1);
                %for i=1:nConds
                %    dataPoints{j}(i,:,:)=data(inds{j}(:,i),:);
                %end
                %This line does the same as the for loop commented above:
                if any(isnan(inds{j}(:)))
                    if ~padWithNaNFlag
                        error('adaptationData:getDataFromInds',['Could not retrieve for subject ' this.subData.ID ' because some of the indexes given are NaN.'])
                    else
                    %A less drastic option:
                        warning('adaptationData:getDataFromInds',['Index strides for ' this.subData.ID ' are NaN. Data will be padded with NaNs.'])
                        inds{j}=inds{j}';
                        auxInds=inds{j}(~isnan(inds{j}(:)));
                        auxData=nan(numel(inds{j}),nLabels);
                        auxData(~isnan(inds{j}(:)),:)=data(auxInds,:);
                        dataPoints{j}=reshape(auxData,nConds,nSteps,nLabels);
                    end
                else
                    dataPoints{j}=reshape(data(inds{j}',:),nConds,nSteps,nLabels);
                end
            end
        end
        function [fh,ph]=plotTimeAndBars(this,labels,conds,binwidth,trialMarkerFlag,medianFlag,ph,numberOfStrides,monoLSfitFlag)
            %Plots time courses and early/late averaged data in bar form
            %INPUTS:
            %monoLSfitFlag: a value in the [0,3] integer range. 0 plots
            %no fits, 1 plots condition based fit, 2 plots trial based fit,
            %3 plots condition & trial based fits
            %Ex: adaptData.plotTimeAndBars({'spatialContributionPNorm'},{'TM base'},5,1,[],[],[5 -40],[])
            fh=figure;
            M=length(labels);
            if nargin<7 || isempty(ph) || size(ph,1)~=M || size(ph,2)~=2
            clear ph
            for i=1:M
                ph(i,1)=subplot(M,3,[1:2]+3*(i-1));
                ph(i,2)=subplot(M,3,[3]+3*(i-1));
            end
            end
            %Defaults:
            plotHandles=[]; %Not allowed
            exemptFirst=1;
            exemptLast=5;
            mode=[];
            %Time courses:
            this.plotParamTimeCourse(labels,binwidth,trialMarkerFlag,conds,medianFlag,ph(:,1));
            if mod(monoLSfitFlag,2)==1 %Add condition based monoLS fits if flag=1,3
                % Third plot: use monotonic LS, constraining derivatives up to 2nd order to have no sign changes, using no regularization, and fitting a single function for each condition
                order=1;
                reg=1;
                medianAcrossSubj=0;
                trialBased=0;
                filterFlag=[medianAcrossSubj,order,reg,trialBased];
                colorOrder=repmat(.6*ones(1,3),3,1); %Changing colors for plot
                binWidth=1;
                %Do the plot:
                adaptationData.plotAvgTimeCourse(this,labels,conds,binWidth,[],[],[],colorOrder,[],[],[],filterFlag,ph(:,1));
            end
            if monoLSfitFlag>1 %Add trial based monoLS fits if flag=2,3
                % Third plot: use monotonic LS, constraining derivatives up to 2nd order to have no sign changes, using no regularization, and fitting a single function for each TRIAL
                order=1;
                reg=1;
                medianAcrossSubj=0;
                trialBased=1;
                filterFlag=[medianAcrossSubj,order,reg,trialBased];
                colorOrder=repmat(0*ones(1,3),3,1); %Changing colors for plot
                binWidth=1;
                %Do the plot:
                adaptationData.plotAvgTimeCourse(this,labels,conds,binWidth,[],[],[],colorOrder,[],[],[],filterFlag,ph(:,1));
            end
            %Add bars:
            this.plotParamBarsByConditionsv2(labels,numberOfStrides,exemptLast,exemptFirst,conds,mode,ph(:,2));
            for i=1:M
                subplot(ph(i,1));
                grid on
                axis tight
                aa=axis;
                subplot(ph(i,2));
                grid on
                ab=axis;
                axis([ab(1:2) aa(3:4)])
                if i~=M
                    ph(i,1).XTickLabel={};
1000                     ph(i,2).XTickLabel={};
1001                 else
1002                     subplot(ph(i,1))
1003                     legend off
1004                 end
1005                 ph(i,2).Title.String=labels{i};
1006             end
1007         end
1008
1009         function [fh,ph,labels,dataE,dataRef]=plotCheckerboards(this,labelPrefix,epochs,fh,ph,refEpoch,flipLR, summFlag)
1010             %This is meant to be used with parameters that end in
1011             %'s1...s12' as are computed for EMG and angles. The 's' must be
1012             %included in the labelPrefixes (to allow for other options too)
1013             %summFlag: represents how do we want to summarize the data
1014             %across strides (e.g., nanmean or nanmedian)
1015             %See also: groupAdaptationData.plotCheckerboards
1016
1017             if nargin<7 || isempty(flipLR)
1018                 flipLR=false;
1019             end
1020             if nargin<4
1021                 fh=[];
1022             end
1023             if nargin<5
1024                 ph=[];
1025             end
1026             if nargin<6
1027                 refEpoch=[];
1028             end
1029             if nargin<8
1030                 summFlag=[];
1031             end
1032            [fh,ph,labels,dataE,dataRef]=this.createSingleSubjGroup.plotCheckerboards(labelPrefix,epochs,fh,ph,refEpoch,flipLR,summFlag); %Call onto groupAdaptData method
1033         end
1034
1035         function [dataE,dataRef,labels,groups]=getCheckerboardsData(this,labelPrefix,epochs,refEpoch,flipLR)
1036             %This is meant to be used with parameters that end in
1037             %'s1...s12' as are computed for EMG and angles. The 's' must be
1038             %included in the labelPrefixes (to allow for other options too)
1039             %See also: groupAdaptationData.getCheckerboardsData
1040
1041             if nargin<5 || isempty(flipLR)
1042                 flipLR=false;
1043             end
1044
1045             if nargin<4
1046                 refEpoch=[];
1047             end
1048             [dataE,dataRef,labels,groups]=this.createSingleSubjGroup.getCheckerboardsData(labelPrefix,epochs,refEpoch,flipLR); %Call onto groupAdaptData method
1049         end
1050
1051
1052         function gAD=createSingleSubjGroup(this)
1053             gAD=groupAdaptationData({this.subData.ID},{this},this.subData.ID);
1054         end
1055
1056
1057         function badSubj=RemoveBadMuscles(this,badMuscles)
1058             %This is a function that change the values of the "bad" muscle to NaN.
1059
1060             %This code was developed by SL and updated by DMMO
1061
1062             badSubj = this;
1063
1064             for i = 1:numel(badMuscles)
1065
1066                 badDataIdx=find(cellfun(@(x) ~isempty(x),regexp(badSubj.data.labels,['^' badMuscles{i} '[ ]?\d+$'])));
1067
1068                 if isempty(badDataIdx)
1069                     warning('Label not found. No muscle removed. Make sure that you normalize the data first')
1070                     return
1071                 end
1072
1073                 badSubj.data.Data(:,badDataIdx) = nan;
1074
1075                 disp(['Removing (Setting NaN) of ' badMuscles{i} ' from Subject: ' badSubj.subData.ID])
1076
1077             end
1078
1079         end
1080
1081     end
1082
1083
1084
1085
1086     methods(Static)
1087
1088          [figHandle,allData]=plotGroupedSubjectsTimeCourse(adaptDataList,label,removeBiasFlag,plotIndividualsFlag,condList,earlyNumber,lateNumber,exemptLast,legendNames)
1089
1090          [figHandle,allData]=plotGroupedSubjects(adaptDataList,label,removeBiasFlag,plotIndividualsFlag,condList,earlyNumber,lateNumber,exemptLast,legendNames) %Will deprecate, use plotGroupedSubjectsBars instead.
1091
1092          [figHandle,allData]=plotGroupedSubjectsBars(adaptDataList,label,removeBiasFlag,plotIndividualsFlag,condList,earlyNumber,lateNumber,exemptLast,legendNames,significanceThreshold,plotHandles,colors)
1093
1094          varargout=plotAvgTimeCourse(adaptDataList,params,conditions,binwidth,trialMarkerFlag,indivFlag,indivSubs,colorOrder,biofeedback,removeBiasFlag,groupNames,medianFlag,plotHandles,alignEnd,alignIni)
1095
1096          [figHandle]=scatterPlotLab(adapDataList,labels,conditionIdxs,figHandle,marker,binSize,trajectoryColor,removeBias,addID)
1097
1098          [figHandle]=Correlations(adapDataList, results,epochx,epochy,param1,groups,colorOrder,type)
1099
1100         function [fh,ph,allData]=plotGroupedTimeAndBars(adaptDataGroups,labels,conds,binwidth,trialMarkerFlag,indivFlag,indivSubs,colorOrder,biofeedback,removeBiasFlag,groupNames,medianFlag,plotHandles,numberOfStrides)
1101
1102             fh=figure;
1103
1104             M=length(labels);
1105             clear ph
1106             for i=1:M
1107                 ph(i,1)=subplot(M,3,[1:2]+3*(i-1));
1108                 ph(i,2)=subplot(M,3,[3]+3*(i-1));
1109             end
1110
1111             %Defaults:
1112             plotHandles=[]; %Not allowed
1113             if nargin<8 || isempty(colorOrder)
1114                 colorScheme
1115             colorOrder=color_palette;
1116             end
1117             plotIndividualsFlag=indivFlag;
1118             legendNames=[];
1119             significanceThreshold=.05;
1120             removeBiasFlag=0; %Disallowing removeBiasFlag
1121             significancePlotMatrix=[];
1122             alignEnd=abs(numberOfStrides(2));
1123             signifPlotMatrixConds=[];
1124             exemptFirst=1;
1125             exemptLast=5;
1126
1127             %Time courses:
1128             adaptData=cellfun(@(x) x.adaptData,adaptDataGroups,'UniformOutput',false);
1129             fh=adaptationData.plotAvgTimeCourse(adaptData,labels,conds,binwidth,trialMarkerFlag,indivFlag,indivSubs,colorOrder,biofeedback,removeBiasFlag,groupNames,medianFlag,ph(:,1),alignEnd);
1130
1131             %Add bars:
1132             [fh,allData]=groupAdaptationData.plotMultipleGroupsBars(adaptDataGroups,labels,removeBiasFlag,plotIndividualsFlag,conds,numberOfStrides,exemptFirst,exemptLast,groupNames,significanceThreshold,ph(:,2),colorOrder,significancePlotMatrix,medianFlag,signifPlotMatrixConds);
1133
1134             for i=1:M
1135                 subplot(ph(i,2));
1136                 grid on
1137                 aa=axis;
1138                 subplot(ph(i,1));
1139                 grid on
1140                 ab=axis;
1141                 axis([ab(1:2) aa(3:4)])
1142             end
1143         end
1144
1145         function[fh,ph,allData]=plotGroupedTimeAndEpochBars(adaptDataGroups,labels,eps,binwidth,trialMarkerFlag,indivFlag,indivSubs,colorOrder,biofeedback,groupNames,medianFlag,removeBaseEpochFlag,alignEnd,significanceThreshold,posthocGroupFlag,posthocEpochFlag,posthocGroupByEpochFlag,posthocEpochByGroupFlag);
1146            %  figure('units','normalized','outerposition',[0 0 1 1])
1147             fh=figure;
1148
1149
1150
1151             M=length(labels);
1152             clear ph
1153             for i=1:M
1154                 ph(i,1)=subplot(M,3,[1:2]+3*(i-1));
1155                 ph(i,2)=subplot(M,3,[3]+3*(i-1));
1156             end
1157
1158             %Defaults:
1159             if nargin<8 || isempty(colorOrder)
1160                 colorScheme
1161             colorOrder=color_palette;
1162             end
1163
1164             conds=unique(eps.Condition,'stable');
1165 %             numberOfStrides=eps.Stride_No;
1166 %             for i=1:length(numberOfStrides)
1167 %                 if ~eps.EarlyOrLate(i)
1168 %                     numberOfStrides(i)=-1*numberOfStrides(i);%last strides
1169 %                 end
1170 %             end
1171             plotIndividualsFlag=indivFlag;
1172            % significanceThreshold=[];%.05;
1173
1174             %alignEnd=abs(numberOfStrides(2));
1175
1176             %exemptFirst=1;
1177             %exemptLast=5;
1178
1179             set(ph,'ActivePositionProperty','outerposition')
1180             %Time courses:
1181             for i=1:length(adaptDataGroups)
1182                 adaptDataGroups{i}=adaptDataGroups{i}.removeBadStrides;
1183             if removeBaseEpochFlag==1
1184                    adaptDataGroups2{i}=adaptDataGroups{i}.removeBaselineEpoch(eps(1,:),[]);
1185             else
1186                  adaptDataGroups2{i}=adaptDataGroups{i};
1187             end
1188
1189             end
1190             adaptData=cellfun(@(x) x.adaptData,adaptDataGroups2,'UniformOutput',false);
1191            fh=adaptationData.plotAvgTimeCourse(adaptData,labels,conds,binwidth,trialMarkerFlag,indivFlag,indivSubs,colorOrder,biofeedback,0,groupNames,medianFlag,ph(:,1),alignEnd);
1192             for pl=1:size(ph,1)
1193                 hold(ph(pl,1))
1194                 title(ph(pl,1),ph(pl,1).YLabel.String);
1195                 ylabel(ph(pl,1),{''})
1196             end
1197
1198             %set(ph(:,2),'Clipping','off')
1199             %Add bars:
1200             [fh,allData]=groupAdaptationData.plotMultipleEpochBars(adaptDataGroups,labels,eps,plotIndividualsFlag,groupNames,ph(:,2),colorOrder,medianFlag,significanceThreshold,posthocGroupFlag,posthocEpochFlag,posthocGroupByEpochFlag,posthocEpochByGroupFlag,removeBaseEpochFlag);
1201             for i=1:M
1202                 subplot(ph(i,2));
1203                 grid on
1204                 aa=axis;
1205                 subplot(ph(i,1));
1206                 grid on
1207                 ab=axis;
1208                 axis([ab(1:2) aa(3:4)])
1209             end
1210             set(ph,'FontSize',16,'TitleFontSizeMultiplier',1.1,'XGrid','off','YGrid','off');
1211             set(ph(1:end-1,:),'XTickLabel',{''})
1212             set(fh,'Color',[1 1 1]);
1213             %ph(1,1).Legend=ph(end,1).Legend;%ph(end,1).Legend
1214
1215         end
1216
1217         function groupData=createGroupAdaptData(adaptDataList, parametersToKeep, rmvDatlog)
1218             %Check that it is a single cell array of chars (subIDs):
1219             %Ex: GroupName=adaptationData.createGroupAdaptData({'X1params','x2params','X3params'})
1220             %Input
1221             % - adaptDataList: cell array of strings that represent file paths to
1222             %       load the adaptData objects to create the group
1223             %       adaptation. The string file name should be either SubID
1224             %       or SubIDparams, e.g., {'AUC01V01param.mat','AUC02V01param.mat'}
1225             % - parametersToKeep: OPTIONAL. cell array of strings with
1226             %       parameter labels to keep in the group data. This is
1227             %       added to make the group object more light weighted and
1228             %       avoid out of memory error. Not provided or leave empty
1229             %       [] will create the group object with the full
1230             %       parameters.
1231             % - rmvDatlog: OPTIONAL. boolean indicating if datalog should
1232             %       be removed. this helps to save storage space (default true)
1233             %Load and construct object:
1234
1235             if nargin < 3 || isempty(rmvDatlog)
1236                 rmvDatlog = true;
1237             end
1238             for i=1:length(adaptDataList)
1239                 try
1240                     a=load(adaptDataList{i});
1241                 catch ME
1242                     warning('Could not find filename as provided. Trying alternative spellings.')
1243                     try
1244                         a=load([adaptDataList{i} 'Params']);
1245                     catch
1246                         try
1247                             a=load([adaptDataList{i} 'params']);
1248                         catch
1249                             warning('Alternative spellings failed too.')
1250                             throw(ME)
1251                         end
1252                     end
1253                 end
1254                 if rmvDatlog && isprop(a.adaptData.metaData,'datlog')
1255                     a.adaptData.metaData.datlog = {};
1256                 end
1257                 data{i}=a.('adaptData');
1258                 if nargin >= 2 && ~isempty(parametersToKeep) %valid parameters given, now reduce it to only keep the parameters given.
1259                     data{i}=data{i}.reduce(parametersToKeep);
1260                 end
1261                 ID{i}=a.('adaptData').subData.ID;
1262                 clear a %maybe helps with memory
1263             end
1264             groupData=groupAdaptationData(ID,data);
1265         end
1266
1267         function [veryEarlyPoints,earlyPoints,latePoints,pEarly,pLate,pChange,pSwitch]=getGroupedData(adaptDataList,label,conds,removeBiasFlag,earlyNumber,lateNumber,exemptLast);
1268
1269             if ~(isa(label,'char') || (isa(label,'cell') && length(label)==1 && (isa(label{1},'char'))))
1270                 error('adaptationData:getGroupedData','Only one parameter can be retrieved at a time.'); %This is NOT true (?). Fix.
1271             end
1272
1273             %Create a groupAdaptationData object and use it to get the
1274             %requested data in matrix form:
1275             groupData=adaptationData.createGroupAdaptData(adaptDataList);
1276             [data]=groupData.getGroupedData(label,conds,removeBiasFlag,[3,earlyNumber,-lateNumber],0,exemptLast);
1277             earlyPoints=data{2};
1278             veryEarlyPoints=data{1};
1279             latePoints=data{3};
1280
1281             %Compute some stats (this may only work properly if length(label)==1)
1282             if length(label)>1
1283                 pEarly=[];
1284                 pLate=[];
1285                 pChange=[];
1286                 pSwitch=[];
1287             else
1288                 aux1=squeeze(nanmean(earlyPoints,2)); %Averaging across strides
1289                 aux2=squeeze(nanmean(latePoints,2));
1290                 pSwitch=[];
1291                 for i=1:size(aux1,1) %For all conditions requested
1292                     for j=1:size(aux1,1)
1293                         if i~=j
1294                             [~,pEarly(i,j)] =ttest(aux1(i,:),aux1(j,:)); %Testing early points across all conds
1295                             [~,pLate(i,j)] =ttest(aux2(i,:),aux2(j,:)); %Testing late points across all conds
1296                         else
1297                             pEarly(i,j)=NaN;
1298                             pLate(i,j)=NaN;
1299                         end
1300                     end
1301                     [~,pChange(i)]=ttest(aux1(i,:),aux2(i,:)); %Testing changes within each condition
1302                     if i>1
1303                         [~,pSwitch(i-1)]=ttest(aux2(i-1,:),aux1(i,:)); %Testing changes from end of one condition to start of the next
1304                     end
1305                 end
1306             end
1307         end
1308
1309         function this=loadobj(this)
1310             if ~isempty(this.subData.dateOfBirth)
1311                 warning('adaptData:subjectDOB',['Subject data contains DOB information for subject ' this.subData.ID '. Data will be hidden. You should overwrite (save) your file with this new version to prevent this warning in the future. Please check that all other information is intact before overwriting.'])
1312                 %Determine age (in months):
1313                 age=round(this.metaData.date.timeSince(this.subData.dateOfBirth));
1314                 %Scrub DOB from subject meta data, save age at experiment time (in years):
1315                 this.subData=subjectData([],this.subData.sex,this.subData.dominantLeg,this.subData.dominantArm,this.subData.height,this.subData.weight,age/12,this.subData.ID);
1316             end
1317         end
1318
1319 %         function figHandle=groupedScatterPlot(adaptDataList,labels,conditionIdxs,binSize,figHandle,trajColors,removeBias)
1320 %
1321 %             if isa(adaptDataList,'cell')
1322 %                 if ~isa(adaptDataList{1},'cell')
1323 %                     adaptDataList={adaptDataList};
1324 %                 end
1325 %             elseif isa(adaptDataList,'char')
1326 %                 adaptDataList={{adaptDataList}};
1327 %             end
1328 %             Ngroups=length(adaptDataList);
1329 %
1330 %             if nargin<7 || isempty(removeBias)
1331 %                 removeBias=0;
1332 %             end
1333 %             if nargin<5 || isempty(figHandle)
1334 %                 figHandle=figure;
1335 %             else
1336 %                 figure(figHandle);
1337 %                 hold on
1338 %             end
1339 %             markerList={'x','o','.','+','*','s','v','^','d'};
1340 %             if nargin<3 || isempty(conditionIdxs)
1341 %                 conditionIdxs=[];
1342 %             end
1343 %             if nargin<4 || isempty(binSize)
1344 %                 binSize=[];
1345 %             end
1346 %             for g=1:Ngroups
1347 %                 for i=1:length(adaptDataList{g})
1348 %                     r=(i-1)/(length(adaptDataList{g})-1);
1349 %                     if nargin<6 || isempty(trajColors)
1350 %                         trajColor=[1,0,0] + r*[-1,0,1];
1351 %                     elseif iscell(trajColors)
1352 %                         trajColor=trajColors{i};
1353 %                     elseif size(trajColors,2)==3
1354 %                         trajColor=trajColors(mod(i,size(trajColors,1))+1,:);
1355 %                     else
1356 %                         warning('Could not interpret trajecColors input')
1357 %                         trajColor='k';
1358 %                     end
1359 %                     this=adaptDataList{g}{i};
1360 %                     fieldList=fields(this);
1361 %                     a=this.(fieldList{1});
1362 %                     if iscell(conditionIdxs) %This gives the possibility to pass condition names instead of the indexes for each subject, which might be different
1363 %                         conditionIdxs1=getConditionIdxsFromName(a,conditionIdxs);
1364 %                     else
1365 %                         conditionIdxs1=conditionIdxs;
1366 %                     end
1367 %                     figHandle=scatterPlotLab(adaptDataList,labels,conditionIdxs,figHandle,markerList{mod(i,length(markerList))+1},binSize,trajColor,removeBias,1);
1368 %                        figHandle=scatterPlotLab(adaptDataList,labels,conditionIdxs,figHandle,markerList,binSize,[],removeBias,1);
1369 %                 end
1370 %             end
1371 %
1372 %         end
1373
1374         [figHandle,allData]=plotGroupedSubjectsBarsv2(adaptDataList,label,removeBiasFlag,plotIndividualsFlag,condList,numberOfStrides,exemptFirst,exemptLast,legendNames,significanceThreshold,plotHandles,colors,medianFlag)
1375     end %static methods
1376
1377 end