Description of computeTorques
Home > labTools > classes > dataStructs > @labData > computeTorques.m
computeTorques
PURPOSE
computeTorques Computes joint torques from kinematics and kinetics
SYNOPSIS
function [momentData, COP, COM] = computeTorques(this,subjectWeight)
DESCRIPTION
computeTorques  Computes joint torques from kinematics and kinetics
   [momentData, COP, COM] = computeTorques(this) computes joint torques
   using estimated subject weight from GRF data
   [momentData, COP, COM] = computeTorques(this, subjectWeight) computes
   joint torques using specified subject weight
   Inputs:
       this - labData object
       subjectWeight - subject body weight in kg (optional, estimated from
                       GRF if not provided)
   Outputs:
       momentData - labTimeSeries containing joint moment data
       COP - center of pressure data
       COM - center of mass data
   See also: TorqueCalculator, estimateSubjectBodyWeight
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
estimateSubjectBodyWeight estimateSubjectBodyWeight Estimates subject weight from GRF data
TorqueCalculator TORQUECALCULATOR Calculate torque at each leg joint using inverse dynamics
This function is called by:
labData
SOURCE CODE
function [momentData, COP, COM] = computeTorques(this, ...
    subjectWeight)
%computeTorques  Computes joint torques from kinematics and kinetics
%
%   [momentData, COP, COM] = computeTorques(this) computes joint torques
%   using estimated subject weight from GRF data
%
%   [momentData, COP, COM] = computeTorques(this, subjectWeight) computes
%   joint torques using specified subject weight
%
%   Inputs:
%       this - labData object
%       subjectWeight - subject body weight in kg (optional, estimated from
%                       GRF if not provided)
%
%   Outputs:
%       momentData - labTimeSeries containing joint moment data
%       COP - center of pressure data
%       COM - center of mass data
%
%   See also: TorqueCalculator, estimateSubjectBodyWeight
if nargin < 2 || isempty(subjectWeight)
    warning(['Subject weight not given, estimating from GRFs. This ' ...
        'will fail miserably if z-axis force is not representative of ' ...
        'weight.']);
    subjectWeight = estimateSubjectBodyWeight(this);
end
[momentData, COP, COM] = TorqueCalculator(this, subjectWeight);
end