Description of getEvents
Home > labTools > classes > dataStructs > @labData > getEvents.m
getEvents
PURPOSE
GETEVENTS Extract gait events from a raw trial, selecting the appropriate
SYNOPSIS
function events = getEvents(trialData, angleData, perceptualFlag)
DESCRIPTION
GETEVENTS Extract gait events from a raw trial, selecting the appropriate
detection strategy based on trial type and available data.
   For OG and NIM trials, events are derived from limb angles
 (GETEVENTSFROMANGLES). For treadmill (TM) trials with GRF data, events
 are derived from vertical forces (GETEVENTSFROMFORCES); kinematic events
 are also computed and stored as diagnostics. For TM trials without GRF
 data, events are derived from toe and heel markers
 (GETEVENTSFROMTOENANDHEEL). In all cases, the output labTimeSeries
 contains LHS, RHS, LTO, RTO plus diagnostic force and kinematic copies.
 Inputs:
   trialData      - rawTrialData, contains markerData, GRFData, metaData
   angleData      - labTimeSeries with 'RLimb' and 'LLimb' labels, or []
   perceptualFlag - scalar logical/numeric (1 = include perceptual cue
                   columns in the output)
 Outputs:
   events - labTimeSeries, sparse logical event matrix with labels:
            LHS, RHS, LTO, RTO, forceLHS/RHS/LTO/RTO,
            kinLHS/RHS/LTO/RTO, [percStartCue, percEndCue, percEndRamp]
 Toolbox Dependencies: None
 See also GETEVENTSFROMFORCES, GETEVENTSFROMANGLES,
          GETEVENTSFROMTOENANDHEEL, LABTIMESERIES.
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
labTimeSeries
orientationInfo
getEventsFromAngles GETEVENTSFROMANGLES Detect gait events from limb angle data.
getEventsFromForces GETEVENTSFROMFORCES Detect gait events from vertical ground reaction forces.
getEventsFromToeAndHeel GETEVENTSFROMTOENANDHEEL Detect gait events from toe and heel marker data.
getSimpleFileName
This function is called by:
process process Processes raw trial data to compute angles, gait events,
recomputeEvents recomputeEvents Re-calculates gait events from angle data
recomputeEvents recomputeEvents Re-computes gait events and adaptation parameters
SOURCE CODE
function events = getEvents(trialData, angleData, perceptualFlag)
%GETEVENTS Extract gait events from a raw trial, selecting the appropriate
%detection strategy based on trial type and available data.
%
%   For OG and NIM trials, events are derived from limb angles
% (GETEVENTSFROMANGLES). For treadmill (TM) trials with GRF data, events
% are derived from vertical forces (GETEVENTSFROMFORCES); kinematic events
% are also computed and stored as diagnostics. For TM trials without GRF
% data, events are derived from toe and heel markers
% (GETEVENTSFROMTOENANDHEEL). In all cases, the output labTimeSeries
% contains LHS, RHS, LTO, RTO plus diagnostic force and kinematic copies.
%
% Inputs:
%   trialData      - rawTrialData, contains markerData, GRFData, metaData
%   angleData      - labTimeSeries with 'RLimb' and 'LLimb' labels, or []
%   perceptualFlag - scalar logical/numeric (1 = include perceptual cue
%                   columns in the output)
%
% Outputs:
%   events - labTimeSeries, sparse logical event matrix with labels:
%            LHS, RHS, LTO, RTO, forceLHS/RHS/LTO/RTO,
%            kinLHS/RHS/LTO/RTO, [percStartCue, percEndCue, percEndRamp]
%
% Toolbox Dependencies: None
%
% See also GETEVENTSFROMFORCES, GETEVENTSFROMANGLES,
%          GETEVENTSFROMTOENANDHEEL, LABTIMESERIES.
arguments
    trialData
    angleData
    perceptualFlag (1,1) {mustBeNumeric}
end
trialFileName = getSimpleFileName(trialData.metaData.rawDataFilename);
if isempty(trialData.markerData.orientation)
    warning('Assuming default orientation of axes for marker data.');
    orientation = orientationInfo([0, 0, 0], 'x', 'y', 'z', 1, 1, 1);
else
    orientation = trialData.markerData.orientation;
end
if ~isempty(angleData)
    [kinLHS, kinRHS, kinLTO, kinRTO] = ...
        getEventsFromAngles(trialData, angleData, orientation);
else
    % length 10 is arbitrary; prevents length-mismatch errors downstream
    [kinLHS, kinRHS, kinLTO, kinRTO] = deal(false(10, 1));
end
if strcmpi(trialData.metaData.type, 'OG') ...
        || strcmpi(trialData.metaData.type, 'NIM') % overground trial: use limb angles
    [LHSevent, LHSeventKin] = deal(kinLHS); % make a redundant copy; kinematic events are default
    [RHSevent, RHSeventKin] = deal(kinRHS);
    [LTOevent, LTOeventKin] = deal(kinLTO);
    [RTOevent, RTOeventKin] = deal(kinRTO);
    LHSeventForce = false(length(LHSevent), 1); % no force events; fill with logical 0s
    RHSeventForce = false(length(RHSevent), 1);
    LTOeventForce = false(length(LTOevent), 1);
    RTOeventForce = false(length(RTOevent), 1);
    t0 = trialData.markerData.Time(1);
    Ts = trialData.markerData.sampPeriod;
    %     t0=trialData.GRFData.Time(1);
    %     Ts=trialData.GRFData.sampPeriod;
else % treadmill trial
    if isempty(trialData.GRFData) || isempty(trialData.GRFData.Data) % no force data: use marker kinematics
        disp(['No ground reaction forces data in ' trialFileName ...
            '. Using marker data to compute events.'])
        %         LtoePos=trialData.getMarkerData({['LTOE' orientation.foreaftAxis],['LTOE' orientation.updownAxis],['LTOE' orientation.sideAxis]});
        %         LtoePos=[orientation.foreaftSign* LtoePos(:,1),orientation.updownSign*LtoePos(:,2),orientation.sideSign*LtoePos(:,3)];
        %         RtoePos=trialData.getMarkerData({['RTOE' orientation.foreaftAxis],['RTOE' orientation.updownAxis],['RTOE' orientation.sideAxis]});
        %         RtoePos=[orientation.foreaftSign* RtoePos(:,1),orientation.sideSign*RtoePos(:,2),orientation.updownSign*RtoePos(:,3)];
        LtoePos = trialData.markerData.getDataAsVector({'LTOE'});
        RtoePos = trialData.markerData.getDataAsVector({'RTOE'}); % was incorrectly 'LTOE' before
        %         LanklePos=trialData.getMarkerData({['LANK' orientation.foreaftAxis],['LANK' orientation.updownAxis],['LANK' orientation.sideAxis]});
        %         LanklePos=[orientation.foreaftSign* LanklePos(:,1),orientation.sideSign*LanklePos(:,2),orientation.updownSign*LanklePos(:,3)];
        %         RanklePos=trialData.getMarkerData({['RANK' orientation.foreaftAxis],['RANK' orientation.updownAxis],['RANK' orientation.sideAxis]});
        %         RanklePos=[orientation.foreaftSign* RanklePos(:,1),orientation.sideSign*RanklePos(:,2),orientation.updownSign*RanklePos(:,3)];
        LanklePos = trialData.markerData.getDataAsVector({'LANK'});
        RanklePos = trialData.markerData.getDataAsVector({'RANK'});
        if trialData.markerData.isaLabel('LHEEx')
            %             LheelPos=trialData.getMarkerData({['LHEE' orientation.foreaftAxis],['LHEE' orientation.updownAxis],['LHEE' orientation.sideAxis]});
            %             LheelPos=[orientation.foreaftSign* LheelPos(:,1),orientation.sideSign*LheelPos(:,2),orientation.updownSign*LheelPos(:,3)];
            %             RheelPos=trialData.getMarkerData({['RHEE' orientation.foreaftAxis],['RHEE' orientation.updownAxis],['RHEE' orientation.sideAxis]});
            %             RheelPos=[orientation.foreaftSign* RheelPos(:,1),orientation.sideSign*RheelPos(:,2),orientation.updownSign*RheelPos(:,3)];
            LheelPos = trialData.markerData.getDataAsVector({'LHEE'});
            RheelPos = trialData.markerData.getDataAsVector({'RHEE'});
        else
            disp(['No heel markers in ' trialFileName ...
                '. Using ankle markers instead to compute events.'])
            LheelPos = LanklePos;
            RheelPos = RanklePos;
        end
        fs_kin = trialData.markerData.sampFreq;
        [LHSevent, RHSevent, LTOevent, RTOevent] = ...
            getEventsFromToeAndHeel(LtoePos, LheelPos, RtoePos, RheelPos, fs_kin);
        LHSeventForce = false(length(LHSevent), 1); % no force events; fill with logical 0s
        RHSeventForce = false(length(RHSevent), 1);
        LTOeventForce = false(length(LTOevent), 1);
        RTOeventForce = false(length(RTOevent), 1);
        LHSeventKin = kinLHS;
        RHSeventKin = kinRHS;
        LTOeventKin = kinLTO;
        RTOeventKin = kinRTO;
        t0 = trialData.markerData.Time(1);
        Ts = trialData.markerData.sampPeriod;
    else % TM trial with GRF data: use forces as primary events
        upAxis = trialData.GRFData.orientation.updownAxis;
        upSign = trialData.GRFData.orientation.updownSign;
        FzL    = upSign * trialData.GRFData.getDataAsVector(['LF', upAxis]);
        FzR    = upSign * trialData.GRFData.getDataAsVector(['RF', upAxis]);
        % %Sanity check: correct non-zeroed force-plates: % Now we will be
        % doing this inside the even detection
        % if mode(FzL)~=0
        %     disp(['Warning: Left z-axis forces in ' trialFileName ' have non-zero mode. Subtracting mode from force data before event detection'])
        %     FzL=FzL-mode(FzL);
        % end
        % if mode(FzR)~=0
        %     disp(['Warning: Right z-axis forces in ' trialFileName ' have non-zero mode. Subtracting mode from force data before event detection'])
        %     FzR=FzR-mode(FzR);
        % end
        [LHSevent, RHSevent, LTOevent, RTOevent] = ...
            getEventsFromForces(FzL, FzR, trialData.GRFData.sampFreq);
        LHSeventForce = LHSevent; % make a redundant copy to label as force events
        RHSeventForce = RHSevent;
        LTOeventForce = LTOevent;
        RTOeventForce = RTOevent;
        t0 = trialData.GRFData.Time(1);
        Ts = trialData.GRFData.sampPeriod;
        [LHSeventKin, RHSeventKin, LTOeventKin, RTOeventKin] = ...
            deal(false(trialData.GRFData.Length, 1));
        % TODO: use a method to re-sample kinematic events to be consistent
        % with forces.
        kinToGrfRatio = trialData.GRFData.sampFreq ...
            / trialData.markerData.sampFreq; % GRF samples per kinematic sample
        LHSeventKin(round((find(kinLHS) - 1) * kinToGrfRatio + 1)) = true;
        RHSeventKin(round((find(kinRHS) - 1) * kinToGrfRatio + 1)) = true;
        LTOeventKin(round((find(kinLTO) - 1) * kinToGrfRatio + 1)) = true;
        RTOeventKin(round((find(kinRTO) - 1) * kinToGrfRatio + 1)) = true;
        %%
        if perceptualFlag == 1 % If your code is breaking, I am iterating so just comment this out
            % timeLHS = find(LHSeventForce==1)./trialData.GRFData.sampFreq; timeRHS = find(RHSeventForce==1)./trialData.GRFData.sampFreq;
            % timeLTO = find(LTOeventForce==1)./trialData.GRFData.sampFreq;
            timeRTO = find(RTOeventForce == 1) ./ trialData.GRFData.sampFreq; % time of each RTO event, used to align with datalog
            % [LHSstartCue, LHSstopCue, RHSstartCue, RHSstopCue] = getPerceptualEventsFromCues(trialData.metaData.datlog, infoLHSevent, infoRHSevent);
            % actual frame number for the stride whose time is closest to
            % the perceptual trial start and end cues
            percStartCue = zeros(1, length(RTOeventForce));
            percEndCue   = zeros(1, length(RTOeventForce));
            percEndRamp  = zeros(1, length(RTOeventForce));
            % grab auditory cue times from the datlog; offset by
            % synchronization with Nexus
            if sum(contains(fields(trialData.metaData.datlog), ...
                    'dataLogTimeOffsetBest')) > 0
                startCue = trialData.metaData.datlog.audioCues.start ...
                    + trialData.metaData.datlog.dataLogTimeOffsetBest;
                endCue = trialData.metaData.datlog.audioCues.stop ...
                    + trialData.metaData.datlog.dataLogTimeOffsetBest;
                if ~isempty(startCue)
                    % find last RTO before each cue; the controller
                    % increments stride count starting from RTO
                    idxStrideScue = arrayfun( ...
                        @(x) find((x - timeRTO) >= 0, 1, 'last'), startCue);
                    ... start cue should happen after updating both legs, so the RTO after the left leg speed was updated in the task
                        idxStrideEcue = arrayfun( ...
                        @(x) find((x - timeRTO) >= 0, 1, 'last'), endCue);
                    framesRTO = find(RTOeventForce == 1);
                    idxFrameStart = framesRTO(idxStrideScue);
                    percStartCue(idxFrameStart) = true;
                    idxFrameEnd = framesRTO(idxStrideEcue);
                    percEndCue(idxFrameEnd)  = true;
                    idxFrameEndRamp = framesRTO(idxStrideEcue);
                    percEndRamp(idxFrameEndRamp) = true;
                    % Currently for Weber Perception I have a ramp down of 3
                    % strides which might change in the future. TODO: make it
                    % more robust such that this is only computed for Weber
                    % Study
                    % idxFrameEndRamp = framesRTO(idxStrideEcue+3);
                    % percEndRamp(idxFrameEndRamp) = true;
                end
            else % proceed with caution; relative times in MATLAB are not synchronized with Nexus
                warning("Datalogs can't be synchronized with Nexus data");
            end
        end
    end
end
%% Assemble output event time series
eventLabels = {'LHS', 'RHS', 'LTO', 'RTO', ...
    'forceLHS', 'forceRHS', 'forceLTO', 'forceRTO', ...
    'kinLHS', 'kinRHS', 'kinLTO', 'kinRTO'};
eventData   = [LHSevent, RHSevent, LTOevent, RTOevent, ...
    LHSeventForce, RHSeventForce, LTOeventForce, RTOeventForce, ...
    LHSeventKin, RHSeventKin, LTOeventKin, RTOeventKin];
if perceptualFlag == 1
    eventLabels = [eventLabels, ...
        {'percStartCue', 'percEndCue', 'percEndRamp'}];
    eventData   = [eventData, ...
        percStartCue', percEndCue', percEndRamp'];
end
events = labTimeSeries(sparse(eventData), t0, Ts, eventLabels);
end