Description of process
Home > labTools > classes > dataStructs > @labData > process.m
process
PURPOSE
process Processes raw trial data to compute angles, gait events,
SYNOPSIS
function processedData = process(this, subData, eventClass)
DESCRIPTION
 process  Processes raw trial data to compute angles, gait events,
   and adaptation parameters.
   processedData = process(this, subData) processes the raw trial
   data and returns a processedTrialData object with computed limb
   angles, gait events, filtered EMG, COP, COM, and joint moments.
   processedData = process(this, subData, eventClass) uses the
   specified gait event detection method.
   Inputs:
     this       - labData object
     subData    - subjectData object containing subject weight and
                  other anthropometric information
     eventClass - (optional) String specifying the gait event
                  detection method. Defaults to '' if omitted:
                    ''      - default (forces for TM trials,
                              kinematics otherwise)
                    'kin'   - strictly from kinematics
                    'force' - strictly from forces
   Outputs:
     processedData - processedTrialData object containing all
                     processed data
   Note: This function must be idempotent, i.e.,
           labData.process().process() == labData.process()
         Otherwise re-processing data may lead to double or
         triple filtering.
   Toolbox Dependencies:
     None
   See also: processedTrialData, calcParameters, experimentData/process
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
subjectData
calcLimbAngles calcLimbAngles Calculates limb and joint angles from marker data.
getBeltSpeedsFromFootMarkers
getEvents GETEVENTS Extract gait events from a raw trial, selecting the appropriate
processEMG processEMG Extracts processed and filtered EMG amplitude envelopes
processedTrialData
calcParameters CALCPARAMETERS Compute stride-by-stride parameters for analysis.
This function is called by:
experimentData
labData
SOURCE CODE
function processedData = process(this, subData, eventClass)
% process  Processes raw trial data to compute angles, gait events,
%   and adaptation parameters.
%
%   processedData = process(this, subData) processes the raw trial
%   data and returns a processedTrialData object with computed limb
%   angles, gait events, filtered EMG, COP, COM, and joint moments.
%
%   processedData = process(this, subData, eventClass) uses the
%   specified gait event detection method.
%
%   Inputs:
%     this       - labData object
%     subData    - subjectData object containing subject weight and
%                  other anthropometric information
%     eventClass - (optional) String specifying the gait event
%                  detection method. Defaults to '' if omitted:
%                    ''      - default (forces for TM trials,
%                              kinematics otherwise)
%                    'kin'   - strictly from kinematics
%                    'force' - strictly from forces
%
%   Outputs:
%     processedData - processedTrialData object containing all
%                     processed data
%
%   Note: This function must be idempotent, i.e.,
%           labData.process().process() == labData.process()
%         Otherwise re-processing data may lead to double or
%         triple filtering.
%
%   Toolbox Dependencies:
%     None
%
%   See also: processedTrialData, calcParameters, experimentData/process
arguments
    this
    subData    (1,1) subjectData
    eventClass (1,:) char        = ''
end
% 1) Extract amplitude from EMG data if present
spikeRemovalFlag = false;
[procEMGData, filteredEMGData] = processEMG(this, spikeRemovalFlag);
% 2) Interpolate marker data if there is missing data
%    (make into function once we have a method to do this)
if ~isempty(this.markerData)
    % function goes here: check marker data health
end
% 3) Calculate limb angles
angleData = calcLimbAngles(this);
% 4) Calculate gait events from kinematics or forces if available;
%    last argument is the perceptual task flag
gaitEvents = getEvents(this, angleData,  this.metaData.perceptualTasks);
% 5) If 'beltSpeedReadData' is empty, try to generate it from
%    foot markers, if existent
if isempty(this.beltSpeedReadData)
    this.beltSpeedReadData = getBeltSpeedsFromFootMarkers(this,gaitEvents);
end
% 6) Compute COP, COM, and joint torque data; COP from
%    computeTorques is discarded in favor of computeCOPAlt below
[jointMomentsData, ~, COMData] = this.computeTorques(subData.weight);
% Replacing COPData with alternative computation
COPData = this.computeCOPAlt();
% COMData = this.CarlysCOMData(); % CJS: you should do this!
% 7) Generate processedTrialData object
processedData = processedTrialData(this.metaData, this.markerData, ...
    filteredEMGData, this.GRFData, this.beltSpeedSetData, ...
    this.beltSpeedReadData, this.accData, this.EEGData, ...
    this.footSwitchData, gaitEvents, procEMGData, angleData, COPData, ...
    COMData, jointMomentsData, this.HreflexPin);
% 8) Calculate adaptation parameters (to be recalculated later)
processedData.adaptParams = ...
    calcParameters(processedData, subData, eventClass);
end