Description of PlotParamsGUI
Home > labTools > gui > eventReview > PlotParamsGUI.m
PlotParamsGUI
PURPOSE
PLOTPARAMSGUI GUI for configuring and launching adaptation parameter plots.
SYNOPSIS
function varargout = PlotParamsGUI(varargin)
DESCRIPTION
PLOTPARAMSGUI GUI for configuring and launching adaptation parameter plots.
   Loads a studyData object and provides controls to select groups,
 subjects, parameters, conditions, and plot type (time course, early/late
 bars, scatter, epoch bars, correlation), then calls the corresponding
 adaptationData plotting function.
 Toolbox Dependencies:
   None
 See also: adaptationData, groupAdaptationData, studyData
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
cat cat Concatenates alignedTimeSeries
cat cat Concatenates (override)
cat cat Concatenates two parameterSeries
contrastColor CONTRASTCOLOR
barGroups Make a bar plot to compare groups for a given epoch and parameter
getResults define number of points to use for calculating values
disableFields DISABLEFIELDS Disable a list of named GUI controls in a handles struct.
enableFields ENABLEFIELDS Enable a list of named GUI controls in a handles struct.
This function is called by:
SUBFUNCTIONS
function PlotParamsGUI_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = PlotParamsGUI_OutputFcn(hObject, eventdata, handles)
function plotTypePanel_SelectionChangeFcn(hObject, eventdata, handles)
function groupList_Callback(hObject, eventdata, handles)
function subjectList_Callback(hObject, eventdata, handles)
function parameterList_Callback(hObject, eventdata, handles)
function conditionList_Callback(hObject, eventdata, handles)
function binEdit_Callback(hObject, eventdata, handles)
function indivSubs_Callback(hObject, eventdata, handles)
function samePlotCheck_Callback(hObject, eventdata, handles)
function conditionSubList_Callback(hObject, eventdata, handles)
function regExpBox_Callback(hObject, eventdata, handles)
function maxPerturbCheck_Callback(hObject, eventdata, handles)
function earlyNumPts_Callback(hObject, eventdata, handles)
function lateNumPts_Callback(hObject, eventdata, handles)
function exptLastNumPts_Callback(hObject, eventdata, handles)
function removeBiasCheck_Callback(hObject, eventdata, handles)
function biofeedback_Callback(hObject, eventdata, handles)
function printCodeCheck_Callback(hObject, eventdata, handles)
function AlignEnd2_Callback(hObject, eventdata, handles)
function InitiAlig_Callback(hObject, eventdata, handles)
function saveTool_ClickedCallback(hObject, eventdata, handles)
function openTool_ClickedCallback(hObject, eventdata, handles)
function plotButton_Callback(hObject, eventdata, handles)
function colorMenu_Callback(hObject, eventdata, handles)
function saveColorsButton_Callback(hObject, eventdata, handles)
function color1_Callback(hObject, eventdata, handles)
function color2_Callback(hObject, eventdata, handles)
function color3_Callback(hObject, eventdata, handles)
function color4_Callback(hObject, eventdata, handles)
function color5_Callback(hObject, eventdata, handles)
function color6_Callback(hObject, eventdata, handles)
function color7_Callback(hObject, eventdata, handles)
function color8_Callback(hObject, eventdata, handles)
function color9_Callback(hObject, eventdata, handles)
function color10_Callback(hObject, eventdata, handles)
function color11_Callback(hObject, eventdata, handles)
function color12_Callback(hObject, eventdata, handles)
function color13_Callback(hObject, eventdata, handles)
function color14_Callback(hObject, eventdata, handles)
function color15_Callback(hObject, eventdata, handles)
function color16_Callback(hObject, eventdata, handles)
function color17_Callback(hObject, eventdata, handles)
function handles = colorButtonCallback(hObject, handles)
function conditionList_CreateFcn(hObject, eventdata, handles)
function parameterList_CreateFcn(hObject, eventdata, handles)
function groupList_CreateFcn(hObject, eventdata, handles)
function binEdit_CreateFcn(hObject, eventdata, handles)
function subjectList_CreateFcn(hObject, eventdata, handles)
function conditionSubList_CreateFcn(hObject, eventdata, handles)
function regExpBox_CreateFcn(hObject, eventdata, handles)
function earlyNumPts_CreateFcn(hObject, eventdata, handles)
function lateNumPts_CreateFcn(hObject, eventdata, handles)
function exptLastNumPts_CreateFcn(hObject, eventdata, handles)
function colorMenu_CreateFcn(hObject, eventdata, handles)
function regExpBox_ButtonDownFcn(hObject, eventdata, handles)
function AlignEnd2_CreateFcn(hObject, eventdata, handles)
function InitiAlig_CreateFcn(hObject, eventdata, handles)
SOURCE CODE
function varargout = PlotParamsGUI(varargin)
%PLOTPARAMSGUI GUI for configuring and launching adaptation parameter plots.
%
%   Loads a studyData object and provides controls to select groups,
% subjects, parameters, conditions, and plot type (time course, early/late
% bars, scatter, epoch bars, correlation), then calls the corresponding
% adaptationData plotting function.
%
% Toolbox Dependencies:
%   None
%
% See also: adaptationData, groupAdaptationData, studyData
% Last Modified by GUIDE v2.5 04-May-2016 12:48:39
% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
    'gui_Singleton',  gui_Singleton, ...
    'gui_OpeningFcn', @PlotParamsGUI_OpeningFcn, ...
    'gui_OutputFcn',  @PlotParamsGUI_OutputFcn, ...
    'gui_LayoutFcn',  [] , ...
    'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end
if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT
end
%% --- Executes just before PlotParamsGUI is made visible.
function PlotParamsGUI_OpeningFcn(hObject, eventdata, handles, varargin)
handles.output = hObject;
% Position GUI window at the bottom center of the screen
scrsz  = get(0, 'ScreenSize');
set(gcf(), 'Units', 'pixels');
guiPos = get(gcf(), 'Position');   % left, bottom, width, height
width  = min([guiPos(3) scrsz(3)]);
height = min([guiPos(4) scrsz(4)]);
set(hObject, 'Position', [(scrsz(3) - width) / 2, 45, width, height]);
%set color strings
for ii = 1:17
    clr = get(handles.(['color' num2str(ii)]), 'BackgroundColor');
    set(handles.(['color' num2str(ii)]), 'ForegroundColor', contrastColor(clr));
    set(handles.(['color' num2str(ii)]), 'String', ['[' num2str(clr .* 255) ']']);
end
%initialize drop down list with different color orders
path = which('PlotParamsGUI');
path = strrep(path, 'PlotParamsGUI.m', 'Plotting Colors');
W    = what(path);
colorOrders = cellstr(W.mat);
for ii = 1:length(colorOrders)
    fileExt        = find(colorOrders{ii} == '.');
    colorOrders{ii} = colorOrders{ii}(1:fileExt - 1);
end
set(handles.colorMenu, 'String', [' '; colorOrders]);
% Update handles structure
guidata(hObject, handles);
% UIWAIT makes PlotParamsGUI wait for user response (see UIRESUME)
% uiwait(handles.figure1);
end
function varargout = PlotParamsGUI_OutputFcn(hObject, eventdata, handles)
%Outputs from this function are returned to the command line.
% Get default command line output from handles structure
varargout{1} = handles.output;
end
%% --------------------------Selecting Plot Type:----------------------------------
% --- Executes when selected object is changed in plotTypePanel.
function plotTypePanel_SelectionChangeFcn(hObject, eventdata, handles)
% hObject    handle to the selected object in plotTypePanel
% eventdata  structure with the following fields (see UIBUTTONGROUP)
%    EventName: string 'SelectionChanged' (read only)
%    OldValue: handle of the previously selected object or empty if none was selected
%    NewValue: handle of the currently selected object
% handles    structure with handles and user data (see GUIDATA)
handles = disableFields(handles, 'groupList', 'subjectList', 'parameterList', ...
    'conditionList', 'plotButton', 'binEdit', 'conditionSubList', 'indivSubs', ...
    'samePlotCheck', 'regExpBox', 'maxPerturbCheck', 'earlyNumPts', 'lateNumPts', ...
    'exptLastNumPts', 'removeBiasCheck', 'printCodeCheck', 'colorMenu', ...
    'saveColorsButton', 'biofeedback', 'AlignEnd2', 'InitiAlig');
for ii = 1:17
    set(handles.(['color' num2str(ii)]), 'Enable', 'Off');
end
%Then, enable things based on plot type
switch get(eventdata.NewValue,'Tag')
    case 'timeCourseButton'
        handles.plotType = 1;
        handles = enableFields(handles, 'groupList', 'subjectList', ...
            'parameterList', 'regExpBox', 'samePlotCheck', 'conditionList', ...
            'conditionSubList', 'indivSubs', 'binEdit', 'printCodeCheck', ...
            'colorMenu', 'saveColorsButton', 'biofeedback', 'removeBiasCheck', ...
            'AlignEnd2', 'InitiAlig');
        for ii = 1:17
            set(handles.(['color' num2str(ii)]), 'Enable', 'On');
        end
        set(handles.parameterList, 'Max',    10);
        set(handles.conditionText, 'String', 'Conditions');
    case 'earlyLateBarButton'
        handles.plotType = 2;
        handles = enableFields(handles, 'groupList', 'subjectList', ...
            'parameterList', 'regExpBox', 'conditionList', 'indivSubs', ...
            'earlyNumPts', 'lateNumPts', 'exptLastNumPts', 'removeBiasCheck', ...
            'printCodeCheck');
        set(handles.parameterList, 'Max',    10);
        set(handles.conditionText, 'String', 'Conditions');
    case 'scatterButton'
        handles.plotType = 3;
        handles = enableFields(handles, 'groupList', 'subjectList', ...
            'parameterList', 'regExpBox', 'conditionList', 'binEdit');
        set(handles.parameterList, 'Max', 3);
    case 'epochBarButton'
        results          = getResults(handles.Study, {'good'}, handles.groups(1));
        handles.plotType = 4;
        handles = enableFields(handles, 'groupList', 'parameterList', ...
            'regExpBox', 'conditionList', 'maxPerturbCheck', 'indivSubs', ...
            'printCodeCheck', 'colorMenu', 'saveColorsButton');
        for ii = 1:17
            set(handles.(['color' num2str(ii)]), 'Enable', 'On');
        end
        set(handles.parameterList, 'Max',    10);
        set(handles.conditionText, 'String', 'Epochs');
        set(handles.conditionList, 'String', fieldnames(results));
    case 'correlationButton'
        results          = getResults(handles.Study, {'good'}, handles.groups(1));
        handles.plotType = 5;
        handles = enableFields(handles, 'groupList', 'parameterList', ...
            'regExpBox', 'conditionList');
        set(handles.parameterList, 'Max',    5);
        set(handles.conditionText, 'String', 'Epochs');
        set(handles.conditionList, 'String', fieldnames(results), 'Max', 2);
    case 'CorrelationParams'
        results          = getResults(handles.Study, {'good'}, handles.groups(1));
        handles.plotType = 6;
        handles = enableFields(handles, 'groupList', 'parameterList', ...
            'regExpBox', 'conditionList');
        set(handles.parameterList, 'Max',    2);
        set(handles.conditionText, 'String', 'Epochs');
        set(handles.conditionList, 'String', fieldnames(results), 'Max', 5);
end
set(handles.plotButton, 'Enable', 'On')
guidata(hObject, handles);
end
%% ---------------- Selecting Groups/Subjects to Plot ----------------- %%
function groupList_Callback(hObject, eventdata, handles)
% When groups are selected, populate condition and parameter lists with
% options common to all subjects in those groups.
if ~isempty(get(hObject, 'Value'))
    % Use fieldnames — get(...,'String') returns HTML-formatted strings
    contents = fieldnames(handles.Study);
    groups   = contents(get(hObject, 'Value'));
    allGroups = handles.Study.(groups{1});
    for gg = 2:length(groups)
        allGroups = cat(allGroups, handles.Study.(groups{gg}));
    end
    % %populate condition listbox (All possible conditions)
    %     conditions={};
    %     for g=1:length(groups)
    %     conditions=[conditions handles.Study.(groups{g}).getCommonConditions];
    %     end
    %     conds=unique(conditions,'stable');
    %     set(handles.conditionList,'String',conds')
    if strcmpi(get(handles.conditionText, 'String'), 'conditions')
        conditionContents    = get(handles.conditionList,    'String');
        selectedConds        = conditionContents(get(handles.conditionList, 'Value'));
        conditionSubContents = get(handles.conditionSubList, 'String');
        selectedSubConds     = conditionSubContents(get(handles.conditionSubList, 'Value'));
        conditions = allGroups.getCommonConditions();
        set(handles.conditionList, 'String', conditions');
        condInds  = find(ismember(conditions, selectedConds));
        set(handles.conditionList,    'Value',  condInds);
        subConds  = conditions(condInds);
        set(handles.conditionSubList, 'String', subConds);
        subInds   = find(ismember(subConds, selectedSubConds));
        set(handles.conditionSubList, 'Value',  subInds);
    end
    parameterContents = get(handles.parameterList, 'String');
    selectedParams    = parameterContents(get(handles.parameterList, 'Value'));
    [parameters, handles.descriptions] = allGroups.getCommonParameters();
    set(handles.parameterList, 'String', parameters);
    paramInds = find(ismember(parameters, selectedParams));
    set(handles.parameterList, 'Value', paramInds);
    guidata(hObject, handles);
else
    if strcmp(get(handles.subjectList, 'Enable'), 'On')
        subjectList_Callback(handles.subjectList, eventdata, handles)
    end
end
end
% --- Executes on selection change in subjectList.
function subjectList_Callback(hObject, eventdata, handles)
if isempty(get(handles.groupList, 'Value'))
    if ~isempty(get(hObject, 'Value'))
        conditionContents    = get(handles.conditionList,    'String');
        selectedConds        = conditionContents(get(handles.conditionList, 'Value'));
        conditionSubContents = get(handles.conditionSubList, 'String');
        selectedSubConds     = conditionSubContents(get(handles.conditionSubList, 'Value'));
        parameterContents    = get(handles.parameterList,    'String');
        selectedParams       = parameterContents(get(handles.parameterList, 'Value'));
        selectedSubs = handles.subjects(get(hObject, 'Value'));
        groups       = fieldnames(handles.Study);
        boolFlag = false(1, length(groups));
        for gg = 1:length(groups)
            for jj = 1:length(selectedSubs)
                if ismember(selectedSubs{jj}, handles.Study.(groups{gg}).ID)
                    boolFlag(gg) = true;
                end
            end
        end
        groups = groups(boolFlag);
        allGroups = handles.Study.(groups{1});
        for gg = 2:length(groups)
            allGroups = cat(allGroups, handles.Study.(groups{gg}));
        end
        conditions                         = allGroups.getCommonConditions(selectedSubs);
        [parameters, handles.descriptions] = allGroups.getCommonParameters(selectedSubs);
        set(handles.conditionList, 'String', conditions');
        set(handles.parameterList, 'String', parameters);
        condInds  = find(ismember(conditions, selectedConds));
        set(handles.conditionList,    'Value',  condInds);
        subConds  = conditions(condInds);
        set(handles.conditionSubList, 'String', subConds);
        subInds   = find(ismember(subConds, selectedSubConds));
        set(handles.conditionSubList, 'Value',  subInds);
        paramInds = find(ismember(parameters, selectedParams));
        set(handles.parameterList,    'Value',  paramInds);
    else
        set(handles.conditionList,    'Value',  []);
        set(handles.conditionList,    'String', '');
        set(handles.conditionSubList, 'Value',  []);
        set(handles.conditionSubList, 'String', '');
        set(handles.parameterList,    'Value',  []);
        set(handles.parameterList,    'String', '');
    end
end
guidata(hObject, handles);
end
%% ------------  Other options for plotting ---------------- %%
% --- Executes on selection change in parameterList.
function parameterList_Callback(hObject, eventdata, handles)
values=get(hObject,'Value');
if strcmp(get(handles.figure1,'SelectionType'),'open')
    description=handles.descriptions{values}; % display window with parameter description
    msgbox(description,'Description');
end
%restrict the number of selected parameters to be less than or equal to
%'Max' property of the list
values=get(hObject,'Value');
newVals=values(~ismember(values,handles.paramVals));
handles.paramVals=values(ismember(values,handles.paramVals));
maxNum=get(hObject,'Max');
if length(values)>maxNum
    allVals=[handles.paramVals newVals];
    handles.paramVals=allVals(end-(maxNum-1):end);
else
    handles.paramVals=[handles.paramVals newVals];
end
set(hObject,'Value',handles.paramVals);
guidata(hObject, handles);
end
% --- Executes on selection change in conditionList.
function conditionList_Callback(hObject, eventdata, handles)
values=get(hObject,'Value');
newVals=values(~ismember(values,handles.paramVals));
handles.paramVals=values(ismember(values,handles.paramVals));
maxNum=get(hObject,'Max');
if length(values)>maxNum
    allVals=[handles.paramVals newVals];
    handles.paramVals=allVals(end-(maxNum-1):end);
else
    handles.paramVals=[handles.paramVals newVals];
end
set(hObject,'Value',handles.paramVals);
%add selected conditions to list for plotting individual trials (only for time course)
if handles.plotType==1
    conditionSubContents = get(handles.conditionSubList, 'String');
    selectedSubConds     = conditionSubContents(get(handles.conditionSubList, 'Value'));
    set(handles.conditionSubList, 'Value', []);
    contents = cellstr(get(hObject, 'String'));
    set(handles.conditionSubList, 'String', contents(get(hObject, 'Value')));
    %re-select conditions previously selected
    inds=find(ismember(contents(get(hObject,'Value')),selectedSubConds));
    set(handles.conditionSubList,'Value',inds);
end
end
function binEdit_Callback(hObject, eventdata, handles)
% Hints: get(hObject,'String') returns contents of binEdit as text
%        str2double(get(hObject,'String')) returns contents of binEdit as a double
end
% --- Executes on button press in indivSubs.
function indivSubs_Callback(hObject, eventdata, handles)
% Hint: get(hObject,'Value') returns toggle state of indivSubs
end
% --- Executes on button press in samePlotCheck.
function samePlotCheck_Callback(hObject, eventdata, handles)
% Hint: get(hObject,'Value') returns toggle state of samePlotCheck
end
% --- Executes on selection change in conditionSubList.
function conditionSubList_Callback(hObject, eventdata, handles)
% Hints: contents = cellstr(get(hObject,'String')) returns conditionSubList contents as cell array
%        contents{get(hObject,'Value')} returns selected item from conditionSubList
end
function regExpBox_Callback(hObject, eventdata, handles)
expression = get(hObject, 'String');
paramList  = cellstr(get(handles.parameterList, 'String'));
matchCells = regexp(paramList, expression);
matched    = cellfun(@(x) ~isempty(x), matchCells);
inds       = find(matched);
set(handles.parameterList, 'Value', ...
    inds(1:min([end, get(handles.parameterList, 'Max')])));
end
% --- Executes on button press in maxPerturbCheck.
function maxPerturbCheck_Callback(hObject, eventdata, handles)
% Hint: get(hObject,'Value') returns toggle state of maxPerturbCheck
end
function earlyNumPts_Callback(hObject, eventdata, handles)
% Hints: get(hObject,'String') returns contents of earlyNumPts as text
%        str2double(get(hObject,'String')) returns contents of earlyNumPts as a double
end
function lateNumPts_Callback(hObject, eventdata, handles)
% Hints: get(hObject,'String') returns contents of lateNumPts as text
%        str2double(get(hObject,'String')) returns contents of lateNumPts as a double
end
function exptLastNumPts_Callback(hObject, eventdata, handles)
% Hints: get(hObject,'String') returns contents of exptLastNumPts as text
%        str2double(get(hObject,'String')) returns contents of exptLastNumPts as a double
end
% --- Executes on button press in removeBiasCheck.
function removeBiasCheck_Callback(hObject, eventdata, handles)
% Hint: get(hObject,'Value') returns toggle state of removeBiasCheck
end
% --- Executes on button press in biofeedback.
function biofeedback_Callback(hObject, eventdata, handles)
% Hint: get(hObject,'Value') returns toggle state of biofeedback
end
% --- Executes on button press in printCodeCheck.
function printCodeCheck_Callback(hObject, eventdata, handles)
% Hint: get(hObject,'Value') returns toggle state of printCodeCheck
end
function AlignEnd2_Callback(hObject, eventdata, handles)
% Hints: get(hObject,'String') returns contents of AlignEnd2 as text
%        str2double(get(hObject,'String')) returns contents of AlignEnd2 as a double
end
function InitiAlig_Callback(hObject, eventdata, handles)
% Hints: get(hObject,'String') returns contents of InitiAlig as text
%        str2double(get(hObject,'String')) returns contents of InitiAlig as a double
end
%% ----------------- Open/Save button in toolstrip --------------------- %%
function saveTool_ClickedCallback(hObject, eventdata, handles)
end
function openTool_ClickedCallback(hObject, eventdata, handles)
%OPENTOOL_CLICKEDCALLBACK  Opens a study file and populates group/subject lists.
%
%   Inputs:
%     hObject   - handle to openTool (see GCBO)
%     eventdata - reserved for future MATLAB versions
%     handles   - struct with handles and user data (see GUIDATA)
%
% Toolbox Dependencies:
%   None
[handles.filename, handles.dir] = uigetfile('*.mat', 'Choose study file');
if handles.filename ~= 0
    msgHandle = msgbox('Opening...', '');
    child     = get(msgHandle, 'Children');
    delete(child(1));   % remove the OK button so the dialog is non-interactive
    drawnow
    loaded = load([handles.dir handles.filename]);
    close(msgHandle)
    fieldNames      = fieldnames(loaded);
    handles.varName = fieldNames{1};
    handles.Study   = loaded.(fieldNames{1});
    handles.paramVals = [];
    handles.groups    = fieldnames(handles.Study);
    groupNames       = handles.groups;
    subEntries       = {};
    handles.subjects = {};
    for ii = 1:length(groupNames)
        groupSubs        = handles.Study.(groupNames{ii}).ID;
        handles.subjects = [handles.subjects groupSubs];
        if mod(ii, 2) == 1   % bold odd-numbered groups for visual grouping
            for jj = 1:length(groupSubs)
                groupSubs{jj} = ['<html><b>' groupSubs{jj} '</b></html>'];
            end
        end
        subEntries = [subEntries; groupSubs']; %#ok<AGROW>
    end
    set(handles.subjectList, 'String', subEntries);
    for ii = 1:2:length(groupNames)
        groupNames{ii} = ['<html><b>' groupNames{ii} '</b></html>'];
    end
    set(handles.groupList, 'String', groupNames);
end
guidata(hObject, handles);
end
%% -------------------- Do the actual plotting ------------------------%%
function plotButton_Callback(hObject, eventdata, handles)
%PLOTBUTTON_CALLBACK  Executes the selected plot type with current settings.
%
%   Inputs:
%     hObject   - handle to plotButton (see GCBO)
%     eventdata - reserved for future MATLAB versions
%     handles   - struct with handles and user data (see GUIDATA)
%
% Toolbox Dependencies:
%   None
colorOrder = zeros(17, 3);
for ii = 1:17
    colorOrder(ii, :) = get(handles.(['color' num2str(ii)]), 'BackgroundColor');
end
groupContents = fieldnames(handles.Study);
adaptDataList = {};
indivSubList  = {};
indivSubStr   = '[]';
if handles.plotType == 2
    if ~isempty(get(handles.groupList, 'Value'))
        groups = groupContents(get(handles.groupList, 'Value'));
        for gg = 1:length(groups)
            adaptDataList{gg} = handles.Study.(groups{gg});
        end
    end
else
    if ~isempty(get(handles.groupList, 'Value'))
        groups = groupContents(get(handles.groupList, 'Value'));
        for gg = 1:length(groups)
            adaptDataList{gg} = handles.Study.(groups{gg}).adaptData;
        end
        adaptDataStr = ['{' strjoin( ...
            strcat([handles.varName '.'], groups, '.adaptData')', ',') '}'];
        if ~isempty(get(handles.subjectList, 'Value'))
            indivSubList = cell(1, length(get(handles.groupList, 'Value')));
            indivSubStr  = adaptDataStr;
            indivSubs    = handles.subjects(get(handles.subjectList, 'Value'));
            for gg = 1:length(groups)
                [isAinB, locAinB] = ismember(indivSubs, handles.Study.(groups{gg}).ID);
                for jj = 1:length(indivSubs)
                    if isAinB(jj)
                        indivSubList{gg}{end + 1} = ...
                            handles.Study.(groups{gg}).adaptData{locAinB(jj)};
                    end
                end
                indivSubStr = strrep(indivSubStr, ...
                    [groups{gg} '.adaptData'], ...
                    [groups{gg} '.adaptData{' num2str(locAinB(isAinB)) '}']);
            end
        end
    else
        if ~isempty(get(handles.subjectList, 'Value'))
            indivSubs = handles.subjects(get(handles.subjectList, 'Value'));
            for jj = 1:length(indivSubs)
                groups = fieldnames(handles.Study);
                for gg = 1:numel(groups)
                    [isAinB, locAinB] = ismember( ...
                        indivSubs{jj}, handles.Study.(groups{gg}).ID);
                    if isAinB
                        adaptDataList{end + 1} = ...
                            handles.Study.(groups{gg}).adaptData(locAinB);
                    end
                end
            end
        end
    end
end
paramContents = cellstr(get(handles.parameterList, 'String'));
params        = paramContents(get(handles.parameterList, 'Value'))';
if get(handles.samePlotCheck, 'Value')
    params = params';
end
if get(handles.samePlotCheck, 'Value')
    paramStr = ['{' strjoin(strcat('''', params, ''''), ';') '}'];
else
    paramStr = ['{' strjoin(strcat('''', params, ''''), ',') '}'];
end
condContents = cellstr(get(handles.conditionList, 'String'));
conds        = condContents(get(handles.conditionList, 'Value'));
condStr      = ['{' strjoin(strcat('''', conds, ''''), ',') '}'];
indivSubFlag    = get(handles.indivSubs,       'Value');
biofeedbackFlag = get(handles.biofeedback,     'Value');
removeBias      = get(handles.removeBiasCheck, 'Value');
switch handles.plotType
    case 1  % time course
        trialMarkerFlag = ismember(conds, conds(get(handles.conditionSubList, 'Value')));
        binwidth        = str2double(get(handles.binEdit,   'String'));
        alignEndFlag    = str2double(get(handles.AlignEnd2, 'String'));
        initiAligFlag   = str2double(get(handles.InitiAlig, 'String'));
        adaptationData.plotAvgTimeCourse(adaptDataList, params, conds, ...
            binwidth, trialMarkerFlag', indivSubFlag, indivSubList, colorOrder, ...
            biofeedbackFlag, removeBias, groups, [], [], alignEndFlag, initiAligFlag);
        if get(handles.printCodeCheck, 'Value')
            disp(['load(''' handles.dir handles.filename ''')'])
            disp(['adaptDataList = ' adaptDataStr ';'])
            disp(['params = ' paramStr ';'])
            disp(['conds = ' condStr ';'])
            disp(['binWidth = ' num2str(binwidth) ';'])
            disp(['trialMarkerFlag = [' num2str(trialMarkerFlag') '];'])
            disp(['indivSubFlag = ' num2str(indivSubFlag) ';'])
            disp(['IndivSubList = ' indivSubStr ';'])
            disp(['removeBias = ' num2str(removeBias) ';'])
            disp('% groups variable comes from the loaded studyData struct')
            disp(['adaptationData.plotAvgTimeCourse(adaptDataList,params,' ...
                'conds,binWidth,trialMarkerFlag,indivSubFlag,IndivSubList,' ...
                num2str(biofeedbackFlag) ',removeBias,groups)'])
        end
    case 2  % early/late bars
        removeBiasFlag      = get(handles.removeBiasCheck, 'Value');
        earlyNumber         = [str2double(get(handles.earlyNumPts, 'String')) ...
                               str2double(get(handles.lateNumPts,  'String'))];
        lateNumber          = [];
        exemptLast          = str2double(get(handles.exptLastNumPts, 'String'));
        legendNames         = [];
        significanceThresh  = 0.01;  % default significance threshold
        adaptationData.plotGroupedSubjectsBarsv2(adaptDataList, params, ...
            removeBiasFlag, indivSubFlag, conds, earlyNumber, lateNumber, ...
            exemptLast, legendNames, significanceThresh)
    case 3  % scatter plot
        binSize = str2double(get(handles.binEdit, 'String'));
        adaptationData.scatterPlotLab(adaptDataList, params, conds, ...
            [], [], binSize, [], removeBias)
    case 4  % epoch bars
        results = getResults(handles.Study, params, groups, ...
            get(handles.maxPerturbCheck, 'Value'));
        barGroups(handles.Study, results, groups, params, conds, ...
            indivSubFlag, colorOrder);
        if get(handles.printCodeCheck, 'Value')
            disp(['load(''' handles.dir handles.filename ''')'])
            disp(['groups = {' strjoin(strcat('''', groups, ''''), ',') '};'])
            disp(['params = ' paramStr ';'])
            disp(['results = getResults(' handles.varName ',params,groups,' ...
                num2str(get(handles.maxPerturbCheck, 'Value')) ');'])
            disp(['epochs = ' condStr ';'])
            disp(['indivSubFlag = ' num2str(indivSubFlag) ';'])
            disp(['barGroups(' handles.varName ...
                ',results,groups,params,epochs,indivSubFlag)'])
        end
    case 5  % correlation
        results = getResults(handles.Study, params, groups, ...
            get(handles.maxPerturbCheck, 'Value'));
        adaptationData.Correlations(adaptDataList, results, params, ...
            conds, groups, colorOrder, 1)
    case 6  % correlation by params
        results = getResults(handles.Study, params, groups, ...
            get(handles.maxPerturbCheck, 'Value'));
        adaptationData.Correlations(adaptDataList, results, params, ...
            conds, groups, colorOrder, 2)
end
end
%% ------------------ Color order selection ---------------------------- %%
% --- Executes on selection change in colorMenu.
function colorMenu_Callback(hObject, eventdata, handles)
colorPath  = which('PlotParamsGUI');
colorPath  = strrep(colorPath, 'PlotParamsGUI.m', 'Plotting Colors');
contents   = cellstr(get(hObject, 'String'));
colorFile  = contents{get(hObject, 'Value')};
if exist([colorPath filesep colorFile '.mat'], 'file') > 0
    colorData  = load([colorPath filesep colorFile]);
    fieldNames = fieldnames(colorData);
    colorOrder = colorData.(fieldNames{1});
    if size(colorOrder, 2) == 3 && ...
            max(colorOrder(:)) <= 1 && min(colorOrder(:)) >= 0
        for ii = 1:min([17, size(colorOrder, 1)])
            clr = colorOrder(ii, :);
            set(handles.(['color' num2str(ii)]), ...
                'String',          ['[' num2str(round(clr .* 255)) ']']);
            set(handles.(['color' num2str(ii)]), 'BackgroundColor', clr);
            set(handles.(['color' num2str(ii)]), ...
                'ForegroundColor', contrastColor(clr));
        end
    end
end
end
% --- Executes on button press in saveColorsButton.
function saveColorsButton_Callback(hObject, eventdata, handles)
% hObject    handle to saveColorsButton (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
colorOrder = nan(17, 3);
for ii = 1:17
    colorOrder(ii, :) = get(handles.(['color' num2str(ii)]), 'BackgroundColor');
end
answer    = inputdlg('Enter name of new color order: ', 'File Name Input');
colorPath = which('PlotParamsGUI');
colorPath = strrep(colorPath, 'PlotParamsGUI.m', 'Plotting Colors');
save([colorPath filesep char(answer)], 'colorOrder');
W           = what(colorPath);
colorOrders = cellstr(W.mat);
for ii = 1:length(colorOrders)
    fileExt         = find(colorOrders{ii} == '.');
    colorOrders{ii} = colorOrders{ii}(1:fileExt - 1);
end
set(handles.colorMenu, 'String', [' '; colorOrders]);
end
%% --------------------- Color Buttons --------------------------------%%
function color1_Callback(hObject, eventdata, handles)
handles = colorButtonCallback(hObject, handles);
guidata(hObject, handles);
end
function color2_Callback(hObject, eventdata, handles)
handles = colorButtonCallback(hObject, handles);
guidata(hObject, handles);
end
function color3_Callback(hObject, eventdata, handles)
handles = colorButtonCallback(hObject, handles);
guidata(hObject, handles);
end
function color4_Callback(hObject, eventdata, handles)
handles = colorButtonCallback(hObject, handles);
guidata(hObject, handles);
end
function color5_Callback(hObject, eventdata, handles)
handles = colorButtonCallback(hObject, handles);
guidata(hObject, handles);
end
function color6_Callback(hObject, eventdata, handles)
handles = colorButtonCallback(hObject, handles);
guidata(hObject, handles);
end
function color7_Callback(hObject, eventdata, handles)
handles = colorButtonCallback(hObject, handles);
guidata(hObject, handles);
end
function color8_Callback(hObject, eventdata, handles)
handles = colorButtonCallback(hObject, handles);
guidata(hObject, handles);
end
function color9_Callback(hObject, eventdata, handles)
handles = colorButtonCallback(hObject, handles);
guidata(hObject, handles);
end
function color10_Callback(hObject, eventdata, handles)
handles = colorButtonCallback(hObject, handles);
guidata(hObject, handles);
end
function color11_Callback(hObject, eventdata, handles)
handles = colorButtonCallback(hObject, handles);
guidata(hObject, handles);
end
function color12_Callback(hObject, eventdata, handles)
handles = colorButtonCallback(hObject, handles);
guidata(hObject, handles);
end
function color13_Callback(hObject, eventdata, handles)
handles = colorButtonCallback(hObject, handles);
guidata(hObject, handles);
end
function color14_Callback(hObject, eventdata, handles)
handles = colorButtonCallback(hObject, handles);
guidata(hObject, handles);
end
function color15_Callback(hObject, eventdata, handles)
handles = colorButtonCallback(hObject, handles);
guidata(hObject, handles);
end
function color16_Callback(hObject, eventdata, handles)
handles = colorButtonCallback(hObject, handles);
guidata(hObject, handles);
end
function color17_Callback(hObject, eventdata, handles)
handles = colorButtonCallback(hObject, handles);
guidata(hObject, handles);
end
function handles = colorButtonCallback(hObject, handles)
%COLORBUTTONCALLBACK  Open color picker and update button appearance.
clr = uisetcolor(get(hObject, 'BackgroundColor'), 'Set Color');
rgb = round(clr .* 255);
set(hObject, 'BackgroundColor', clr);
set(hObject, 'ForegroundColor', contrastColor(clr));
set(hObject, 'String', ['[' num2str(rgb) ']']);
end
%% ------------- CREATE FUNCTIONS - DO NOT EDIT ------------------------%%
% hObject    handle to exptLastNumPts (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
function conditionList_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject, 'BackgroundColor'), get(0, 'defaultUicontrolBackgroundColor'))
    set(hObject, 'BackgroundColor', 'White');
end
end
function parameterList_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject, 'BackgroundColor'), get(0, 'defaultUicontrolBackgroundColor'))
    set(hObject, 'BackgroundColor', 'White');
end
end
function groupList_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject, 'BackgroundColor'), get(0, 'defaultUicontrolBackgroundColor'))
    set(hObject, 'BackgroundColor', 'White');
end
end
function binEdit_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject, 'BackgroundColor'), get(0, 'defaultUicontrolBackgroundColor'))
    set(hObject, 'BackgroundColor', 'White');
end
end
function subjectList_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject, 'BackgroundColor'), get(0, 'defaultUicontrolBackgroundColor'))
    set(hObject, 'BackgroundColor', 'White');
end
end
function conditionSubList_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject, 'BackgroundColor'), get(0, 'defaultUicontrolBackgroundColor'))
    set(hObject, 'BackgroundColor', 'White');
end
end
function regExpBox_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject, 'BackgroundColor'), get(0, 'defaultUicontrolBackgroundColor'))
    set(hObject, 'BackgroundColor', 'White');
end
end
function earlyNumPts_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject, 'BackgroundColor'), get(0, 'defaultUicontrolBackgroundColor'))
    set(hObject, 'BackgroundColor', 'White');
end
end
function lateNumPts_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject, 'BackgroundColor'), get(0, 'defaultUicontrolBackgroundColor'))
    set(hObject, 'BackgroundColor', 'White');
end
end
function exptLastNumPts_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject, 'BackgroundColor'), get(0, 'defaultUicontrolBackgroundColor'))
    set(hObject, 'BackgroundColor', 'White');
end
end
function colorMenu_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject, 'BackgroundColor'), get(0, 'defaultUicontrolBackgroundColor'))
    set(hObject, 'BackgroundColor', 'White');
end
end
% --- If Enable == 'on', executes on mouse press in 5 pixel border.
% --- Otherwise, executes on mouse press in 5 pixel border or over regExpBox.
function regExpBox_ButtonDownFcn(hObject, eventdata, handles)
% hObject    handle to regExpBox (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
end
function AlignEnd2_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject, 'BackgroundColor'), get(0, 'defaultUicontrolBackgroundColor'))
    set(hObject, 'BackgroundColor', 'White');
end
end
function InitiAlig_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject, 'BackgroundColor'), get(0, 'defaultUicontrolBackgroundColor'))
    set(hObject, 'BackgroundColor', 'White');
end
end