Description of filterStationary
Home > fun > ext > pitools > kalmanFilter > filterStationary.m
filterStationary
PURPOSE
filterStationary implements a Kalman filter assuming
SYNOPSIS
function [X,P,Xp,Pp,rejSamples]=filterStationary(Y,A,C,Q,R,x0,P0,B,D,U,outlierRejection)
DESCRIPTION
filterStationary implements a Kalman filter assuming
stationary (fixed) noise matrices and system dynamics
The model is: x[k+1]=A*x[k]+b+v[k], v~N(0,Q)
y[k]=C*x[k]+d+w[k], w~N(0,R)
CROSS-REFERENCE INFORMATION
This function calls:
predict predict implements Kalman's predict step
updateKF update implements Kalman's update step
update_wOutlierRejection
This function is called by:
mainTest % Test function for Kalman filter
mainTestConstraints % Generate data
smoothStationary Init missing params:
SOURCE CODE
function [X,P,Xp,Pp,rejSamples]=filterStationary(Y,A,C,Q,R,x0,P0,B,D,U,outlierRejection)
%filterStationary implements a Kalman filter assuming
%stationary (fixed) noise matrices and system dynamics
%The model is: x[k+1]=A*x[k]+b+v[k], v~N(0,Q)
%y[k]=C*x[k]+d+w[k], w~N(0,R)
%Init missing params:
if nargin<6 || isempty(x0)
  x0=zeros(size(A,1),1); %Column vector
end
if nargin<7 || isempty(P0)
  P0=1e8 * eye(size(A));
end
if nargin<8 || isempty(B)
  B=0;
end
if nargin<9 || isempty(D)
  D=0;
end
if nargin<10 || isempty(U)
  U=zeros(size(B,2),size(X,2));
end
%Size checks:
%TODO
%Do the filtering
Xp=nan(size(A,1),size(Y,2));
X=nan(size(A,1),size(Y,2));
Pp=nan(size(A,1),size(A,1),size(Y,2));
P=nan(size(A,1),size(A,1),size(Y,2));
prevX=x0;
prevP=P0;
rejSamples=zeros(size(Y));
for i=1:size(Y,2)
  b=B*U(:,i);
  [prevX,prevP]=predict(A,Q,prevX,prevP,b);
  Xp(:,i)=prevX;
  Pp(:,:,i)=prevP;
  d=D*U(:,i);
  if ~outlierRejection
    [prevX,prevP]=updateKF(C,R,prevX,prevP,Y(:,i),d);
  else
    [prevX,prevP,rejSamples(:,i)]=update_wOutlierRejection(C,R,prevX,prevP,Y(:,i),d);
  end
  X(:,i)=prevX;
  P(:,:,i)=prevP;
end
end