Description of update_wOutlierRejection
Home > fun > ext > pitools > kalmanFilter > update_wOutlierRejection.m
update_wOutlierRejection
PURPOSE
SYNOPSIS
function [x,P,outlierIndx]=update_wOutlierRejection(C,R,x,P,y,d)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
detectOutliers
updateKF update implements Kalman's update step
This function is called by:
filterStationary filterStationary implements a Kalman filter assuming
filterStationary_wConstraint Same as filterStationary but allowing for a generic constraint model for the states.
SOURCE CODE
function [x,P,outlierIndx]=update_wOutlierRejection(C,R,x,P,y,d)
[outlierIndx]=detectOutliers(y-d,x,P,C,R);
if any(~outlierIndx)
%Update without outliers, by setting outliers to exactly what we expect
%with inifinite uncertainty
%y(outlierIndx)=C(outlierIndx,:)*x + d(outlierIndx); %Unnecessary
R(outlierIndx,:)=1/eps;
R(:,outlierIndx)=1/eps;
%Alt: (equivalent) eliminate outliers before update
%y=y(~outlierIndx);
%C=C(~outlierIndx,:);
%R=R(~outlierIndx,~outlierIndx);
[x,P]=updateKF(C,R,x,P,y,d);
end
%Al
end