Description of updateKF
Home > fun > ext > pitools > kalmanFilter > updateKF.m
updateKF
PURPOSE
update implements Kalman's update step
SYNOPSIS
function [x,P]=updateKF(C,R,x,P,y,d)
DESCRIPTION
update implements Kalman's update step
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
filterStationary filterStationary implements a Kalman filter assuming
filterStationary_wConstraint Same as filterStationary but allowing for a generic constraint model for the states.
update_wOutlierRejection
SOURCE CODE
function [x,P]=updateKF(C,R,x,P,y,d)
  %update implements Kalman's update step
  K=P*C'/(C*P*C'+R);
x=x+K*(y-C*x-d);
P=P-K*C*P;
end