Description of extractStimArtifactIndsFromTrigger
Home > labTools > fun > +Hreflex > extractStimArtifactIndsFromTrigger.m
extractStimArtifactIndsFromTrigger
PURPOSE
EXTRACTSTIMARTIFACTINDSFROMTRIGGER Extract TAP stim artifact peak indices.
SYNOPSIS
function indsStimArtifact = extractStimArtifactIndsFromTrigger(times, rawEMG_TAP, pinHreflexStim, options)
DESCRIPTION
EXTRACTSTIMARTIFACTINDSFROMTRIGGER Extract TAP stim artifact peak indices.
   Extract the indices of the stimulation artifact peaks in the proximal
 tibialis anterior EMG signal (more robust than calf muscles during
 walking) using the rising edge of the stimulation trigger pulse to
 localize the artifact peak.
 Inputs:
   times          - number of samples x 1 array of time in seconds from
                    the start of the trial for each sample
   rawEMG_TAP     - 2-element cell of number of samples x 1 arrays for
                    right (cell 1) and left (cell 2) proximal TA EMG
                    (if one cell is empty, that leg is skipped)
   pinHreflexStim - 2-element cell of number of samples x 1 arrays for
                    right (cell 1) and left (cell 2) stim trigger pulses
 Optional Name-Value Inputs:
   threshStim      - stim trigger pulse detection threshold, V
                     (default: 2.5)
   winDurStim      - search window duration around trigger pulse, s
                     (default: 0.1)
   minArtifactPeak - minimum stim artifact peak height, V (default: 0.001)
 Outputs:
   indsStimArtifact - 2 x 1 cell of number of stimuli x 1 arrays for
                      right (cell 1) and left (cell 2) stim artifact
                      indices
 Toolbox Dependencies:
   None
 See also HREFLEX.EXTRACTSNIPPETS, COMPUTEHREFLEXPARAMETERS.
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
mean mean Computes mean across strides
times times Multiplies by constant
times times Multiplies data by constant
times times Multiplies by constant (override)
This function is called by:
SUBFUNCTIONS
function stimTimes = getStimOnsetTimes(stimTrig, times, threshStim)
function indsStimArtifact = findStimArtifactInds(times, rawEMG,
SOURCE CODE
function indsStimArtifact = extractStimArtifactIndsFromTrigger(...
    times, rawEMG_TAP, pinHreflexStim, options)
%EXTRACTSTIMARTIFACTINDSFROMTRIGGER Extract TAP stim artifact peak indices.
%
%   Extract the indices of the stimulation artifact peaks in the proximal
% tibialis anterior EMG signal (more robust than calf muscles during
% walking) using the rising edge of the stimulation trigger pulse to
% localize the artifact peak.
%
% Inputs:
%   times          - number of samples x 1 array of time in seconds from
%                    the start of the trial for each sample
%   rawEMG_TAP     - 2-element cell of number of samples x 1 arrays for
%                    right (cell 1) and left (cell 2) proximal TA EMG
%                    (if one cell is empty, that leg is skipped)
%   pinHreflexStim - 2-element cell of number of samples x 1 arrays for
%                    right (cell 1) and left (cell 2) stim trigger pulses
%
% Optional Name-Value Inputs:
%   threshStim      - stim trigger pulse detection threshold, V
%                     (default: 2.5)
%   winDurStim      - search window duration around trigger pulse, s
%                     (default: 0.1)
%   minArtifactPeak - minimum stim artifact peak height, V (default: 0.001)
%
% Outputs:
%   indsStimArtifact - 2 x 1 cell of number of stimuli x 1 arrays for
%                      right (cell 1) and left (cell 2) stim artifact
%                      indices
%
% Toolbox Dependencies:
%   None
%
% See also HREFLEX.EXTRACTSNIPPETS, COMPUTEHREFLEXPARAMETERS.
arguments
    times             (:,1) double
    rawEMG_TAP        cell
    pinHreflexStim    cell
    options.threshStim      (1,1) double {mustBePositive} = 2.5   % V
    options.winDurStim      (1,1) double {mustBePositive} = 0.1   % s
    options.minArtifactPeak (1,1) double {mustBePositive} = 0.001 % V
end
if isempty(times) || all(cellfun(@isempty, rawEMG_TAP)) || ...
        all(cellfun(@isempty, pinHreflexStim))
    error(['There is data missing that is crucial for computing the ' ...
        'stimulation artifact indices']);
end
% NOTE: it does not work to use stim trigger pulse to retrieve peak times
% if stimulator is disabled during trial (because there will be a trigger
% pulse but the participant will not have been stimulated)
%% Identify Stimulation Onset Times
stimTimeRAbs = getStimOnsetTimes(...
    pinHreflexStim{1}, times, options.threshStim);
stimTimeLAbs = getStimOnsetTimes(...
    pinHreflexStim{2}, times, options.threshStim);
%% Localize Artifact Peaks in EMG Signal
indsStimArtifact = cell(2, 1);
indsStimArtifact{1} = findStimArtifactInds(times, rawEMG_TAP{1}, ...
    stimTimeRAbs, options.winDurStim, options.minArtifactPeak);
indsStimArtifact{2} = findStimArtifactInds(times, rawEMG_TAP{2}, ...
    stimTimeLAbs, options.winDurStim, options.minArtifactPeak);
end
%% Helper Functions
function stimTimes = getStimOnsetTimes(stimTrig, times, threshStim)
% detect rising edges of stimulation trigger pulses
indsStimAll = find(stimTrig > threshStim);
% determine which indices correspond to start of new stimulus pulse
% (i.e., there is jump in index greater than 1, not just next sample)
indsNewPulse = diff([0; indsStimAll]) > 1;      % rising edges
% determine time since trial start when stim pulse began (rising edge)
stimTimes = times(indsStimAll(indsNewPulse));
end
function indsStimArtifact = findStimArtifactInds(times, rawEMG, ...
    stimTimes, winDurStim, minPeakHeight)
% identify stim artifact indices in EMG signal around stimulation times
if isempty(rawEMG) || isempty(stimTimes)    % if no EMG or stim data, ...
    indsStimArtifact = [];                  % return empty array
    return;
end
period = mean(diff(times));                 % sampling period
winSamples = round(winDurStim / period);    % search window dur. in samples
numStim = numel(stimTimes);                 % number of stimuli
indsStimArtifact = nan(numStim, 1);         % initialize array of indices
for st = 1:numStim                          % for each stimulus, ...
    % locate EMG data index corresponding to onset of stim trigger pulse
    [~, indStim] = min(abs(times - stimTimes(st)));
    % ensure window does not exceed EMG data in case stim near trial end
    winSearch = max(1, indStim - winSamples): ...   % search window around
        min(length(rawEMG), indStim + winSamples);  % stimulation time
    [~, locs] = findpeaks(rawEMG(winSearch), ...
        'MinPeakHeight', minPeakHeight);
    if isempty(locs)                        % if no peaks detected, ...
        [~, indMaxTAP] = max(rawEMG(winSearch)); % use maximum as peak
    else                                    % otherwise, ...
        indMaxTAP = locs(1);                % use first (earliest) peak
    end
    indsStimArtifact(st) = winSearch(indMaxTAP);
end
end