Description of plotSnippets
Home > labTools > fun > +Hreflex > plotSnippets.m
plotSnippets
PURPOSE
PLOTSNIPPETS Plot H-reflex snippets with GRFs if available.
SYNOPSIS
function fig = plotSnippets(times, snippets, yLabels, titles,id, trialNum, options)
DESCRIPTION
PLOTSNIPPETS Plot H-reflex snippets with GRFs if available.
   Plot the H-reflex snippets for desired muscles or forces (if desired)
 with the window bounds for M-wave and H-wave indicated by vertical lines.
 Inputs:
   times    - number of samples x 1 array of time in seconds with 0
              indicating the identified stimulation artifact peak
   snippets - 2 x 3 cell of number of snippets x number of samples
              arrays for right (row 1) and left (row 2) leg H-reflex
              (col 1), ipsilateral (col 2), and contralateral (col 3)
              GRF snippets
   yLabels  - N x 1 cell array of y-axis label strings for each tile
   titles   - N x 1 cell array of title strings for each tile
   id       - string or character array of participant/session ID
   trialNum - string or character array of the trial number
 Optional Name-Value Inputs:
   pathFig - path for saving figures; not saved if empty (default: '')
 Outputs:
   fig - handle to the figure generated
 Toolbox Dependencies:
   None
 See also HREFLEX.EXTRACTSNIPPETS, HREFLEX.COMPUTEAMPLITUDES.
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
plot plot Plots aligned data with mean
times times Multiplies by constant
plot plot Plots data in subplots
times times Multiplies data by constant
times times Multiplies by constant (override)
plot PLOT Implementation for ClusteredSynergySetCollection
plot PLOT Implementation of the plot method for SynergySetCollections
This function is called by:
SOURCE CODE
function fig = plotSnippets(times, snippets, yLabels, titles, ...
    id, trialNum, options)
%PLOTSNIPPETS Plot H-reflex snippets with GRFs if available.
%
%   Plot the H-reflex snippets for desired muscles or forces (if desired)
% with the window bounds for M-wave and H-wave indicated by vertical lines.
%
% Inputs:
%   times    - number of samples x 1 array of time in seconds with 0
%              indicating the identified stimulation artifact peak
%   snippets - 2 x 3 cell of number of snippets x number of samples
%              arrays for right (row 1) and left (row 2) leg H-reflex
%              (col 1), ipsilateral (col 2), and contralateral (col 3)
%              GRF snippets
%   yLabels  - N x 1 cell array of y-axis label strings for each tile
%   titles   - N x 1 cell array of title strings for each tile
%   id       - string or character array of participant/session ID
%   trialNum - string or character array of the trial number
%
% Optional Name-Value Inputs:
%   pathFig - path for saving figures; not saved if empty (default: '')
%
% Outputs:
%   fig - handle to the figure generated
%
% Toolbox Dependencies:
%   None
%
% See also HREFLEX.EXTRACTSNIPPETS, HREFLEX.COMPUTEAMPLITUDES.
% TODO: adapt this function to work for generating any snippets plot
arguments
    times    (:,1) double
    snippets (2,3) cell
    yLabels  cell
    titles   cell
    id       (1,:) {mustBeText}
    trialNum (1,:) {mustBeText}
    options.pathFig (1,:) char = ''
end
%% Validate Input Dimensions
numSnipSamps = cellfun(@(x) size(x, 2), snippets);
numSnipSamps = reshape(numSnipSamps, 1, []);
numUniqueSampleCounts = length(unique([numSnipSamps length(times)]));
if numUniqueSampleCounts > 1    % if sample counts differ across arrays, ...
    error('There are different numbers of samples across arrays.');
end
% TODO: ensure that there is at least one snippet
% ensure the number of titles and labels matches the number of tiles
if all(cellfun(@isempty, snippets(:, 2:3)))
    numTiles = 2;           % right and left EMG
else
    numTiles = 4;           % right GRFs, left GRFs, right EMG, left EMG
    if length(titles) ~= numTiles || length(yLabels) ~= numTiles
        error('Mismatch between the number of tiles, titles, or yLabels.');
    end
end
%% Create Figure
fig = figure;
tl = tiledlayout(numTiles, 1, 'TileSpacing', 'tight', 'Padding', 'compact');
%% Plot GRF Tiles
% NOTE: assuming inputs in desired plot order from top to bottom
% check for force data (columns 2 & 3) and plot combined GRFs if available
if ~isempty(snippets{1,2}) && ~isempty(snippets{1,3})
    nexttile;           % plot right leg ipsilateral and contralateral GRFs
    hold on;
    plot(times, snippets{1,2}, 'LineWidth', 1.5, ...
        'Color', [0.000 0.447 0.741]);
    plot(times, snippets{1,3}, 'LineWidth', 1.5, ...
        'Color', [0.850 0.325 0.098]);
    title(titles{1});
    ylabel(yLabels{1});
    xlim([times(1) times(end)]);
    hold off;
end
if ~isempty(snippets{2,2}) && ~isempty(snippets{2,3})
    nexttile;           % plot left leg ipsilateral and contralateral GRFs
    hold on;
    plot(times, snippets{2,2}, 'LineWidth', 1.5, ...
        'Color', [0.000 0.447 0.741]);
    plot(times, snippets{2,3}, 'LineWidth', 1.5, ...
        'Color', [0.850 0.325 0.098]);
    title(titles{2});
    ylabel(yLabels{2});
    xlim([times(1) times(end)]);
    hold off;
end
%% Plot EMG Tiles
ax   = gobjects(1, 2);     % initialize array of Axes objects
% TODO: move y-axis limit code outside this function or make optional input
% (e.g., which index to start from) for more flexibility
indsYLims = times > 0.005;
ymin = 0;                   % initialize minimum y-axis value to be 0
ymax = 0;
for ii = 1:2                % for each EMG H-reflex snippets array, ...
    ax(ii) = nexttile;      % advance to next figure tile
    hold on;
    xline(0, 'k', 'LineWidth', 2);  % stimulation artifact alignment
    % M-wave and H-wave range
    % TODO: update to accept as function input rather than hard-coding
    xline(0.0045, 'b', 'LineWidth', 1.5);  % M-wave start: 4.5 ms after stim
    xline(0.0200, 'b', 'LineWidth', 1.5);  % M-wave end: 20 ms after stim
    xline(0.0250, 'g', 'LineWidth', 1.5);  % H-wave start: 25 ms after stim
    xline(0.0450, 'g', 'LineWidth', 1.5);  % H-wave end: 45 ms after stim
    plot(times, snippets{ii,1}, 'LineWidth', 1.5);
    hold off;
    title(titles{ii+2}); % EMG titles are in positions 3 and 4
    ylabel(yLabels{ii+2});
    newYmin = min(snippets{ii,1}(:, indsYLims), [], 'all');
    newYmax = max(snippets{ii,1}(:, indsYLims), [], 'all');
    if newYmin < ymin       % if minimum y-value less than previous, ...
        ymin = newYmin;     % update minimum y-axis value
    end
    if newYmax > ymax       % if maximum y-value greater than previous, ...
        ymax = newYmax;     % update maximum y-axis value
    end
end
%% Finalize Axes & Labels
linkaxes(ax);
xlim([times(1) times(end)]);
ylim([ymin ymax]);
% TODO: should y-axis limits be the same in case of both legs present?
% TODO: consider accepting labels as optional input argument
% TODO: make figure title and filename optional inputs
xlabel(tl, 'Time (s)');
title(tl, sprintf('%s - Trial %s - H-Reflex Snippets', id, trialNum));
if ~isempty(options.pathFig)        % if figure saving path provided, ...
    saveas(fig, fullfile(options.pathFig, ...
        sprintf('%s_HreflexSnippets_Trial%s.fig', id, trialNum)));
    saveas(fig, fullfile(options.pathFig, ...
        sprintf('%s_HreflexSnippets_Trial%s.png', id, trialNum)));
end
end