Description of recomputeEvents
Home > labTools > classes > dataStructs > @experimentData > recomputeEvents.m
recomputeEvents
PURPOSE
recomputeEvents Recalculates gait events and parameters
SYNOPSIS
function this = recomputeEvents(this, eventClass, initEventSide)
DESCRIPTION
recomputeEvents  Recalculates gait events and parameters
   this = recomputeEvents(this) recomputes events and parameters for
   all trials with default options
   this = recomputeEvents(this, eventClass, initEventSide)
   recomputes with specified options
   Inputs:
       this - experimentData object
       eventClass - event classification parameter (optional)
       initEventSide - initial event side specification (optional)
   Outputs:
       this - experimentData object with recomputed events and parameters
   See also: processedLabData/recomputeEvents, recomputeParameters
CROSS-REFERENCE INFORMATION
This function calls:
recomputeEvents recomputeEvents Recalculates gait events and parameters
recomputeEvents recomputeEvents Re-calculates gait events from angle data
recomputeEvents recomputeEvents Re-computes gait events and adaptation parameters
cell2mat cell2mat Converts cell array of strideData to matrix
This function is called by:
experimentData
recomputeEvents recomputeEvents Recalculates gait events and parameters
labData
processedLabData
SOURCE CODE
function this = recomputeEvents(this, eventClass, initEventSide)
%recomputeEvents  Recalculates gait events and parameters
%
%   this = recomputeEvents(this) recomputes events and parameters for
%   all trials with default options
%
%   this = recomputeEvents(this, eventClass, initEventSide)
%   recomputes with specified options
%
%   Inputs:
%       this - experimentData object
%       eventClass - event classification parameter (optional)
%       initEventSide - initial event side specification (optional)
%
%   Outputs:
%       this - experimentData object with recomputed events and parameters
%
%   See also: processedLabData/recomputeEvents, recomputeParameters
trials = cell2mat(this.metaData.trialsInCondition);
for t = trials
    % This recomputes events AND recomputes parameters (otherwise
    % parameters will not correspond to the new events)
    this.data{t} = recomputeEvents(this.data{t});
end
end