Description of getSimpleFileName
Home > labTools > fun > misc > getSimpleFileName.m
getSimpleFileName
PURPOSE
SYNOPSIS
function [file] = getSimpleFileName(filename)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
This function is called by:
calcLimbAngles calcLimbAngles Calculates limb and joint angles from marker data.
getEvents GETEVENTS Extract gait events from a raw trial, selecting the appropriate
calcParameters CALCPARAMETERS Compute stride-by-stride parameters for analysis.
SOURCE CODE
function [file] = getSimpleFileName(filename)
if isa(filename,'cell') %Case where there are several filenames, using the first one only (arbitrary!)
    filename=filename{1};
end
slashes=find(filename=='\' | filename=='/');
if ~isempty(slashes)
    file=filename((slashes(end)+1):end);
else
    file=filename;
end
end