Description of skDistdetect
Home > labTools > fun > ext > markerDataCleaning > staticSkeleton > skDistdetect.m
skDistdetect
PURPOSE
SYNOPSIS
function [markerLogL,totalLogL] = skDistdetect(data,m,R)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
computeDistanceMatrix computeDistanceMatrix Computes inter-marker distances
computeDistanceMatrix Gets position data as N markers x 3D x M frames and for each frame
This function is called by:
testMarkerOutlierDetectAndCorrect TESTMARKEROUTLIERDETECTANDCORRECT Example: detect and correct marker outliers using skeleton models.
SOURCE CODE
function [markerLogL,totalLogL] = skDistdetect(data,m,R)
[N,d,M]=size(data);
[D] = computeDistanceMatrix(data); %Will be NxNxM
missing=squeeze(any(isnan(data),2));
clear data
D=D-m; %Subtracting mean
C=R+1e3*max(abs(R(:)))*eye(N);
auxScores=D.^2 ./C;
totalLogL=squeeze(nanmean(nanmean(nanmean(auxScores))));
%markerLogL=nan(N,M);
markerLogL=squeeze(nanmedian(reshape(auxScores,N,N,M),2));
%markerLogL=squeeze(mean(reshape(auxScores,N,N*d,M),2));
markerLogL(missing)=-10;
end