Description of checkConditionOrder
Home > labTools > classes > dataStructs > metaData > @experimentMetaData > checkConditionOrder.m
checkConditionOrder
PURPOSE
checkConditionOrder Checks that conditions appear in order
SYNOPSIS
function conditionOrder = checkConditionOrder(this,conditionNamesInOrder, silentFlag)
DESCRIPTION
checkConditionOrder  Checks that conditions appear in order
   conditionOrder = checkConditionOrder(this) checks that all
   conditions appear in order according to trial numbering
   conditionOrder = checkConditionOrder(this,
   conditionNamesInOrder, silentFlag) checks specified conditions and
   optionally displays warnings
   Inputs:
       this - experimentMetaData object
       conditionNamesInOrder - cell array of condition names to check
                               (optional, default: all conditions)
       silentFlag - if false, displays warnings for out-of-order
                    conditions (optional, default: true)
   Outputs:
       conditionOrder - vector indicating order of conditions by first
                        trial number
   See also: validateTrialsInCondition, sortConditions
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
validateTrialsInCondition validateTrialsInCondition Validates trial organization
This function is called by:
experimentMetaData
SOURCE CODE
function conditionOrder = checkConditionOrder(this, ...
    conditionNamesInOrder, silentFlag)
%checkConditionOrder  Checks that conditions appear in order
%
%   conditionOrder = checkConditionOrder(this) checks that all
%   conditions appear in order according to trial numbering
%
%   conditionOrder = checkConditionOrder(this,
%   conditionNamesInOrder, silentFlag) checks specified conditions and
%   optionally displays warnings
%
%   Inputs:
%       this - experimentMetaData object
%       conditionNamesInOrder - cell array of condition names to check
%                               (optional, default: all conditions)
%       silentFlag - if false, displays warnings for out-of-order
%                    conditions (optional, default: true)
%
%   Outputs:
%       conditionOrder - vector indicating order of conditions by first
%                        trial number
%
%   See also: validateTrialsInCondition, sortConditions
if nargin < 2 || isempty(conditionNamesInOrder)
    conditionNamesInOrder = this.conditionName;
end
% Doing validation of trials, and getting conditionOrder
conditionOrder = validateTrialsInCondition(this);
conditionIdxsInOrder = ...
    this.getConditionIdxsFromName(conditionNamesInOrder);
% Keeping order of requested conditions only
conditionOrder = conditionOrder(conditionIdxsInOrder);
if nargin > 2 && ~isempty(silentFlag) && ~silentFlag
    if any(diff(conditionOrder) < 1)
        badOrder = find(diff(conditionOrder) < 1);
        for i = 1:length(badOrder)
            disp(['Conditions provided are not in order: ' ...
                conditionNamesInOrder{badOrder(i)} ' precedes ' ...
                conditionNamesInOrder{badOrder(i) + 1}]);
        end
    end
end
end