Description of computeDistanceMatrix
Home > labTools > classes > labTS > @orientedLabTimeSeries > computeDistanceMatrix.m
computeDistanceMatrix
PURPOSE
computeDistanceMatrix Computes inter-marker distances
SYNOPSIS
function [distMatrix, labels, labels2, Time] = computeDistanceMatrix(this, t0, t1, labels, labels2)
DESCRIPTION
computeDistanceMatrix  Computes inter-marker distances
   [distMatrix, labels, labels2, Time] = computeDistanceMatrix(this,
   t0, t1, labels, labels2) computes Euclidean distances between
   markers
   Inputs:
       this - orientedLabTimeSeries object
       t0 - start time (optional)
       t1 - end time (optional)
       labels - markers to compute from (optional)
       labels2 - markers to compute to (optional)
   Outputs:
       distMatrix - 3D matrix (time x markers1 x markers2) of distances
       labels - cell array of marker1 labels used
       labels2 - cell array of marker2 labels used
       Time - time vector
   See also: computeDifferenceMatrix
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
computeDifferenceMatrix computeDifferenceMatrix Computes inter-marker differences
This function is called by:
orientedLabTimeSeries
naiveDistances
createZeroModel UNTITLED6 Summary of this function goes here
determineLikelihoodFromZeroModel Computes a likelihood for a set of marker positions given a 'zero-model'
skDistdetect
skDistenforce Given a prior estimate x with uncertainty P (normal dist) of some variable x, and the
skDistlearn Returns model such that W*d(pos(:,:,i)) ~ N(m,R)
SOURCE CODE
function [distMatrix, labels, labels2, Time] = computeDistanceMatrix(...
    this, t0, t1, labels, labels2)
%computeDistanceMatrix  Computes inter-marker distances
%
%   [distMatrix, labels, labels2, Time] = computeDistanceMatrix(this,
%   t0, t1, labels, labels2) computes Euclidean distances between
%   markers
%
%   Inputs:
%       this - orientedLabTimeSeries object
%       t0 - start time (optional)
%       t1 - end time (optional)
%       labels - markers to compute from (optional)
%       labels2 - markers to compute to (optional)
%
%   Outputs:
%       distMatrix - 3D matrix (time x markers1 x markers2) of distances
%       labels - cell array of marker1 labels used
%       labels2 - cell array of marker2 labels used
%       Time - time vector
%
%   See also: computeDifferenceMatrix
if nargin < 2 || isempty(t0)
    t0 = [];
end
if nargin < 3 || isempty(t1)
    t1 = [];
end
if nargin < 4 || isempty(labels)
    labels = [];
end
if nargin < 5 || isempty(labels2)
    labels2 = [];
end
[diffMatrix, labels, labels2, Time] = computeDifferenceMatrix(this, ...
    t0, t1, labels, labels2);
distMatrix = sqrt(sum(diffMatrix.^2, 4));
end