Description of getDataAsOTS
Home > labTools > classes > labTS > @orientedLabTimeSeries > getDataAsOTS.m
getDataAsOTS
PURPOSE
getDataAsOTS Returns subset as orientedLabTimeSeries
SYNOPSIS
function newThis = getDataAsOTS(this, label)
DESCRIPTION
getDataAsOTS  Returns subset as orientedLabTimeSeries
   newThis = getDataAsOTS(this) returns all data as OTS
   newThis = getDataAsOTS(this, label) returns data for specified
   marker prefixes
   Inputs:
       this - orientedLabTimeSeries object
       label - cell array of marker prefixes (optional, default: all)
   Outputs:
       newThis - orientedLabTimeSeries with requested data
   See also: getOrientedData, getDataAsTS
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
getOrientedData getOrientedData Returns data as 3D tensor
orientedLabTimeSeries
This function is called by:
orientedLabTimeSeries
SOURCE CODE
function newThis = getDataAsOTS(this, label)
%getDataAsOTS  Returns subset as orientedLabTimeSeries
%
%   newThis = getDataAsOTS(this) returns all data as OTS
%
%   newThis = getDataAsOTS(this, label) returns data for specified
%   marker prefixes
%
%   Inputs:
%       this - orientedLabTimeSeries object
%       label - cell array of marker prefixes (optional, default: all)
%
%   Outputs:
%       newThis - orientedLabTimeSeries with requested data
%
%   See also: getOrientedData, getDataAsTS
if nargin < 2 || isempty(label)
    label = [];
end
[data, label] = getOrientedData(this, label);
data = permute(data, [1, 3, 2]);
newThis = orientedLabTimeSeries(data(:, :), this.Time(1), ...
    this.sampPeriod, ...
    orientedLabTimeSeries.addLabelSuffix(label), this.orientation);
end