Description of getDataAsTS
Home > labTools > classes > labTS > @orientedLabTimeSeries > getDataAsTS.m
getDataAsTS
PURPOSE
getDataAsTS Returns labTimeSeries (override)
SYNOPSIS
function [newTS, auxLabel] = getDataAsTS(this, label)
DESCRIPTION
getDataAsTS  Returns labTimeSeries (override)
   [newTS, auxLabel] = getDataAsTS(this, label) returns data as
   labTimeSeries
   Inputs:
       this - orientedLabTimeSeries object
       label - string or cell array of label(s) to extract
   Outputs:
       newTS - labTimeSeries with requested data
       auxLabel - cell array of labels
   Note: I think this is unnecessary - default behavior if function is
         not defined in inheriting class is to call the superclass'
         method
   See also: labTimeSeries/getDataAsTS, getDataAsOTS
CROSS-REFERENCE INFORMATION
This function calls:
getDataAsTS getDataAsTS Returns new labTimeSeries with given label(s)
labTimeSeries
getDataAsTS getDataAsTS Returns labTimeSeries (override)
getDataAsTS getDataAsTS Returns processedEMGTimeSeries with specified label(s)
This function is called by:
labTimeSeries
getDataAsTS getDataAsTS Returns labTimeSeries (override)
orientedLabTimeSeries
processedEMGTimeSeries
computeCOM COMPUTECOM Compute stride-by-stride COM kinematics relative to each ankle.
SOURCE CODE
function [newTS, auxLabel] = getDataAsTS(this, label)
%getDataAsTS  Returns labTimeSeries (override)
%
%   [newTS, auxLabel] = getDataAsTS(this, label) returns data as
%   labTimeSeries
%
%   Inputs:
%       this - orientedLabTimeSeries object
%       label - string or cell array of label(s) to extract
%
%   Outputs:
%       newTS - labTimeSeries with requested data
%       auxLabel - cell array of labels
%
%   Note: I think this is unnecessary - default behavior if function is
%         not defined in inheriting class is to call the superclass'
%         method
%
%   See also: labTimeSeries/getDataAsTS, getDataAsOTS
[newTS, auxLabel] = getDataAsTS@labTimeSeries(this, label);
end