Description of plus
Home > labTools > classes > labTS > @orientedLabTimeSeries > plus.m
plus
PURPOSE
plus Adds two OTS (override)
SYNOPSIS
function newThis = plus(this, other)
DESCRIPTION
plus  Adds two OTS (override)
   newThis = plus(this, other) adds and preserves orientedLabTimeSeries
   type with updated labels
   Inputs:
       this - orientedLabTimeSeries object
       other - orientedLabTimeSeries to add
   Outputs:
       newThis - sum as orientedLabTimeSeries
   See also: labTimeSeries/plus, minus, times
CROSS-REFERENCE INFORMATION
This function calls:
plus plus Adds two alignedTimeSeries
labTimeSeries
plus plus Adds two labTimeSeries
orientedLabTimeSeries
plus plus Adds two OTS (override)
This function is called by:
plotParamBarsByConditionsv2 TODO: this file should be updated to call upon plotGroupedBars
alignedTimeSeries
expandEventTimes expandEventTimes Computes sample times for all events
plotCheckerboard plotCheckerboard Displays data as heatmap
integrate integrate Numerical integration
labTimeSeries
getVirtualOTS getVirtualOTS Computes virtual markers from model
orientedLabTimeSeries
plus plus Adds two OTS (override)
translate translate Translates data by vector
computeCOP COMPUTECOP Compute bilateral center of pressure in lab coordinates.
figuresColorMap Colormap:
figuresColorMap Colormap:
SOURCE CODE
function newThis = plus(this, other)
%plus  Adds two OTS (override)
%
%   newThis = plus(this, other) adds and preserves orientedLabTimeSeries
%   type with updated labels
%
%   Inputs:
%       this - orientedLabTimeSeries object
%       other - orientedLabTimeSeries to add
%
%   Outputs:
%       newThis - sum as orientedLabTimeSeries
%
%   See also: labTimeSeries/plus, minus, times
newThis = plus@labTimeSeries(this, other);
tL = this.getLabelPrefix;
oL = other.getLabelPrefix;
newLabelPrefixes = cell(size(tL));
for i = 1:length(newLabelPrefixes)
    newLabelPrefixes{i} = ['(' tL{i} ' + ' oL{i} ')'];
end
newLabels = orientedLabTimeSeries.addLabelSuffix(newLabelPrefixes);
newThis = orientedLabTimeSeries(newThis.Data, newThis.Time(1), ...
    newThis.sampPeriod, newLabels, this.orientation);
end