Description of thresholdByChannel
Home > labTools > classes > labTS > @orientedLabTimeSeries > thresholdByChannel.m
thresholdByChannel
PURPOSE
thresholdByChannel Thresholds by channel (override)
SYNOPSIS
function newThis = thresholdByChannel(this, th, label, moreThanFlag)
DESCRIPTION
thresholdByChannel  Thresholds by channel (override)
   newThis = thresholdByChannel(this, th, label, moreThanFlag)
   thresholds and preserves orientedLabTimeSeries type
   Inputs:
       this - orientedLabTimeSeries object
       th - threshold value
       label - label to use for thresholding
       moreThanFlag - if 1, zeros when greater than threshold
                      (optional)
   Outputs:
       newThis - thresholded orientedLabTimeSeries
   See also: labTimeSeries/thresholdByChannel, threshold
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
labTimeSeries
thresholdByChannel thresholdByChannel Zeros data based on threshold
orientedLabTimeSeries
thresholdByChannel thresholdByChannel Thresholds by channel (override)
This function is called by:
labTimeSeries
orientedLabTimeSeries
thresholdByChannel thresholdByChannel Thresholds by channel (override)
SOURCE CODE
function newThis = thresholdByChannel(this, th, label, moreThanFlag)
%thresholdByChannel  Thresholds by channel (override)
%
%   newThis = thresholdByChannel(this, th, label, moreThanFlag)
%   thresholds and preserves orientedLabTimeSeries type
%
%   Inputs:
%       this - orientedLabTimeSeries object
%       th - threshold value
%       label - label to use for thresholding
%       moreThanFlag - if 1, zeros when greater than threshold
%                      (optional)
%
%   Outputs:
%       newThis - thresholded orientedLabTimeSeries
%
%   See also: labTimeSeries/thresholdByChannel, threshold
if nargin < 4 || isempty(moreThanFlag)
    moreThanFlag = [];
end
newThis = thresholdByChannel@labTimeSeries(this, th, label, moreThanFlag);
newThis = orientedLabTimeSeries(newThis.Data, this.Time(1), ...
    this.sampPeriod, this.labels, this.orientation);
end