Description of threshold
Home > labTools > classes > labTS > @orientedLabTimeSeries > threshold.m
threshold
PURPOSE
threshold Thresholds by vector magnitude
SYNOPSIS
function newThis = threshold(this, th)
DESCRIPTION
threshold  Thresholds by vector magnitude
   newThis = threshold(this, th) zeros samples where vector magnitude
   is below threshold
   Inputs:
       this - orientedLabTimeSeries object
       th - magnitude threshold value
   Outputs:
       newThis - thresholded orientedLabTimeSeries
   See also: thresholdByChannel
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
orientedLabTimeSeries
interpolTraj %INTERPOLTRAJ Interpolates trajectories to fill in marker gaps
getStanceFromForces GETSTANCEFROMFORCES Estimate stance phase from vertical ground reaction force.
markerModel
syncEMGData SYNCEMGDATA Synchronize two-PC EMG recordings to a reference signal.
SOURCE CODE
function newThis = threshold(this, th)
%threshold  Thresholds by vector magnitude
%
%   newThis = threshold(this, th) zeros samples where vector magnitude
%   is below threshold
%
%   Inputs:
%       this - orientedLabTimeSeries object
%       th - magnitude threshold value
%
%   Outputs:
%       newThis - thresholded orientedLabTimeSeries
%
%   See also: thresholdByChannel
newThis = this;
newThis.Data(sqrt(sum(newThis.Data.^2)) < th, :) = 0;
end