Description of times
Home > labTools > classes > labTS > @orientedLabTimeSeries > times.m
times
PURPOSE
times Multiplies by constant (override)
SYNOPSIS
function newThis = times(this, constant)
DESCRIPTION
times  Multiplies by constant (override)
   newThis = times(this, constant) multiplies and preserves
   orientedLabTimeSeries type
   Inputs:
       this - orientedLabTimeSeries object
       constant - scalar or array to multiply by
   Outputs:
       newThis - scaled orientedLabTimeSeries
   See also: labTimeSeries/times, plus
CROSS-REFERENCE INFORMATION
This function calls:
times times Multiplies by constant
labTimeSeries
times times Multiplies data by constant
times times Multiplies by constant (override)
This function is called by:
plotGroupedSubjectsBars
mergeHemiCOPs mergeHemiCOPs Merges left and right center of pressure data
alignedTimeSeries
plotCheckerboard plotCheckerboard Displays data as heatmap
labTimeSeries
getVirtualOTS getVirtualOTS Computes virtual markers from model
orientedLabTimeSeries
rotate rotate Rotates data by matrix
times times Multiplies by constant (override)
parameterSeries
extractStimArtifactIndsFromTrigger EXTRACTSTIMARTIFACTINDSFROMTRIGGER Extract TAP stim artifact peak indices.
plotSnippets PLOTSNIPPETS Plot H-reflex snippets with GRFs if available.
plotStimArtifactPeaks PLOTSTIMARTIFACTPEAKS Plot stimulation artifact peaks in proximal TA
TrajCheckOnePipeline
btkEmulateC3Dserver BTKEMULATEC3DSERVER Creates an emulated COM object for C3Dserver.
TrajCheckOtherPipeline
PlotHelper PLOTHELPER helper function with static functions to make common plots
generateHreflexRecruitmentCurves % Generate H-Reflex Calibration Recruitment Curves & Other Figures
calcParameters CALCPARAMETERS Compute stride-by-stride parameters for analysis.
computeCOP COMPUTECOP Compute bilateral center of pressure in lab coordinates.
computeHreflexParameters COMPUTEHREFLEXPARAMETERS Compute stride-by-stride H-reflex parameters.
extractKinematicDataAtEvents EXTRACTKINEMATICDATAATEVENTS Extract markers and angles at gait event times.
getKinematicData GETKINEMATICDATA Extract marker and angle data at gait event times.
getKinematicDataAbs GETKINEMATICDATAABS Extract marker data in absolute lab-frame coordinates.
figuresColorMap Colormap:
figuresColorMap Colormap:
ReviewEventsGUI REVIEWEVENTSGUI Plot and edit gait events in an experimentData object.
SOURCE CODE
function newThis = times(this, constant)
%times  Multiplies by constant (override)
%
%   newThis = times(this, constant) multiplies and preserves
%   orientedLabTimeSeries type
%
%   Inputs:
%       this - orientedLabTimeSeries object
%       constant - scalar or array to multiply by
%
%   Outputs:
%       newThis - scaled orientedLabTimeSeries
%
%   See also: labTimeSeries/times, plus
newThis = times@labTimeSeries(this, constant);
newThis = newThis.castAsOTS(this.orientation);
end