Description of appendData
Home > labTools > classes > labTS > @parameterSeries > appendData.m
appendData
PURPOSE
appendData Appends new parameters
SYNOPSIS
function newThis = appendData(this, newData, newLabels, newDesc)
DESCRIPTION
appendData  Appends new parameters
   newThis = appendData(this, newData, newLabels) appends new
   parameters without descriptions
   newThis = appendData(this, newData, newLabels, newDesc) appends
   with descriptions
   Inputs:
       this - parameterSeries object
       newData - matrix of new parameter values (same number of rows)
       newLabels - cell array of labels for new parameters
       newDesc - cell array of descriptions (optional)
   Outputs:
       newThis - parameterSeries with appended parameters
   Note: For backward compatibility
   See also: cat, addNewParameter
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
cat cat Concatenates alignedTimeSeries
cat cat Concatenates (override)
cat cat Concatenates two parameterSeries
parameterSeries
This function is called by:
paramData
addNewParameter addNewParameter Adds computed parameter from existing data
labTimeSeries
addNewParameter addNewParameter Computes and adds new parameter from existing parameters
linearStretch linearStretch Linearly transforms parameter values
parameterSeries
appendBodyCOM APPENDBODYCOM Approximate whole-body center of mass from marker data.
SOURCE CODE
function newThis = appendData(this, newData, newLabels, newDesc)
%appendData  Appends new parameters
%
%   newThis = appendData(this, newData, newLabels) appends new
%   parameters without descriptions
%
%   newThis = appendData(this, newData, newLabels, newDesc) appends
%   with descriptions
%
%   Inputs:
%       this - parameterSeries object
%       newData - matrix of new parameter values (same number of rows)
%       newLabels - cell array of labels for new parameters
%       newDesc - cell array of descriptions (optional)
%
%   Outputs:
%       newThis - parameterSeries with appended parameters
%
%   Note: For backward compatibility
%
%   See also: cat, addNewParameter
if nargin < 4 || isempty(newDesc)
    newDesc = cell(size(newLabels));
end
other = parameterSeries(...
    newData, newLabels, this.hiddenTime, newDesc, this.trialTypes);
newThis = cat(this, other);
end