Description of polyfit1PCA
Home > labTools > fun > ext > pitools > signalProcessing > polyfit1PCA.m
polyfit1PCA
PURPOSE
Finding best-fit line through PCA
SYNOPSIS
function [pp] = polyfit1PCA(x,y,varNormalizeFlag)
DESCRIPTION
Finding best-fit line through PCA
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
mean mean Computes mean across strides
std std Computes standard deviation
This function is called by:
groupAdaptationData
SOURCE CODE
function [pp] = polyfit1PCA(x,y,varNormalizeFlag)
%Finding best-fit line through PCA
my=mean(y);
y=y(:)'-my;
mx=mean(x);
x=x(:)'-mx;
if nargin>2 && ~isempty(varNormalizeFlag) && varNormalizeFlag==1
  vx=std(x);
  vy=std(y);
else
  vx=1;
  vy=1;
end
[ppp,ccc,aaa]=pca([x/vx; y/vy],'Centered',false);
ccc=ccc(:,1);
pp(1)=ccc(2)*vy/(ccc(1)*vx);
pp(2)=my-mx*pp(1);
end