Description of isempty
Home > labTools > classes > auxData > @labDate > isempty.m
isempty
PURPOSE
isempty Checks if the date equals the default value.
SYNOPSIS
function flag = isempty(this)
DESCRIPTION
 isempty  Checks if the date equals the default value.
   Determines whether the date equals the default sentinel
 date (Jan 1, 1900), which is used to represent an
 uninitialized labDate.
   Inputs:
     this - labDate object
   Outputs:
     flag - true if date equals default value, else false
   See also: default, timeSince
CROSS-REFERENCE INFORMATION
This function calls:
timeSince timeSince Calculates elapsed time from another date.
This function is called by:
BiofeedbackPerception
BiofeedbackSL
BiofeedbackSLBF_Percp
BiofeedbackSL_c3d
BiofeedbackVazE2B
SombricTaiChi
getScore getScore Retrieves scores for specified test(s)
labDate
subjectData
Correlations Set colors order
adaptationData
getBaseConditions
getBaseData Returns data from last 40 strides of baseline, exempting the last 5.
getEarlyLateData_v2 obtain the earliest and late data points for conditions
getEarlyLateData_v2_ obtain the earliest and late data points for conditions
getEarlyLateIdxs obtain the earliest and late data points for conditions
plotAvgTimeCourse adaptDataList must be cell array of 'param.mat' file names
plotGroupedSubjectsBars
plotGroupedSubjectsBarsv2
plotGroupedSubjectsTimeCourse
plotParamBarsByConditions
plotParamBarsByConditionsv2 TODO: this file should be updated to call upon plotGroupedBars
removeBiasV2
removeBiasV3 removeBias('condition') or removeBias({'Condition1','Condition2',...})
removeBiasV4 removeBias('condition') or removeBias({'Condition1','Condition2',...})
scatterPlotLab Plots up to 3 parameters as coordinates in a single cartesian axes system
checkMarkerHealth checkMarkerHealth Validates marker data quality
computeAngles computeAngles Calculates joint angles for all trials
experimentData
extractMarkerModels extractMarkerModels Builds marker position models from data
flushAndRecomputeParameters FLUSHANDRECOMPUTEPARAMETERS Discard existing parameters and recompute all.
getAlignedField getAlignedField Extracts time-aligned field data across
getRefLeg getRefLeg Returns reference leg for parameter computations
getStrideInfo getStrideInfo Returns stride timing information
getStridedField getStridedField Extracts stride-segmented field data across
getSubjectAgeAtExperimentDate getSubjectAgeAtExperimentDate Computes subject age at experiment time
makeDataObjNew makeDataObjNew Internal method to create adaptationData object
parameterEvolutionPlot parameterEvolutionPlot Plots parameter evolution across conditions
parameterTimeCourse parameterTimeCourse Plots parameter time course
process process Processes raw data for all trials in the experimental session.
recomputeParameters RECOMPUTEPARAMETERS Recalculate stride-by-stride adaptation parameters.
reduce reduce Creates reducedLabData for all trials
splitIntoStrides splitIntoStrides Separates trials into individual strides
groupAdaptationData
plotBars TODO: Should check that numberOfStrides groups are given in
plotMultipleEpochBars This function replaces plotMultipleGroupBars
plotMultipleGroupsBars
calcLimbAngles calcLimbAngles Calculates limb and joint angles from marker data.
computeCOPAlt computeCOPAlt Alternative method to compute center of pressure
computeHemiCOP computeHemiCOP Computes center of pressure for one leg
computeTorques computeTorques Computes joint torques from kinematics and kinetics
getBeltSpeedsFromFootMarkers
getEvents GETEVENTS Extract gait events from a raw trial, selecting the appropriate
getPartialData getPartialData Returns requested data from specified field
labData
process process Processes raw trial data to compute angles, gait events,
processEMG processEMG Extracts processed and filtered EMG amplitude envelopes
getStepInfo getStepInfo Returns step count and timing information
getStrideInfo getStrideInfo Returns stride count and timing information
processedLabData
reduce reduce Aligns and resamples all timeseries to the same indexes and puts
rawTrialData
plotCell plotCell Plots cell array of stride data
plotCellAvg plotCellAvg Plots average and std of stride cell array
strideData
plotAllStrides plotAllStrides Plots all individual strides for a field
plotAvgStride plotAvgStride Plots average stride across conditions
checkConditionOrder checkConditionOrder Checks that conditions appear in order
experimentMetaData
getCondLstPerTrial getCondLstPerTrial Returns list of condition numbers for each trial
getConditionIdxsFromName getConditionIdxsFromName Returns condition indices from names
getConditionsThatMatch getConditionsThatMatch Returns condition names matching pattern
getConditionsThatMatchV2 getConditionsThatMatchV2 Returns condition names matching pattern
processedTrialData
alignedTimeSeries
cat cat Concatenates alignedTimeSeries
discretize discretize Averages data across phases
fftshift fftshift Shifts alignment by half cycle
flipLR flipLR Flips left/right alignment
getLabelsThatMatch getLabelsThatMatch Finds labels matching pattern
getPartialStridesAsATS getPartialStridesAsATS Extracts subset of strides
iqr iqr Computes interquartile range
logicalHist logicalHist Generates histogram from logical event data
mean mean Computes mean across strides
median median Computes median
plot plot Plots aligned data with mean
prctile prctile Computes percentile
renameLabels renameLabels Renames labels
rescaleTime rescaleTime Redefines time vector
std std Computes standard deviation
stdRobust stdRobust Computes robust standard deviation
align align Aligns data to gait events
assessMissing assessMissing Assesses and plots missing data
bilateralPlot bilateralPlot Plots bilateral comparison
castAsOTS castAsOTS Converts to orientedLabTimeSeries
derivative derivative Numerical differentiation
discretize discretize Discretizes by averaging across phases
getArrayedEvents getArrayedEvents Extracts event times as array
getDataAsVector GETDATASVECTOR Extract data vectors for the specified label(s).
getLabelsThatMatch getLabelsThatMatch Returns labels matching regular expression
getSample getSample Samples timeseries at arbitrary timepoints
integrate integrate Numerical integration
labTimeSeries
monotonicFilter monotonicFilter Applies monotonic least squares
plot plot Plots data in subplots
renameLabels renameLabels Renames labels in timeseries
resample resample Resamples timeseries to different sampling period
resampleN resampleN Resamples to N samples over same time range
split split Returns timeseries between two timepoints
splitByEvents splitByEvents Separates by events in boolean timeseries
stridedTSToAlignedTS stridedTSToAlignedTS Converts strided TS to aligned TS
substituteNaNs substituteNaNs Replaces NaN by interpolation
thresholdByChannel thresholdByChannel Zeros data based on threshold
animate2 animate2 Creates animation with balloon model
assessMissing assessMissing Assesses missing data
buildNaiveDistancesModel buildNaiveDistancesModel Builds statistical marker model
computeDifferenceMatrix computeDifferenceMatrix Computes inter-marker differences
computeDifferenceOTS computeDifferenceOTS Difference matrix as OTS
computeDistanceMatrix computeDistanceMatrix Computes inter-marker distances
fillGaps fillGaps Fills missing marker data
findOutliers findOutliers Detects outliers using model
fixBadLabels fixBadLabels Detects and fixes label swaps
getDataAsOTS getDataAsOTS Returns subset as orientedLabTimeSeries
getOrientedData getOrientedData Returns data as 3D tensor
getVirtualOTS getVirtualOTS Computes virtual markers from model
orientedLabTimeSeries
plot3 plot3 Plots 3D trajectories
substituteNaNs substituteNaNs Fills NaN values (override)
thresholdByChannel thresholdByChannel Thresholds by channel (override)
addStrides addStrides Adds strides from another parameterSeries
anova anova Performs one-way ANOVA on parameters
appendData appendData Appends new parameters
cat cat Concatenates two parameterSeries
getDataAsPS getDataAsPS Extracts subset as new parameterSeries
indsInTrial indsInTrial Returns indices for specified trial(s)
linearStretch linearStretch Linearly transforms parameter values
substituteNaNs substituteNaNs Fills NaN values, preserving fixed params
plot PLOT Implementation for ClusteredSynergySetCollection
FactorizedMatrix
SynergyAnalysis
cluster CLUSTER Implementation of the cluster function for the class
TestPipelineRecompute TESTPIPELINERECOMPUTE Template script for regression-testing recompute pipelines.
computeAmplitudes COMPUTEAMPLITUDES Compute amplitudes of H-reflex components from EMG.
extractBackgroundEMG EXTRACTBACKGROUNDEMG Extract background EMG snippets before given indices.
extractSnippets EXTRACTSNIPPETS Extract H-reflex and optional GRF snippets for plotting.
extractStimArtifactIndsFromTrigger EXTRACTSTIMARTIFACTINDSFROMTRIGGER Extract TAP stim artifact peak indices.
fitCal FITCAL Fit M- and H-wave recruitment curves.
plotCal PLOTCAL Plot the H-reflex recruitment or ratio calibration curve.
plotNoiseHistogram PLOTNOISEHISTOGRAM Plot the noise amplitude distribution for the H-reflex.
plotSnippets PLOTSNIPPETS Plot H-reflex snippets with GRFs if available.
plotStimArtifactPeaks PLOTSTIMARTIFACTPEAKS Plot stimulation artifact peaks in proximal TA
processAndFillSmallMarkerGapsSession PROCESSANDFILLSMALLMARKERGAPSSESSION Process trial and fill small gaps
reconstructAndLabelSession RECONSTRUCTANDLABELSESSION Run reconstruct and label pipeline on session
reconstructAndLabelTrial RECONSTRUCTANDLABEL Run reconstruct and label pipeline on Vicon trial data
exportSessionToC3D EXPORTSESSIONTOC3D Saves specified trials in a session folder to C3D files
exportTrialToC3D EXPORTTRIALTOC3D Saves a trial as a C3D file with no additional processing
extractMarkerGapsTrial EXTRACTMARKERGAPSTRIAL Extract indices of all marker gaps to be filled
fillMarkerGapsPattern FILLMARKERGAPSPATTERN Fills marker gaps using reference marker pattern
fillSmallMarkerGapsSpline FILLSMALLMARKERGAPSSPLINE Fills small marker trajectory gaps via spline
interpolTraj %INTERPOLTRAJ Interpolates trajectories to fill in marker gaps
openTrialIfNeeded OPENTRIALIFNECESSARY Check if the trial is open, open if not, close others
processAndFillMarkerGapsSession PROCESSANDFILLMARKERGAPSSESSION Process trial and fill marker gaps
normalityTestWithFig Perform normality test on the data vector given using Shapiro-Wilk
AddPythonData Script to process a python biofeedback data file and add the columns of
SyncPython_forStatic function to incorporate biofeedback data from Python scripts into labtools
equalizeMuscleActivity
filterEMG
procEMGhealthCheck
rawEMGhealthCheck % Compute stats
getDataEMGtraces % get time series EMG data
plotEMGtraces % Plot the EMG ttraces for the Nimbus generalization project
SeparateConditions Chagingparams, create new conditions in 1 trial, currently only need to
CalcStrides2SS_PostAdapt this version was my first attempt to plot the postadaptation stuff,
SSTauPostAdapt %
COMCalculator COMCALCULATOR Compute segment center-of-mass time series from marker data.
TorqueCalculator TORQUECALCULATOR Calculate torque at each leg joint using inverse dynamics
TorqueCalculatorNew % Get Center of Mass Time Series (COMTS) data
defineEpochs defineEpochs is used to create a dataset object that defines relevant
deleteShortPhases DELETESHORTPHASES Remove stance or swing phases shorter than a minimum
getEventsFromAngles GETEVENTSFROMANGLES Detect gait events from limb angle data.
btkAppendForcePlatformType2 BTKAPPENDFORCEPLATFORMTYPE2 Append a virtual force platform of type 2.
btkEmulateC3Dserver BTKEMULATEC3DSERVER Creates an emulated COM object for C3Dserver.
markerModel
naiveDistances
getBestReconsFromZeroModel UNTITLED Summary of this function goes here
saveFig SAVEFIG Save figure as .fig, .eps, and .png in organised subdirectories.
estimateDopplerShift ESTIMATEDOPPLERSHIFT Estimate relative sampling-rate mismatch via STFT.
filtfilthd_short FILTFILTHD_SHORT Zero-phase filter with length-limited reflective padding.
findTemplate findTemplate implements a simple cross-correlation search to find for
polyfit1PCA Finding best-fit line through PCA
BenjaminiHochberg Performs the Benjamini-Hochberg procedure to determine significance in
xticklabel_rotate90_cell XTICKLABEL_ROTATE90 - Rotate numeric Xtick labels by 90 degrees
qualmetadata
swtest SWTEST Shapiro-Wilk parametric hypothesis test of composite normality.
tight_subplot tight_subplot creates "subplot" axes with adjustable gaps and margins
DetermineOptimalReconstructAndLabelParams % Determine the Optimal Reconstruct & Label Pipeline Parameters
DetermineOptimalReconstructAndLabelParamsTmp % Determine the Optimal Reconstruct & Label Pipeline Parameters
CompareTrajectory_RL
OptimizedReconstructAndLabel % Take 1 at Optimizing Reconstruct & Label Pipeline
Part1RL pathTrial = 'Z:\Nathan\ViconNexusReconstructAndLabel\Vicon\C3S24_S1\Trial16';
TrajectoryCheckOptimizedRL
processAndFillMarkerGapsTrial PROCESSANDFILLMARKERGAPSTRIAL Process a single trial and fill marker gaps
reconstructAndLabelSession RECONSTRUCTANDLABELSESSION Run reconstruct and label pipeline on session
reconstructAndLabelTrial RECONSTRUCTANDLABEL Run reconstruct and label pipeline on Vicon trial data
PlotHelper PLOTHELPER helper function with static functions to make common plots
SL_Realtime SL Realtime
SL_RealtimeAlpha SL Realtime
changeCondName Changes the condition names of a param file.
compareAdaptationData COMPAREADAPTATIONDATA Compare two adaptationData objects or params.mat files.
compareExperimentData COMPAREEXPERIMENTDATA Compare structure of two experimentData objects.
cprintf CPRINTF displays styled formatted text in the Command Window
generateHreflexRecruitmentCurves % Generate H-Reflex Calibration Recruitment Curves & Other Figures
getOGspeed must load subject before running function
getSimpleFileName
CalcStrides2SS this version was my first attempt to plot the readaptation stuff,
barGroups Make a bar plot to compare groups for a given epoch and parameter
binData BINDATA computes a running average
expResults % THIS FUNCTION IS OLD AND HAS BEEN REPLACED BY getResults !!!
getForceResults UNTITLED Summary of this function goes here
getResults define number of points to use for calculating values
getResultsBF
getResultsSMART define number of points to use for calculating values
makeSMatrix
makeSMatrixV2
smoothedMax SMOOTHEDMAX finds the maximum value of an N-pt running average
matchControlsFixedGUI matchControlsFixedGUI Fixed GUI to choose demographic matching factors
runAvg writen based on bin_dataV1 writen by GTO April 14th 2009
appendBodyCOM APPENDBODYCOM Approximate whole-body center of mass from marker data.
appendEMGNormParameters APPENDEMGNORMPARAMETERS Compute and append EMG norm parameters.
calcExperimentalParams CALCEXPERIMENTALPARAMS Compute experimental parameters per stride.
calcParameters CALCPARAMETERS Compute stride-by-stride parameters for analysis.
computeCOM COMPUTECOM Compute stride-by-stride COM kinematics relative to each ankle.
computeForceParameters COMPUTEFORCEPARAMETERS Compute kinetic treadmill parameters per stride.
computeForceParameters_OGFP COMPUTEFORCEPARAMETERS_OGFP Compute AP GRF parameters from overground force plates.
computeForceParameters_OGFP_aligned COMPUTEFORCEPARAMETERS_OGFP_ALIGNED Compute AP GRF parameters using stride-aligned force traces.
computeHreflexParameters COMPUTEHREFLEXPARAMETERS Compute stride-by-stride H-reflex parameters.
computeLegForceParameters COMPUTELEGFORCEPARAMETERS Compute AP force parameters for one leg stride.
computePercParameters COMPUTEPERCPARAMETERS Compute perceptual task parameters per stride.
computeSpatialParameters COMPUTESPATIALPARAMETERS Compute spatial parameters per stride.
computeTSDiscreteParameters COMPUTETSDISCRETEPARAMETERS Discretize time series into stride phases.
computeTSStatParameters COMPUTETSSTATPARAMETERS Compute summary statistics per stride.
getIndsForAllSteps GETINDSFORALLSTEPS Return event indices and times for all strides.
getIndsForThisStep GETINDSFORTHISSTEP Return event indices and times for one stride.
determineTMAngle DETERMINETMANGLE Extract treadmill incline angle from trial description.
extractKinematicDataAtEvents EXTRACTKINEMATICDATAATEVENTS Extract markers and angles at gait event times.
populateNewParamBackToExpData POPULATENEWPARAMBACKTOEXPDATA Back-populate new parameters into expData.
getNiceAxisLimits Similar to axis tight, but with pre-determined padding so no datapoints
optimizedSubPlot OPTIMIZEDSUBPLOT generates a full-screen figure of empty subplots that
prettyBarPlot Data is PxMxN, where:
reviseExperimentInfo REVISEEEXPERIMENTINFO Revise experimental session information in MAT files
uiCreateStudy UICREATESTUDY GUI for assembling groups of subjects into a study.
PlotParamsGUI PLOTPARAMSGUI GUI for configuring and launching adaptation parameter plots.
ReviewEventsGUI REVIEWEVENTSGUI Plot and edit gait events in an experimentData object.
GetInfoGUI GetInfoGUI GUI for collecting experimental session information.
SepCondsInExpByAudioCue Separate 1 condition into multiple in expData using timing information from audioCue.
autoRenameDatlog autoRenameDatlog using timestamps and trial names from .x1d files in the viconDataFolder
c3d2mat c3d2mat Main script for parsing C3D session files into a MAT file.
GetInfoGUIbeta GETINFOGUIBETA MATLAB code for GetInfoGUIbeta.fig
c3d2matbeta c3d2mat -- The main script for parsing C3D session files into a MAT file.
errorProofInfobeta Checks feilds of GetInfoGUI to ensure entry is valid and reasonable.
errorProofInfo errorProofInfo Validates and extracts all fields from GetInfoGUI.
getEMGworksdata get EMG from EMGworks
getEMGworksdataAcc GETEMGWORKSDATAACC retrieve accelerometer data from 'EMGworks' software
getTrialMetaData getTrialMetaData creates trialMetaData object for each trial of experiment
loadSubject loadSubject Load, organize, process, and save experimental session
loadTrials loadTrials Generates rawTrialData instances for each trial.
processGRFData PROCESSGRFDATA Load and calibrate ground reaction force data from C3D.
syncEMGData SYNCEMGDATA Synchronize two-PC EMG recordings to a reference signal.
SOURCE CODE
function flag = isempty(this)
% isempty  Checks if the date equals the default value.
%
%   Determines whether the date equals the default sentinel
% date (Jan 1, 1900), which is used to represent an
% uninitialized labDate.
%
%   Inputs:
%     this - labDate object
%
%   Outputs:
%     flag - true if date equals default value, else false
%
%   See also: default, timeSince
flag = timeSince(this, labDate.default()) == 0;
end