Description of castAsOTS
Home > labTools > classes > labTS > @labTimeSeries > castAsOTS.m
castAsOTS
PURPOSE
castAsOTS Converts to orientedLabTimeSeries
SYNOPSIS
function newThis = castAsOTS(this, orientation)
DESCRIPTION
castAsOTS  Converts to orientedLabTimeSeries
   newThis = castAsOTS(this) converts to orientedLabTimeSeries with
   default orientation
   newThis = castAsOTS(this, orientation) uses specified orientation
   Inputs:
       this - labTimeSeries object
       orientation - orientationInfo object (optional)
   Outputs:
       newThis - orientedLabTimeSeries object
   See also: orientedLabTimeSeries, castAsSTS
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
orientedLabTimeSeries
orientationInfo
This function is called by:
labTimeSeries
SOURCE CODE
function newThis = castAsOTS(this, orientation)
%castAsOTS  Converts to orientedLabTimeSeries
%
%   newThis = castAsOTS(this) converts to orientedLabTimeSeries with
%   default orientation
%
%   newThis = castAsOTS(this, orientation) uses specified orientation
%
%   Inputs:
%       this - labTimeSeries object
%       orientation - orientationInfo object (optional)
%
%   Outputs:
%       newThis - orientedLabTimeSeries object
%
%   See also: orientedLabTimeSeries, castAsSTS
if nargin < 2 || isempty(orientation)
    orientation = orientationInfo;
end
newThis = orientedLabTimeSeries(...
    this.Data, this.Time(1), this.sampPeriod, this.labels, orientation);
end