Description of getPartialDataAsVector
Home > labTools > classes > labTS > @labTimeSeries > getPartialDataAsVector.m
getPartialDataAsVector
PURPOSE
getPartialDataAsVector Returns data for labels and time range
SYNOPSIS
function [data, time, auxLabel] =getPartialDataAsVector(this, label, t0, t1)
DESCRIPTION
getPartialDataAsVector  Returns data for labels and time range
   [data, time, auxLabel] = getPartialDataAsVector(this, label, t0,
   t1) extracts data for specified labels within time range [t0, t1)
   Inputs:
       this - labTimeSeries object
       label - string or cell array of label(s)
       t0 - start time
       t1 - end time
   Outputs:
       data - data matrix for requested labels and time range
       time - time vector
       auxLabel - cell array of labels
   See also: getDataAsVector, split
CROSS-REFERENCE INFORMATION
This function calls:
split split Splits data into time-delimited segments
getDataAsVector GETDATASVECTOR Extract data vectors for the specified label(s).
split split Returns timeseries between two timepoints
split split Splits timeseries (override)
split split Splits timeseries, preserving processing info
This function is called by:
labTimeSeries
SOURCE CODE
function [data, time, auxLabel] = ...
    getPartialDataAsVector(this, label, t0, t1)
%getPartialDataAsVector  Returns data for labels and time range
%
%   [data, time, auxLabel] = getPartialDataAsVector(this, label, t0,
%   t1) extracts data for specified labels within time range [t0, t1)
%
%   Inputs:
%       this - labTimeSeries object
%       label - string or cell array of label(s)
%       t0 - start time
%       t1 - end time
%
%   Outputs:
%       data - data matrix for requested labels and time range
%       time - time vector
%       auxLabel - cell array of labels
%
%   See also: getDataAsVector, split
newThis = split(this.getDataAsTS(label), t0, t1);
[data, time, auxLabel] = getDataAsVector(newThis, label);
end