Description of lowPassFilter
Home > labTools > classes > labTS > @labTimeSeries > lowPassFilter.m
lowPassFilter
PURPOSE
lowPassFilter Applies low-pass filter
SYNOPSIS
function newThis = lowPassFilter(this, fcut)
DESCRIPTION
lowPassFilter  Applies low-pass filter
   newThis = lowPassFilter(this, fcut) applies Butterworth low-pass
   filter with specified cutoff frequency
   Inputs:
       this - labTimeSeries object
       fcut - cutoff frequency in Hz
   Outputs:
       newThis - filtered labTimeSeries
   See also: highPassFilter, medianFilter, filtfilthd_short
CROSS-REFERENCE INFORMATION
This function calls:
labTimeSeries
lowPassFilter lowPassFilter Applies low-pass filter
lowPassFilter lowPassFilter Applies low-pass filter (override)
filtfilthd_short FILTFILTHD_SHORT Zero-phase filter with length-limited reflective padding.
This function is called by:
labTimeSeries
lowPassFilter lowPassFilter Applies low-pass filter
lowPassFilter lowPassFilter Applies low-pass filter (override)
orientedLabTimeSeries
filterEMG
amp_estim Estimation of amplitude of a given EMG signal (envelope detection).
SOURCE CODE
function newThis = lowPassFilter(this, fcut)
%lowPassFilter  Applies low-pass filter
%
%   newThis = lowPassFilter(this, fcut) applies Butterworth low-pass
%   filter with specified cutoff frequency
%
%   Inputs:
%       this - labTimeSeries object
%       fcut - cutoff frequency in Hz
%
%   Outputs:
%       newThis - filtered labTimeSeries
%
%   See also: highPassFilter, medianFilter, filtfilthd_short
Wn = fcut * 2 / this.sampFreq;
Wst = min([2 * Wn, Wn + 0.2 * (1 - Wn)]);
filterList{1} = fdesign.lowpass('Fp,Fst,Ap,Ast', Wn, Wst, 3, 10);
lowPassFilter = design(filterList{1}, 'butter');
newData = ...
    filtfilthd_short(lowPassFilter, this.Data, 'reflect', this.sampFreq);
newThis = ...
    labTimeSeries(newData, this.Time(1), this.sampPeriod, this.labels);
if ~isfield(this.UserData, 'processingInfo')
    this.UserData.processingInfo = {};
end
newThis.UserData = this.UserData;
newThis.UserData.processingInfo{end + 1} = filterList{1};
end