Description of plotStridedTimeSeries
Home > labTools > classes > labTS > @labTimeSeries > plotStridedTimeSeries.m
plotStridedTimeSeries
PURPOSE
plotStridedTimeSeries Plots strided timeseries
SYNOPSIS
function [figHandle, plotHandles] = plotStridedTimeSeries(stridedTS, figHandle, plotHandles)
DESCRIPTION
plotStridedTimeSeries  Plots strided timeseries
   [figHandle, plotHandles] = plotStridedTimeSeries(stridedTS) plots
   strided timeseries data
   [figHandle, plotHandles] = plotStridedTimeSeries(stridedTS,
   figHandle, plotHandles) uses existing handles
   Inputs:
       stridedTS - cell array of strided timeseries
       figHandle - figure handle (optional)
       plotHandles - subplot handles (optional)
   Outputs:
       figHandle - figure handle
       plotHandles - array of subplot handles
   See also: plot, stridedTSToAlignedTS, alignedTimeSeries/plot
CROSS-REFERENCE INFORMATION
This function calls:
plot plot Plots aligned data with mean
plot plot Plots data in subplots
plot PLOT Implementation for ClusteredSynergySetCollection
plot PLOT Implementation of the plot method for SynergySetCollections
This function is called by:
labTimeSeries
SOURCE CODE
function [figHandle, plotHandles] = plotStridedTimeSeries(...
    stridedTS, figHandle, plotHandles)
%plotStridedTimeSeries  Plots strided timeseries
%
%   [figHandle, plotHandles] = plotStridedTimeSeries(stridedTS) plots
%   strided timeseries data
%
%   [figHandle, plotHandles] = plotStridedTimeSeries(stridedTS,
%   figHandle, plotHandles) uses existing handles
%
%   Inputs:
%       stridedTS - cell array of strided timeseries
%       figHandle - figure handle (optional)
%       plotHandles - subplot handles (optional)
%
%   Outputs:
%       figHandle - figure handle
%       plotHandles - array of subplot handles
%
%   See also: plot, stridedTSToAlignedTS, alignedTimeSeries/plot
if nargin < 2
    figHandle = [];
end
if nargin < 3
    plotHandles = [];
end
N = 2^ceil(log2(1.5 / stridedTS{1}.sampPeriod));
structure = labTimeSeries.stridedTSToAlignedTS(stridedTS, N);
% Using the alignedTimeSeries plot function
[figHandle, plotHandles] = plot(structure, figHandle, plotHandles);
end