Description of renameLabels
Home > labTools > classes > labTS > @labTimeSeries > renameLabels.m
renameLabels
PURPOSE
renameLabels Renames labels in timeseries
SYNOPSIS
function this = renameLabels(this, originalLabels, newLabels)
DESCRIPTION
renameLabels  Renames labels in timeseries
   this = renameLabels(this, originalLabels, newLabels) renames
   specified labels
   Inputs:
       this - labTimeSeries object
       originalLabels - cell array of labels to rename (empty for all)
       newLabels - cell array of new label names
   Outputs:
       this - labTimeSeries with renamed labels
   Note: You should not be renaming labels. You have been warned.
   See also: getLabels
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
This function is called by:
alignedTimeSeries
labTimeSeries
SOURCE CODE
function this = renameLabels(this, originalLabels, newLabels)
%renameLabels  Renames labels in timeseries
%
%   this = renameLabels(this, originalLabels, newLabels) renames
%   specified labels
%
%   Inputs:
%       this - labTimeSeries object
%       originalLabels - cell array of labels to rename (empty for all)
%       newLabels - cell array of new label names
%
%   Outputs:
%       this - labTimeSeries with renamed labels
%
%   Note: You should not be renaming labels. You have been warned.
%
%   See also: getLabels
warning('labTS:renameLabels:dont', ...
    'You should not be renaming the labels. You have been warned.');
if isempty(originalLabels)
    originalLabels = this.labels;
end
if size(newLabels) ~= size(originalLabels)
    error('labTS:renameLabels', 'Inconsistent label sizes');
end
[boo, idx] = this.isaLabel(originalLabels);
this.labels(idx(boo)) = newLabels(boo);
end