Description of getEarlyLateData_v2
Home > classes > dataStructs > @adaptationData > getEarlyLateData_v2.m
getEarlyLateData_v2
PURPOSE
obtain the earliest and late data points for conditions
SYNOPSIS
function [dataPoints]=getEarlyLateData_v2(this,labels,conds,removeBiasFlag,numberOfStrides,exemptLast,exemptFirst,padWithNaNFlag)
DESCRIPTION
obtain the earliest and late data points for conditions
allow to eliminate very late data points
Predefine values:
earlyNumber=5
latePoints=20
exemptLast=5
exemptFirst=0
INPUTS:
this:experimentData object
labels: parameters to plot
conds: condition that information is needed
removeBiasFlag:1 to activate function to remove bias, 0 or empty to no activate function
numberOfStrides: vector of any size, specifying how many stride
cycles to group. Positive values are interpreted as 'first N'
strides, while negative values are interpreted as 'last N'. Zero
values create an empty group
OUTPUTS:
dataPoints: cell array with the requested data.
EX:[veryEarlyPoints,earlyPoints,latePoints]=adaptData.getEarlyLateData({'Sout'},{'TM base'},1,5,40,5);
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
adaptationData
getBaseData Returns data from last 40 strides of baseline, exempting the last 5.
plotParamBarsByConditionsv2 TODO: this file should be updated to call upon plotGroupedBars
removeBiasV3 removeBias('condition') or removeBias({'Condition1','Condition2',...})
removeBiasV4 removeBias('condition') or removeBias({'Condition1','Condition2',...})
SOURCE CODE
function [dataPoints]=getEarlyLateData_v2(this,labels,conds,removeBiasFlag,numberOfStrides,exemptLast,exemptFirst,padWithNaNFlag)
        %obtain the earliest and late data points for conditions
        %allow to eliminate very late data points
        %Predefine values:
        %earlyNumber=5
        %latePoints=20
        %exemptLast=5
        %exemptFirst=0
        %
        %INPUTS:
        %this:experimentData object
        %labels: parameters to plot
        %conds: condition that information is needed
        %removeBiasFlag:1 to activate function to remove bias, 0 or empty to no activate function
        %numberOfStrides: vector of any size, specifying how many stride
        %cycles to group. Positive values are interpreted as 'first N'
        %strides, while negative values are interpreted as 'last N'. Zero
        %values create an empty group
        %OUTPUTS:
        %dataPoints: cell array with the requested data.
        %
        %EX:[veryEarlyPoints,earlyPoints,latePoints]=adaptData.getEarlyLateData({'Sout'},{'TM base'},1,5,40,5);
            if isa(conds,'char')
                conds={conds};
            elseif ~isa(conds,'cell') || ~all(cellfun(@(x) (isa(x,'char') || isa(x,'cell')),conds))
                error('adaptationData:getEarlyLateData','Conditions must be a string or a cell array containing strings.');
            end
            if nargin<2
                labels=[]; %Empty labels interpreted as ALL labels down-stream
            elseif ~isempty(labels) && ( ~(isa(labels,'char') || (isa(labels,'cell') && all(cellfun(@(x) isa(x,'char'),labels)) )))
                error('adaptationData:getEarlyLateData','Labels must be a string or a cell array containing strings.')
            end
            if nargin<5 || isempty(numberOfStrides)
                numberOfStrides=[5,-20]; %First 5 and last 20
            end
            if nargin<6 || isempty(exemptLast)
                Ne=5;
            else
                Ne=exemptLast;
            end
            if nargin<7 || isempty(exemptFirst)
                Nf=0;
            else
                Nf=exemptFirst;
            end
            if nargin<4 || isempty(removeBiasFlag)
                removeBiasFlag=1; %Default, bias removal
            else
                %this=adaptData;
            end
            if nargin<8
                padWithNaNFlag=false;
            end
            %this=this.removeBadStrides; %Should this be default? Pablo: I don't think we should be changing the # of strides in the middle of a request for data.
            [inds]=this.getEarlyLateIdxs(conds,numberOfStrides,Ne,Nf);
            switch removeBiasFlag
                case 1
                    this=this.removeBias;
                case 2
                    this=this.normalizeBias;
                case 0
                    %nop
                otherwise
                    error('Unexpected value for removeBiasFlag')
            end
            dataPoints=this.getDataFromInds(inds,labels,padWithNaNFlag);
        end