Description of alignedTimeSeries
Home > labTools > classes > labTS > @alignedTimeSeries > alignedTimeSeries.m
alignedTimeSeries
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
isaLabel isaLabel Checks if label(s) exist in dataset
isempty isempty Checks if the date equals the default value.
isaLabel isaLabel Checks if label(s) exist in dataset
alignedTimeSeries
castAsTS castAsTS Converts to labTimeSeries
cat cat Concatenates alignedTimeSeries
catStrides catStrides Concatenates strides into labTimeSeries
concatenateAsTS concatenateAsTS Concatenates strides sequentially
demean demean Removes mean
discretize discretize Averages data across phases
energyDecomposition energyDecomposition Decomposes variance
equalizeEnergyPerChannel equalizeEnergyPerChannel Normalizes by RMS
expandEventTimes expandEventTimes Computes sample times for all events
fftshift fftshift Shifts alignment by half cycle
flipLR flipLR Flips left/right alignment
getLabelsThatMatch getLabelsThatMatch Finds labels matching pattern
getPartialDataAsATS getPartialDataAsATS Extracts subset of channels
getPartialStridesAsATS getPartialStridesAsATS Extracts subset of strides
getSym getSym Computes symmetric components
getaSym getaSym Computes asymmetric components
iqr iqr Computes interquartile range
isaLabel isaLabel Checks if labels exist
logicalHist logicalHist Generates histogram from logical event data
mean mean Computes mean across strides
median median Computes median
minus minus Subtracts two alignedTimeSeries
plot plot Plots aligned data with mean
plotCheckerboard plotCheckerboard Displays data as heatmap
plus plus Adds two alignedTimeSeries
prctile prctile Computes percentile
removeStridesWithNaNs removeStridesWithNaNs Removes strides with missing data
renameLabels renameLabels Renames labels
rescaleTime rescaleTime Redefines time vector
std std Computes standard deviation
stdRobust stdRobust Computes robust standard deviation
times times Multiplies by constant
demean demean Removes mean from each channel
discretize discretize Discretizes by averaging across phases
equalizeEnergyPerChannel equalizeEnergyPerChannel Normalizes by RMS
getLabelsThatMatch getLabelsThatMatch Returns labels matching regular expression
isaLabel isaLabel Checks if string is contained in label array
minus minus Subtracts two labTimeSeries
plot plot Plots data in subplots
plus plus Adds two labTimeSeries
renameLabels renameLabels Renames labels in timeseries
times times Multiplies data by constant
cat cat Concatenates (override)
plus plus Adds two OTS (override)
times times Multiplies by constant (override)
cat cat Concatenates two parameterSeries
plot PLOT Implementation for ClusteredSynergySetCollection
plot PLOT Implementation of the plot method for SynergySetCollections
demean DEMEAN Remove the column-wise mean from a matrix.
tight_subplot tight_subplot creates "subplot" axes with adjustable gaps and margins
getFigStruct UNTITLED Calculate best subfigure divide (a x b) for showing N graphs
This function is called by:
groupAdaptationData
alignedTimeSeries
cat cat Concatenates alignedTimeSeries
discretize discretize Averages data across phases
getPartialStridesAsATS getPartialStridesAsATS Extracts subset of strides
mean mean Computes mean across strides
prctile prctile Computes percentile
rescaleTime rescaleTime Redefines time vector
std std Computes standard deviation
align_v2 align_v2 Efficient and robust alignment to events
discretize discretize Discretizes by averaging across phases
stridedTSToAlignedTS stridedTSToAlignedTS Converts strided TS to aligned TS
SUBFUNCTIONS
function this = alignedTimeSeries(t0, Ts, Data, labels,
function eET = get.expandedEventTimes(this)
function this = set.eventTimes(this, eventTimes)
function newThis = abs(this)
function [figHandle,plotHandles,plottedInds]=plot(this,figHandle,plotHandles,meanColor,events,individualLineStyle,plottedInds,bounds,medianFlag)
SOURCE CODE
classdef alignedTimeSeries % < labTimeSeries
    % TODO: make this inherit from labTimeSeries, as it should
    %alignedTimeSeries  Time-series-like object for aligned/repeated data
    %
    %   alignedTimeSeries stores multiple repetitions of recorded data
    %   aligned to common events (e.g., gait cycles aligned to heel
    %   strikes). Data is organized as (samples x channels x repetitions).
    %
    %alignedTimeSeries properties:
    %   Data - 3D matrix (samples x channels x strides)
    %   Time - time vector for one stride cycle
    %   labels - cell array of channel labels
    %   alignmentVector - vector specifying samples per phase
    %   alignmentLabels - cell array of phase/event labels
    %   eventTimes - matrix of actual event times (events x strides+1)
    %   expandedEventTimes - sample times for all events (dependent)
    %
    %alignedTimeSeries methods:
    %   alignedTimeSeries - constructor
    %   getPartialStridesAsATS - extracts subset of strides
    %   removeStridesWithNaNs - removes strides with missing data
    %   getPartialDataAsATS - extracts subset of channels
    %   mean - computes mean across strides
    %   std - computes standard deviation
    %   iqr - computes interquartile range
    %   stdRobust - computes robust standard deviation
    %   prctile - computes percentile
    %   median - computes median
    %   energyDecomposition - decomposes variance
    %   abs - takes absolute value
    %   equalizeEnergyPerChannel - normalizes by RMS
    %   demean - removes mean
    %   minus - subtracts two alignedTimeSeries
    %   plus - adds two alignedTimeSeries
    %   times - multiplies by constant
    %   catStrides - concatenates strides into labTimeSeries
    %   castAsTS - converts to labTimeSeries
    %   concatenateAsTS - concatenates strides sequentially
    %   isaLabel - checks if labels exist
    %   getLabelsThatMatch - finds labels matching pattern
    %   renameLabels - renames labels
    %   cat - concatenates alignedTimeSeries
    %   fftshift - shifts alignment by half cycle
    %   discretize - averages data across phases
    %   flipLR - flips left/right alignment
    %   getSym - computes symmetric components
    %   getaSym - computes asymmetric components
    %   rescaleTime - redefines time vector
    %   plot - plots aligned data with mean
    %   plotCheckerboard - displays data as heatmap
    %
    %See also: labTimeSeries, processedLabData
    %% Properties
    properties
        Data
        Time
        labels
        alignmentVector = [];
        alignmentLabels = {};
        eventTimes = [];
    end
    properties (Dependent)
        expandedEventTimes
    end
    %% Constructor
    methods
        function this = alignedTimeSeries(t0, Ts, Data, labels, ...
                alignmentVector, alignmentLabels, eventTimes)
            %alignedTimeSeries  Constructor for alignedTimeSeries class
            %
            %   this = alignedTimeSeries(t0, Ts, Data, labels,
            %   alignmentVector, alignmentLabels) creates aligned
            %   timeseries without event times
            %
            %   this = alignedTimeSeries(t0, Ts, Data, labels,
            %   alignmentVector, alignmentLabels, eventTimes) includes
            %   event timing information
            %
            %   Inputs:
            %       t0 - initial time
            %       Ts - sampling period
            %       Data - 3D matrix (samples x channels x strides)
            %       labels - cell array of channel labels
            %       alignmentVector - vector specifying number of samples
            %                         per phase
            %       alignmentLabels - cell array of phase/event labels
            %       eventTimes - matrix of event times (optional)
            %
            %   Outputs:
            %       this - alignedTimeSeries object
            %
            %   See also: labTimeSeries, processedLabData/reduce
            if nargin < 6
                warning(['alignedTimeSeries being created without ' ...
                    'specifying alignment criteria.']);
                alignmentVector = 1;
                alignmentLabels = {'Unknown'};
            end
            if size(Data, 2) == length(labels)
                this.Data = Data;
                this.Time = t0 + [0:size(Data, 1) - 1] * Ts;
                this.labels = labels;
                if length(alignmentVector) ~= length(alignmentLabels)
                    error('alignedTS:Constructor', ...
                        'Alignment vector and labels sizes do not match.');
                else
                    this.alignmentVector = alignmentVector;
                    this.alignmentLabels = alignmentLabels;
                end
            else
                error('alignedTS:Constructor', ...
                    'Data size and label number do not match.');
            end
            if nargin > 6
                % This actually calls on the set() method
                this.eventTimes = eventTimes;
            end
        end
    end
    %% Property Getters and Setters
    methods
        function eET = get.expandedEventTimes(this)
            %get.expandedEventTimes  Returns sample times for all events
            %
            %   Outputs:
            %       eET - matrix of sample times for each event
            if ~isempty(this.eventTimes)
                eET = alignedTimeSeries.expandEventTimes(...
                    this.eventTimes, this.alignmentVector);
            else % legacy version
                error('alignedTS:expandedEventTimes', ...
                    'eventTimes are not determined');
            end
        end
        function this = set.eventTimes(this, eventTimes)
            %set.eventTimes  Validates and sets event times
            %
            %   Inputs:
            %       this - alignedTimeSeries object
            %       eventTimes - matrix of event times
            if any(size(eventTimes) ~= [length(this.alignmentVector) ...
                    size(this.Data, 3) + 1])
                error('alignedTS:SetEventTimes', ...
                    'Data and eventTimes sizes do not match.');
            else
                this.eventTimes = eventTimes;
            end
        end
    end
    %% Data Extraction Methods
    methods
        newThis = getPartialStridesAsATS(this, inds)
        newThis = removeStridesWithNaNs(this)
        newThis = getPartialDataAsATS(this, labels)
    end
    %% Statistical Methods
    methods
        [meanTS, stds] = mean(this, strideIdxs)
        stdTS = std(this, strideIdxs)
        iqrTS = iqr(this, strideIdxs)
        stdTS = stdRobust(this, strideIdxs)
        prctileTS = prctile(this, p, strideIdxs)
        medianTS = median(this, strideIdxs)
        [decomposition, meanValue, avgStride, trial2trialVariability] = ...
            energyDecomposition(this)
    end
    %% Normalization Methods
    methods
        newThis = equalizeEnergyPerChannel(this)
        newThis = demean(this)
    end
    %% Arithmetic Operations
    methods
        function newThis = abs(this)
            %abs  Takes absolute value
            %
            %   newThis = abs(this) computes absolute value of data
            %
            %   Inputs:
            %       this - alignedTimeSeries object
            %
            %   Outputs:
            %       newThis - alignedTimeSeries with absolute values
            newThis = this;
            newThis.Data = abs(this.Data);
        end
        newThis = minus(this, other)
        newThis = plus(this, other)
        this = times(this, constant)
    end
    %% Type Conversion Methods
    methods
        newThis = catStrides(this)
        newThis = castAsTS(this)
        newThis = concatenateAsTS(this)
    end
    %% Label Methods
    methods
        [boolFlag, labelIdx] = isaLabel(this, label)
        labelList = getLabelsThatMatch(this, exp)
        this = renameLabels(this, originalLabels, newLabels)
    end
    %% Data Manipulation Methods
    methods
        newThis = cat(this, other, dim, forceFlag)
        newThis = fftshift(this, labels)
        newThis = discretize(this, averagingVector)
        [this, iC, iI] = flipLR(this)
        [this, iC, iI] = getSym(this)
        [this, iC, iI] = getaSym(this)
        newThis = rescaleTime(this, newTs, newT0)
    end
    %% Visualization Methods
    methods
        % [figHandle, plotHandles, plottedInds] = plot(this, figHandle, ...
        %     plotHandles, meanColor, events, individualLineStyle, ...
        %         plottedInds, bounds, medianFlag)
        function [figHandle,plotHandles,plottedInds]=plot(this,figHandle,plotHandles,meanColor,events,individualLineStyle,plottedInds,bounds,medianFlag)
            % Plot individual instances (strides) of the time-series, and overlays the mean of all of them
            % Uses one subplot for each label in the timeseries (same as
            % labTimeSeries.plot).
            % If events are given (alignedTimeSeries with the same time vector and number of strides),
            % it will display the average event-time ocurrence in the plot,
            % instead of the time in the x-axis.
            % See also labTimeSeries.plot
            %
            % SYNTAX:
            % [figHandle,plotHandles]=plot(this,figHandle,plotHandles,meanColor,events)
            %
            % INPUTS:
            % this: alignedTimeSeries object to plot
            % figHandle: handle to the figure to be used. If absent,
            % creates a new figure.
            % plotHandles: handles to the subplots being used. There need
            % to be at least as many handles as labels in the data.
            % meanColor: color to use for the plot of the mean. %FIXME
            % events: alignedTimeSeries of events.
            %
            % OUTPUT:
            % figHandle: handle to the figure used.
            % plotHandles: handles to the subplots used.
            %
            if nargin<4 || isempty(meanColor)
                meanColor=[1,0,0];
            end
            if nargin<9 || isempty(medianFlag)
                medianFlag=1;
            end
            structure=this.Data;
            if nargin<2 || isempty(figHandle)
                figHandle=figure();
            else
                figure(figHandle) %Only works for one condition!
            end
            set(figHandle,'Units','normalized','OuterPosition',[0 0 1 1])
            M=size(structure,2);
            if nargin<3 || isempty(plotHandles) || length(plotHandles)<size(this.Data,2)
                [b,a]=getFigStruct(M);
                plotHandles=tight_subplot(b,a,[.02 .02],[.05 .05], [.05 .05]); %External function
            end
            meanStr=mean(structure,3);
            if nargin<7 || isempty(plottedInds)
                plottedInds=1:size(structure,3);
                if (numel(structure))>1e7
                    P=floor(1e7/numel(structure(:,:,1)));
                    warning(['There are too many strides in this condition to plot (' num2str(size(structure,3)) '). Only plotting first ' num2str(P) '.'])
                    plottedInds=1:P;
                    structure=structure(:,:,plottedInds);
                end
            elseif any(plottedInds<=0) %Counting from the back
                plottedInds(plottedInds<=0)=size(structure,3)+plottedInds(plottedInds<=0);
            end
            %Define centerline plot:
            if medianFlag==1
                centerline=this.median.castAsTS; %Could do mean or median
            else
                centerline=this.mean.castAsTS;
            end
            %Plot percentiles (bounds)
            if nargin<5 || isempty(events)
                events=[];
                meanEvents=[];
            else
                if isa(events,'alignedTimeSeries')
                    [meanEvents,ss]=mean(events);
                    meanEvents=meanEvents.castAsTS;
                else
                    meanEvents=events;
                    ss=[];
                end
                [i2,~]=find(meanEvents.Data);
            end
            if ~islogical(this.Data) && nargin>7 && ~isempty(bounds)
                if length(bounds)==2 %Alt visualization: add patch
                    if any(bounds)==0
                        if medianFlag==1
                            st=this.stdRobust.castAsTS;
                        else
                            st=this.std.castAsTS;
                        end
                        if all(bounds)==0 %Plots ste
                            aux1=centerline+(st.* 1/sqrt(size(this.Data,3)));
                            aux2=centerline-(st .* 1/sqrt(size(this.Data,3)));
                        else %Plots std
                            aux1=centerline+(st);
                            aux2=centerline-(st);
                        end
                    else
                        aux1=prctile(this,bounds(1));
                        aux2=prctile(this,bounds(2));
                    end
                    for i=1:M
                        subplot(plotHandles(i))
                        hold on
                        if size(aux1.Time,1)==numel(aux1.Time) %column vector
                            megaTime=[aux1.Time; aux1.Time(end:-1:1)];
                        else %row vector
                            megaTime=[aux1.Time, aux1.Time(end:-1:1)];
                        end
                        megaData=[aux1.Data(:,i);aux2.Data(end:-1:1,i)];
                        megaData(isnan(megaData))=0;
                        pp=patch(megaTime,megaData,meanColor,'FaceAlpha',.4,'EdgeColor','none');
                        uistack(pp,'bottom');
                        hold off
                    end
                else %Plot each percentile line
                    for k=1:length(bounds)
                        [figHandle,plotHandles]=plot(this.prctile(bounds(k)).castAsTS,figHandle,[],plotHandles,[],meanColor*.8,.5);
                    end
                end
            end
            %PLot mean trace
            [figHandle,plotHandles]=plot(centerline,figHandle,[],plotHandles,meanEvents,meanColor); %Plotting mean data
            %Plot individual traces
            for i=1:M %Go over labels
                %subplot(b,a,i)
                subplot(plotHandles(i))
                hold on
                %title(aux{1}.(field).labels{i})
                data=squeeze(structure(:,i,:));
                N=size(data,1);
                if nargin<6 || isempty(individualLineStyle)
                    ppp=plot(this.Time,data,'Color',[.7,.7,.7]);
                    uistack(ppp,'bottom')
                elseif individualLineStyle==0
                    %nop
                else
                    ppp=plot(this.Time,data,individualLineStyle);
                    uistack(ppp,'bottom')
                end
                %plot([0:N-1]/N,meanStr(:,i),'LineWidth',2,'Color',meanColor);
                %legend(this.labels{i})
                %maxM(i)=5*norm(data(:))/sqrt(length(data(:)));
                meanM(i)=prctile(data(:),50);
                maxM(i)=2*(prctile(data(:),99)-meanM(i))+meanM(i)+eps;
                minM(i)=2*(prctile(data(:),1)-meanM(i))+meanM(i);
                axis([this.Time(1) this.Time(end) minM(i) maxM(i)])
                hold off
            end
            if ~isempty(events)
                for i=1:length(plotHandles) %For each plot, plot a standard deviation bar indicating how disperse are events with respect to their mean/median (XTick set).
                    eventSampPeriod=(events.Time(2)-events.Time(1));
                    subplot(plotHandles(i))
                    hold on
                    for j=1:length(ss)
                        plot(events.Time(i2(j))+ss(j)*[-1,1]*eventSampPeriod,[0,0],'k','LineWidth',1);
                    end
                    %axis tight %TO DO: not use axis tight, but find proper axes limits by computing the rms value of the signal, or something like that.
                    hold off
                end
            else
                for i=1:length(plotHandles) %For each plot, plot a standard deviation bar indicating how disperse are events with respect to their mean/median (XTick set).
                    subplot(plotHandles(i))
                    xt=get(gca,'XTick');
                    xt=[this.Time(1)+[0,cumsum(this.alignmentVector)]*(this.Time(end)-this.Time(1))/sum(this.alignmentVector)];
                    xtl=[[this.alignmentLabels, this.alignmentLabels(1)]];
                    set(gca,'XTick',xt,'XTickLabel',xtl)
                    set(gca,'xgrid','on')
                end
            end
        end
        [fh, ph] = plotCheckerboard(this, fh, ph)
    end
    %% Static Methods
    methods (Static)
        expEventTimes = expandEventTimes(eventTimes, alignmentVector)
    end
    %% Hidden Methods
    methods (Hidden)
        [histogram, newLabels] = logicalHist(this)
    end
end