Description of equalizeEnergyPerChannel
Home > labTools > classes > labTS > @alignedTimeSeries > equalizeEnergyPerChannel.m
equalizeEnergyPerChannel
PURPOSE
equalizeEnergyPerChannel Normalizes by RMS
SYNOPSIS
function newThis = equalizeEnergyPerChannel(this)
DESCRIPTION
equalizeEnergyPerChannel  Normalizes by RMS
   newThis = equalizeEnergyPerChannel(this) normalizes each channel
   by its RMS value across time and strides
   Inputs:
       this - alignedTimeSeries object
   Outputs:
       newThis - normalized alignedTimeSeries
   See also: demean, labTimeSeries/equalizeEnergyPerChannel
CROSS-REFERENCE INFORMATION
This function calls:
mean mean Computes mean across strides
This function is called by:
alignedTimeSeries
labTimeSeries
SOURCE CODE
function newThis = equalizeEnergyPerChannel(this)
%equalizeEnergyPerChannel  Normalizes by RMS
%
%   newThis = equalizeEnergyPerChannel(this) normalizes each channel
%   by its RMS value across time and strides
%
%   Inputs:
%       this - alignedTimeSeries object
%
%   Outputs:
%       newThis - normalized alignedTimeSeries
%
%   See also: demean, labTimeSeries/equalizeEnergyPerChannel
newThis = this;
newThis.Data = bsxfun(@rdivide, newThis.Data, ...
    sqrt(mean(mean(this.Data.^2, 3), 1)));
end