Description of mean
Home > labTools > classes > labTS > @alignedTimeSeries > mean.m
mean
PURPOSE
mean Computes mean across strides
SYNOPSIS
function [meanTS, stds] = mean(this, strideIdxs)
DESCRIPTION
mean  Computes mean across strides
   [meanTS, stds] = mean(this) computes mean and standard deviation
   across all aligned timeseries
   [meanTS, stds] = mean(this, strideIdxs) computes for specified
   strides
   Inputs:
       this - alignedTimeSeries object
       strideIdxs - vector of stride indices (optional, default: all)
   Outputs:
       meanTS - alignedTimeSeries with mean data (single stride)
       stds - standard deviations (for logical data) or empty
   Note: For logical data (events), assumes all aligned timeSeries
         have same number of events in same order. Returns median
         event times.
   See also: median, std, prctile
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
alignedTimeSeries
logicalHist logicalHist Generates histogram from logical event data
This function is called by:
BiofeedbackPerception
BiofeedbackSL
BiofeedbackSLBF_Percp
BiofeedbackVazE2B
plotParamBarsByConditionsv2 TODO: this file should be updated to call upon plotGroupedBars
experimentData
AnovaEpochs %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
GroupDemographics GroupDemographics Computes group demographics -- A CJS origonal, 5/5/17
groupAdaptationData
plotMultipleEpochBars This function replaces plotMultipleGroupBars
plotMultipleGroupsBars
processEMG processEMG Extracts processed and filtered EMG amplitude envelopes
plotCell plotCell Plots cell array of stride data
plotCellAvg plotCellAvg Plots average and std of stride cell array
plotAllStrides plotAllStrides Plots all individual strides for a field
plotAvgStride plotAvgStride Plots average stride across conditions
alignedTimeSeries
equalizeEnergyPerChannel equalizeEnergyPerChannel Normalizes by RMS
plot plot Plots aligned data with mean
plot PLOT Implementation for ClusteredSynergySetCollection
FactorizedMatrix
EMGnormalization EMGNORMALIZATION Example: normalize EMG parameters to baseline.
testMarkerOutlierDetectAndCorrect TESTMARKEROUTLIERDETECTANDCORRECT Example: detect and correct marker outliers using skeleton models.
computeAmplitudes COMPUTEAMPLITUDES Compute amplitudes of H-reflex components from EMG.
extractStimArtifactIndsFromTrigger EXTRACTSTIMARTIFACTINDSFROMTRIGGER Extract TAP stim artifact peak indices.
fitCal FITCAL Fit M- and H-wave recruitment curves.
plotCal PLOTCAL Plot the H-reflex recruitment or ratio calibration curve.
plotNoiseHistogram PLOTNOISEHISTOGRAM Plot the noise amplitude distribution for the H-reflex.
getVarianceDecomposition
rawEMGhealthCheck % Compute stats
getStanceFromForces GETSTANCEFROMFORCES Estimate stance phase from vertical ground reaction force.
getStanceFromForcesAlt GETSTANCEFROMFORCESALT Estimate stance phase using force derivative thresholding.
getStanceFromToeAndHeel GETSTANCEFROMTOENANDHEEL Estimate stance phase from ankle and toe kinematics.
btkEmulateC3Dserver BTKEMULATEC3DSERVER Creates an emulated COM object for C3Dserver.
naiveDistances
testSkeleton testSkeleton
demean DEMEAN Remove the column-wise mean from a matrix.
estimateDopplerShift ESTIMATEDOPPLERSHIFT Estimate relative sampling-rate mismatch via STFT.
findTemplate findTemplate implements a simple cross-correlation search to find for
polyfit1PCA Finding best-fit line through PCA
swtest SWTEST Shapiro-Wilk parametric hypothesis test of composite normality.
DetermineOptimalReconstructAndLabelParams % Determine the Optimal Reconstruct & Label Pipeline Parameters
DetermineOptimalReconstructAndLabelParamsTmp % Determine the Optimal Reconstruct & Label Pipeline Parameters
PlotHelper PLOTHELPER helper function with static functions to make common plots
V2P_tester
generateHreflexRecruitmentCurves % Generate H-Reflex Calibration Recruitment Curves & Other Figures
GroupDemographics GroupDemographics Computes group demographics -- A CJS origonal, 5/5/17
expResults % THIS FUNCTION IS OLD AND HAS BEEN REPLACED BY getResults !!!
getResults define number of points to use for calculating values
getResultsBF
appendBodyCOM APPENDBODYCOM Approximate whole-body center of mass from marker data.
calcParameters CALCPARAMETERS Compute stride-by-stride parameters for analysis.
computeCOM COMPUTECOM Compute stride-by-stride COM kinematics relative to each ankle.
computeForceParameters COMPUTEFORCEPARAMETERS Compute kinetic treadmill parameters per stride.
computeForceParameters_OGFP COMPUTEFORCEPARAMETERS_OGFP Compute AP GRF parameters from overground force plates.
computeForceParameters_OGFP_aligned COMPUTEFORCEPARAMETERS_OGFP_ALIGNED Compute AP GRF parameters using stride-aligned force traces.
computeHarmonicRatioParameters COMPUTEHARMONICRATIOPARAMETERS Compute harmonic ratios per stride.
computeHreflexParameters COMPUTEHREFLEXPARAMETERS Compute stride-by-stride H-reflex parameters.
computeLegForceParameters COMPUTELEGFORCEPARAMETERS Compute AP force parameters for one leg stride.
computeSpatialParameters COMPUTESPATIALPARAMETERS Compute spatial parameters per stride.
computeTSStatParameters COMPUTETSSTATPARAMETERS Compute summary statistics per stride.
extractKinematicDataAtEvents EXTRACTKINEMATICDATAATEVENTS Extract markers and angles at gait event times.
getNiceAxisLimits Similar to axis tight, but with pre-determined padding so no datapoints
prettyBarPlot Data is PxMxN, where:
syncEMGData SYNCEMGDATA Synchronize two-PC EMG recordings to a reference signal.
SOURCE CODE
function [meanTS, stds] = mean(this, strideIdxs)
%mean  Computes mean across strides
%
%   [meanTS, stds] = mean(this) computes mean and standard deviation
%   across all aligned timeseries
%
%   [meanTS, stds] = mean(this, strideIdxs) computes for specified
%   strides
%
%   Inputs:
%       this - alignedTimeSeries object
%       strideIdxs - vector of stride indices (optional, default: all)
%
%   Outputs:
%       meanTS - alignedTimeSeries with mean data (single stride)
%       stds - standard deviations (for logical data) or empty
%
%   Note: For logical data (events), assumes all aligned timeSeries
%         have same number of events in same order. Returns median
%         event times.
%
%   See also: median, std, prctile
if nargin > 1 && ~isempty(strideIdxs)
    this.Data = this.Data(:, :, strideIdxs);
end
if ~islogical(this.Data(1))
    % meanTS = labTimeSeries(nanmean(this.Data, 3), this.Time(1),
    %     this.Time(2) - this.Time(1), this.labels);
    meanTS = alignedTimeSeries(this.Time(1), ...
        this.Time(2) - this.Time(1), nanmean(this.Data, 3), ...
        this.labels, this.alignmentVector, this.alignmentLabels);
    stds = [];
else
    % Logical timeseries. Will find events and average appropriately.
    % Assuming the SAME number of events per stride, and in the same
    % ORDER. % FIXME: check event order.
    [histogram, newLabels] = logicalHist(this);
    % Compute mean/median:
    newData = sparse([], [], false, size(this.Data, 1), ...
        length(newLabels), size(this.Data, 1));
    mH = nanmedian(histogram);
    for i = 1:size(histogram, 2)
        if mod(mH(i), 1) ~= 0
            mH(i) = floor(mH(i));
            warning(['Median event ' num2str(i) ...
                ' falls between two samples']);
        end
        newData(mH(i), i) = true;
    end
    % meanTS = labTimeSeries(newData, this.Time(1),
    %     this.Time(2) - this.Time(1), newLabels);
    meanTS = alignedTimeSeries(this.Time(1), ...
        this.Time(2) - this.Time(1), newData, newLabels, ...
        this.alignmentVector, this.alignmentLabels);
    stds = nanstd(histogram);
end
end