Description of median
Home > labTools > classes > labTS > @alignedTimeSeries > median.m
median
PURPOSE
median Computes median
SYNOPSIS
function medianTS = median(this, strideIdxs)
DESCRIPTION
median  Computes median
   medianTS = median(this) computes median across all strides
   medianTS = median(this, strideIdxs) computes for specified strides
   Inputs:
       this - alignedTimeSeries object
       strideIdxs - vector of stride indices (optional, default: all)
   Outputs:
       medianTS - alignedTimeSeries with median values
   See also: mean, prctile
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
prctile prctile Computes percentile
This function is called by:
groupAdaptationData
getBeltSpeedsFromFootMarkers
alignedTimeSeries
fixBadLabels fixBadLabels Detects and fixes label swaps
testMarkerOutlierDetectAndCorrect TESTMARKEROUTLIERDETECTANDCORRECT Example: detect and correct marker outliers using skeleton models.
computeAmplitudes COMPUTEAMPLITUDES Compute amplitudes of H-reflex components from EMG.
fitCal FITCAL Fit M- and H-wave recruitment curves.
plotNoiseHistogram PLOTNOISEHISTOGRAM Plot the noise amplitude distribution for the H-reflex.
getEventsFromAngles GETEVENTSFROMANGLES Detect gait events from limb angle data.
getStanceFromToeAndHeel GETSTANCEFROMTOENANDHEEL Estimate stance phase from ankle and toe kinematics.
markerModel
DetermineOptimalReconstructAndLabelParams % Determine the Optimal Reconstruct & Label Pipeline Parameters
DetermineOptimalReconstructAndLabelParamsTmp % Determine the Optimal Reconstruct & Label Pipeline Parameters
getResultsBF
calcParameters CALCPARAMETERS Compute stride-by-stride parameters for analysis.
computeForceParameters COMPUTEFORCEPARAMETERS Compute kinetic treadmill parameters per stride.
computeForceParameters_OGFP COMPUTEFORCEPARAMETERS_OGFP Compute AP GRF parameters from overground force plates.
computeForceParameters_OGFP_aligned COMPUTEFORCEPARAMETERS_OGFP_ALIGNED Compute AP GRF parameters using stride-aligned force traces.
computeTSStatParameters COMPUTETSSTATPARAMETERS Compute summary statistics per stride.
SOURCE CODE
function medianTS = median(this, strideIdxs)
%median  Computes median
%
%   medianTS = median(this) computes median across all strides
%
%   medianTS = median(this, strideIdxs) computes for specified strides
%
%   Inputs:
%       this - alignedTimeSeries object
%       strideIdxs - vector of stride indices (optional, default: all)
%
%   Outputs:
%       medianTS - alignedTimeSeries with median values
%
%   See also: mean, prctile
if nargin < 2 || isempty(strideIdxs)
    strideIdxs = [];
end
medianTS = prctile(this, 50, strideIdxs);
end