Description of minus
Home > labTools > classes > labTS > @alignedTimeSeries > minus.m
minus
PURPOSE
minus Subtracts two alignedTimeSeries
SYNOPSIS
function newThis = minus(this, other)
DESCRIPTION
minus  Subtracts two alignedTimeSeries
   newThis = minus(this, other) subtracts other from this element-wise
   Inputs:
       this - alignedTimeSeries object
       other - alignedTimeSeries with compatible dimensions
   Outputs:
       newThis - difference of two alignedTimeSeries
   See also: plus, times
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
adaptationData
removeBiasV2
removeBiasV3 removeBias('condition') or removeBias({'Condition1','Condition2',...})
removeBiasV4 removeBias('condition') or removeBias({'Condition1','Condition2',...})
alignedTimeSeries
demean demean Removes mean
demean demean Removes mean from each channel
labTimeSeries
computeDifferenceMatrix computeDifferenceMatrix Computes inter-marker differences
getVarianceDecomposition
computeDiffMatrix Gets position data as N markers x 3D x M frames and for each frame
SOURCE CODE
function newThis = minus(this, other)
%minus  Subtracts two alignedTimeSeries
%
%   newThis = minus(this, other) subtracts other from this element-wise
%
%   Inputs:
%       this - alignedTimeSeries object
%       other - alignedTimeSeries with compatible dimensions
%
%   Outputs:
%       newThis - difference of two alignedTimeSeries
%
%   See also: plus, times
newThis = this;
newThis.Data = this.Data - other.Data;
end