Description of prctile
Home > labTools > classes > labTS > @alignedTimeSeries > prctile.m
prctile
PURPOSE
prctile Computes percentile
SYNOPSIS
function prctileTS = prctile(this, p, strideIdxs)
DESCRIPTION
prctile  Computes percentile
   prctileTS = prctile(this, p) computes specified percentile across
   all strides
   prctileTS = prctile(this, p, strideIdxs) computes for specified strides
   Inputs:
       this - alignedTimeSeries object
       p - percentile value (0-100)
       strideIdxs - vector of stride indices (optional, default: all)
   Outputs:
       prctileTS - alignedTimeSeries with percentile values
   See also: median, iqr, mean
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
alignedTimeSeries
prctile prctile Computes percentile
This function is called by:
plotAvgTimeCourse adaptDataList must be cell array of 'param.mat' file names
plotGroupedSubjectsBarsv2
alignedTimeSeries
median median Computes median
plot plot Plots aligned data with mean
prctile prctile Computes percentile
plotNoiseHistogram PLOTNOISEHISTOGRAM Plot the noise amplitude distribution for the H-reflex.
markerModel
estimateDopplerShift ESTIMATEDOPPLERSHIFT Estimate relative sampling-rate mismatch via STFT.
PlotHelper PLOTHELPER helper function with static functions to make common plots
clipSignals clipSignals Clip the top and bottom of each signal column by percentile.
computeSpatialParameters COMPUTESPATIALPARAMETERS Compute spatial parameters per stride.
processGRFData PROCESSGRFDATA Load and calibrate ground reaction force data from C3D.
SOURCE CODE
function prctileTS = prctile(this, p, strideIdxs)
%prctile  Computes percentile
%
%   prctileTS = prctile(this, p) computes specified percentile across
%   all strides
%
%   prctileTS = prctile(this, p, strideIdxs) computes for specified strides
%
%   Inputs:
%       this - alignedTimeSeries object
%       p - percentile value (0-100)
%       strideIdxs - vector of stride indices (optional, default: all)
%
%   Outputs:
%       prctileTS - alignedTimeSeries with percentile values
%
%   See also: median, iqr, mean
if nargin > 2 && ~isempty(strideIdxs)
    this.Data = this.Data(:, :, strideIdxs);
end
if ~islogical(this.Data(1))
    % prctileTS = labTimeSeries(prctile(this.Data, p, 3),
    %     this.Time(1), this.Time(2) - this.Time(1), this.labels);
    prctileTS = alignedTimeSeries(this.Time(1), ...
        this.Time(2) - this.Time(1), prctile(this.Data, p, 3), ...
        this.labels, this.alignmentVector, this.alignmentLabels);
else % Logical timeseries.
    error('alignedTimeSeries:prctile', ...
        'Prctile not yet implemented for logical alignedTimeSeries.');
    % TODO
end
end