Description of std
Home > labTools > classes > labTS > @alignedTimeSeries > std.m
std
PURPOSE
std Computes standard deviation
SYNOPSIS
function stdTS = std(this, strideIdxs)
DESCRIPTION
std  Computes standard deviation
   stdTS = std(this) computes standard deviation across all strides
   stdTS = std(this, strideIdxs) computes for specified strides
   Inputs:
       this - alignedTimeSeries object
       strideIdxs - vector of stride indices (optional, default: all)
   Outputs:
       stdTS - alignedTimeSeries with standard deviation (for numeric)
               or vector (for logical)
   See also: mean, stdRobust, iqr
CROSS-REFERENCE INFORMATION
This function calls:
isempty isempty Checks if the date equals the default value.
alignedTimeSeries
logicalHist logicalHist Generates histogram from logical event data
std std Computes standard deviation
This function is called by:
BiofeedbackSL
BiofeedbackSLBF_Percp
BiofeedbackVazE2B
GroupDemographics GroupDemographics Computes group demographics -- A CJS origonal, 5/5/17
groupAdaptationData
plotCellAvg plotCellAvg Plots average and std of stride cell array
alignedTimeSeries
std std Computes standard deviation
plot PLOT Implementation for ClusteredSynergySetCollection
testMarkerOutlierDetectAndCorrect TESTMARKEROUTLIERDETECTANDCORRECT Example: detect and correct marker outliers using skeleton models.
fitCal FITCAL Fit M- and H-wave recruitment curves.
getStanceFromToeAndHeel GETSTANCEFROMTOENANDHEEL Estimate stance phase from ankle and toe kinematics.
circCorr Finds the phase shift of two sinuoidal traces. trace1 and trace2 must be
polyfit1PCA Finding best-fit line through PCA
PlotHelper PLOTHELPER helper function with static functions to make common plots
GroupDemographics GroupDemographics Computes group demographics -- A CJS origonal, 5/5/17
matchControlsFixedGUI matchControlsFixedGUI Fixed GUI to choose demographic matching factors
computeForceParameters COMPUTEFORCEPARAMETERS Compute kinetic treadmill parameters per stride.
computeForceParameters_OGFP COMPUTEFORCEPARAMETERS_OGFP Compute AP GRF parameters from overground force plates.
computeForceParameters_OGFP_aligned COMPUTEFORCEPARAMETERS_OGFP_ALIGNED Compute AP GRF parameters using stride-aligned force traces.
SOURCE CODE
function stdTS = std(this, strideIdxs)
%std  Computes standard deviation
%
%   stdTS = std(this) computes standard deviation across all strides
%
%   stdTS = std(this, strideIdxs) computes for specified strides
%
%   Inputs:
%       this - alignedTimeSeries object
%       strideIdxs - vector of stride indices (optional, default: all)
%
%   Outputs:
%       stdTS - alignedTimeSeries with standard deviation (for numeric)
%               or vector (for logical)
%
%   See also: mean, stdRobust, iqr
if nargin > 1 && ~isempty(strideIdxs)
    this.Data = this.Data(:, :, strideIdxs);
end
if ~islogical(this.Data(1))
    % stdTS = labTimeSeries(nanstd(this.Data, [], 3), this.Time(1),
    %     this.Time(2) - this.Time(1), this.labels);
    stdTS = alignedTimeSeries(this.Time(1), ...
        this.Time(2) - this.Time(1), nanstd(this.Data, [], 3), ...
        this.labels, this.alignmentVector, this.alignmentLabels);
else
    % Logical timeseries. Will find events and average appropriately.
    % Assuming the SAME number of events per stride, and in the same
    % ORDER. % FIXME: check event order.
    histogram = logicalHist(this);
    stdTS = std(histogram); % Not really a tS
end
end