%EDIT THIS COMMENT: INCLUDE A BREIF DESCRIPTION OF WHAT STUDY THIS IS
% ex - OG study: old subjects adapted abruptly

% The different fields of the contition info are difined here.
% Save this code to a different name and then run it once 
% finished editing for changes to appear in GetInfoGUI

% Define Name of group
expDes.group='New Group';

% Define Condition numbers (maximum number of conditions is 15 as of 4/2015)
for cond = 1:10 %<-- edit this number
    expDes.(['condition' num2str(cond)])=num2str(cond);
end
% Define total number of conditions
expDes.numofconds='10'; %<-- this should match the number above

% Define trial types. These descibe the general condition of the trial. For
% example, if the subject is walking overground or at an incline, it would
% be specified here. Types should only be difined for general conditions
% that require a separate baseline for bias removal. Note that even though 
% there may be a slow, fast, and medium baseline trial on the treadmill, 
% if only the medium baseline is used to remove a bias from other treadmill
% trials, then these can all be grouped into a general treadmill type.

%set trial types
for t=[1 9]
    expDes.(['type' num2str(t)])='OG'; % for overground walking
end
for t=[2:8 10]
    expDes.(['type' num2str(t)])='TM'; % for treadmill walking
end
%note: 'IN' is typically used in the treadmill was inclined

% Define condition names. These should be short but descriptive and should
% follow lab conventions, if possible. IMPORTANT: The condition that will 
% be used to remove a bias from all other trials of the same type MUST
% be named such that one of the type strings and the string ‘base’ are 
% both included in the condition's name.
expDes.condName1='OG base';%<-- data from this condition will be used to remove bias from all other conditions of type OG
expDes.condName2='slow base';
expDes.condName3='short split';
expDes.condName4='fast base';
expDes.condName5='TM base'; %<-- data from this condition will be used to remove bias from all other conditions of type TM
expDes.condName6='adaptation';
expDes.condName7='catch';
expDes.condName8='re-adaptation';
expDes.condName9='OG post';
expDes.condName10='TM post';

% Define condition descriptions. Be as descriptive as possible. Include 
% whatever information seems important to someone who is unfamiliar with 
% what you did, such as the number of strides and possibly the speeds the 
% belts were set at. 
expDes.description1='8m walkway for 6 min';
expDes.description2='150 strides at 0.5 m/s';
expDes.description3='10 strides 2:1, 1 m/s and 0.5 m/s';
expDes.description4='150 strides at 1 m/s';
expDes.description5='150 strides at 0.75 m/s';
expDes.description6='600 strides 2:1, 1 m/s and 0.5 m/s';
expDes.description7='10 strides at 0.75 m/s';
expDes.description8='300 strides 2:1, 1 m/s and 0.5 m/s';
expDes.description9='8 m walkway for 6 min';
expDes.description10='450 strides at 0.75 m/s';

% Define (expected) trial numbers for each condition. Multiple numbers can 
% be set as '1:5', '1,2,3' or '4 5' but not '1-5'). These will most
% likely need edited on a per-subject basis. Numbers correspond to names of
% files generated by Vicon Nexus during experiment.
expDes.trialnum1='1:6';
expDes.trialnum2='7';
expDes.trialnum3='8';
expDes.trialnum4='9';
expDes.trialnum5='10';
expDes.trialnum6='11:14';
expDes.trialnum7='15';
expDes.trialnum8='16 17';
expDes.trialnum9='18:23';
expDes.trialnum10='24:26';

%-----------------------DO NOT EDIT BELOW THIS LINE ----------------------%
groupName=expDes.group;
groupName=groupName(ismember(groupName,['A':'Z' 'a':'z']));  
path=which('GetInfoGUI');
path=strrep(path,'GetInfoGUI.m','ExpDetails');
save([path filesep groupName],'expDes')