Description of getEventsFromStance
Home > labTools > fun > eventExtraction > getEventsFromStance.m
getEventsFromStance
PURPOSE
GETEVENTSFROMSTANCE Retrieve gait events from stance phase logical vectors.
SYNOPSIS
function [LHS, RHS, LTO, RTO] = getEventsFromStance(stanceL, stanceR)
DESCRIPTION
GETEVENTSFROMSTANCE Retrieve gait events from stance phase logical vectors.
   Detects heel-strike (HS) and toe-off (TO) events for left and right
 legs by finding rising and falling edges of the stance phase signals.
 Inputs:
   stanceL - N×1 logical, left stance phase (true = stance)
   stanceR - N×1 logical, right stance phase (true = stance)
 Outputs:
   LHS - N×1 logical, left heel-strike events
   RHS - N×1 logical, right heel-strike events
   LTO - N×1 logical, left toe-off events
   RTO - N×1 logical, right toe-off events
 Toolbox Dependencies: None
 See also GETEVENTSFROMFORCES, GETEVENTSFROMTOENANDHEEL.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
getEventsFromSwitches retrieve left and right leg stance phases
getEventsFromForces GETEVENTSFROMFORCES Detect gait events from vertical ground reaction forces.
getEventsFromToeAndHeel GETEVENTSFROMTOENANDHEEL Detect gait events from toe and heel marker data.
SOURCE CODE
function [LHS, RHS, LTO, RTO] = getEventsFromStance(stanceL, stanceR)
%GETEVENTSFROMSTANCE Retrieve gait events from stance phase logical vectors.
%
%   Detects heel-strike (HS) and toe-off (TO) events for left and right
% legs by finding rising and falling edges of the stance phase signals.
%
% Inputs:
%   stanceL - N×1 logical, left stance phase (true = stance)
%   stanceR - N×1 logical, right stance phase (true = stance)
%
% Outputs:
%   LHS - N×1 logical, left heel-strike events
%   RHS - N×1 logical, right heel-strike events
%   LTO - N×1 logical, left toe-off events
%   RTO - N×1 logical, right toe-off events
%
% Toolbox Dependencies: None
%
% See also GETEVENTSFROMFORCES, GETEVENTSFROMTOENANDHEEL.
LTO = [false; diff(double(stanceL)) == -1];  % & stanceR;
LHS = [false; diff(double(stanceL)) == 1];   % & stanceR;
RTO = [false; diff(double(stanceR)) == -1];  % & stanceL;
RHS = [false; diff(double(stanceR)) == 1];   % & stanceL;
end