Description of getEventsFromForces
Home > labTools > fun > eventExtraction > getEventsFromForces.m
getEventsFromForces
PURPOSE
GETEVENTSFROMFORCES Detect gait events from vertical ground reaction forces.
SYNOPSIS
function [LHS, RHS, LTO, RTO] = getEventsFromForces(FzL, FzR, fsample)
DESCRIPTION
GETEVENTSFROMFORCES Detect gait events from vertical ground reaction forces.
   Determines heel-strike (HS) and toe-off (TO) events for left and right
 legs by thresholding vertical GRF signals. Delegates stance detection to
 GETSTANCEFROMFORCES and event extraction to GETEVENTSFROMSTANCE.
 Inputs:
   FzL     - N×1 double, left vertical GRF signal (N, positive upward)
   FzR     - N×1 double, right vertical GRF signal (N, positive upward)
   fsample - scalar double, sampling frequency (Hz)
 Outputs:
   LHS - N×1 logical, left heel-strike events
   RHS - N×1 logical, right heel-strike events
   LTO - N×1 logical, left toe-off events
   RTO - N×1 logical, right toe-off events
 Toolbox Dependencies: None
 See also GETSTANCEFROMFORCES, GETEVENTSFROMSTANCE.
CROSS-REFERENCE INFORMATION
This function calls:
getEventsFromStance GETEVENTSFROMSTANCE Retrieve gait events from stance phase logical vectors.
getStanceFromForces GETSTANCEFROMFORCES Estimate stance phase from vertical ground reaction force.
This function is called by:
BiofeedbackPerception
getEvents GETEVENTS Extract gait events from a raw trial, selecting the appropriate
AddPythonData Script to process a python biofeedback data file and add the columns of
SyncPython_forStatic function to incorporate biofeedback data from Python scripts into labtools
SL_Realtime SL Realtime
SL_RealtimeAlpha SL Realtime
SOURCE CODE
function [LHS, RHS, LTO, RTO] = getEventsFromForces(FzL, FzR, fsample)
%GETEVENTSFROMFORCES Detect gait events from vertical ground reaction forces.
%
%   Determines heel-strike (HS) and toe-off (TO) events for left and right
% legs by thresholding vertical GRF signals. Delegates stance detection to
% GETSTANCEFROMFORCES and event extraction to GETEVENTSFROMSTANCE.
%
% Inputs:
%   FzL     - N×1 double, left vertical GRF signal (N, positive upward)
%   FzR     - N×1 double, right vertical GRF signal (N, positive upward)
%   fsample - scalar double, sampling frequency (Hz)
%
% Outputs:
%   LHS - N×1 logical, left heel-strike events
%   RHS - N×1 logical, right heel-strike events
%   LTO - N×1 logical, left toe-off events
%   RTO - N×1 logical, right toe-off events
%
% Toolbox Dependencies: None
%
% See also GETSTANCEFROMFORCES, GETEVENTSFROMSTANCE.
%% Get stance phases
forceThresh = 60; % stance detection threshold (N); ~8% of typical BW
% NOTE: getStanceFromForcesAlt is a derivative-based alternative to
% getStanceFromForces; see that function for details.
stanceL = getStanceFromForces(FzL, forceThresh, fsample);
stanceR = getStanceFromForces(FzR, forceThresh, fsample);
%% Get events from stance
[LHS, RHS, LTO, RTO] = getEventsFromStance(stanceL, stanceR);
% NOTE: energy-onset masking (removing events before first GRF activity)
% was removed because it suppressed the very first step of a trial, which
% is often the most important event for adaptation analysis (Pablo, 2015).
end