Description of findLabel
Home > labTools > gui > importc3d > findLabel.m
findLabel
PURPOSE
function to deal with different marker labels from vicon. For the code to
SYNOPSIS
function markerLabel = findLabel(viconLabel)
DESCRIPTION
function to deal with different marker labels from vicon. For the code to
run correctly, the label names must be as they are set in this code.
DO NOT edit the 'markerLabel' declarations, only edit the strings in the
case statements
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
SL_Realtime SL Realtime
SL_RealtimeAlpha SL Realtime
loadTrials loadTrials Generates rawTrialData instances for each trial.
SOURCE CODE
function markerLabel = findLabel(viconLabel)
%function to deal with different marker labels from vicon. For the code to
%run correctly, the label names must be as they are set in this code.
%
%DO NOT edit the 'markerLabel' declarations, only edit the strings in the
%case statements
markerLabel = viconLabel;               % default labels input argument
load('markerLabelKey.mat');             % contains 'matchedLabels' variable
for lbl = 1:size(matchedLabels,1)       % for each label, ...
    if ismember(viconLabel,matchedLabels{lbl,1})
        markerLabel = matchedLabels{lbl,2};
    end
end
end
% switch viconLabel
%     case {'LGT','OG80_LGT','OG88_LGT'}
%         markerLabel = 'LHIP';
%     case {'RGT','OG80_RGT','OG88_RGT'}
%         markerLabel = 'RHIP';
%     case {'LANKLE','OG80_LANK','OG88_LANK'}
%         markerLabel = 'LANK';
%     case {'RANKLE','OG80_RANK','OG88_RANK'}
%         markerLabel = 'RANK';
%     case {'RHEEL','OG80_RHEEL','OG88_LHEEL'}
%         markerLabel = 'RHEE';
%     case {'LHEEL','OG80_LHEEL','OG88_RHEEL'}
%         markerLabel = 'LHEE';
%     case {'OG80_LTOE','OG88_LTOE'}
%         markerLabel = 'LTOE';
%     case {'OG80_RTOE','OG88_RTOE'}
%         markerLabel = 'RTOE';
%     case {'RKNEE','OG80_RKNE'} %,'OG88_RKNE'}
%         markerLabel = 'RKNE';
%     case {'LKNEE','OG80_LKNE'} %,'OG88_LKNE'}
%         markerLabel = 'LKNE';
%     otherwise
%         markerLabel = viconLabel;
% end