Description of computeDiffMatrix
Home > fun > ext > markerDataCleaning > old > old_markerFiltering > staticSkeleton > computeDiffMatrix.m
computeDiffMatrix
PURPOSE
SYNOPSIS
function [D] = computeDiffMatrix(pos)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
computeDistanceMatrix UNTITLED2 Summary of this function goes here
sk3Ddetect
sk3Denforce Given a prior estimate x with uncertainty P (normal dist) of some variable x, and the
sk3Dlearn Returns model such that W*pos(:,:,i) ~ N(m,R)
SOURCE CODE
function [D] = computeDiffMatrix(pos)
if numel(pos)==1
    N=pos;
    W=sparse(N^2,N);
    for i=1:N
        W(N*(i-1)+[1:i-1,i+1:N],i)=-1;
        for j=[1:i-1,i+1:N];
            W(N*(i-1)+j,j)=1;
        end
    end
    D=W;
else
[N,dim,M]=size(pos);
D=bsxfun(@minus,reshape(pos,[N,dim,1,M]),reshape(permute(pos,[2,1,3]),[1,dim,N,M]));
%Equivalent to: D=W*pos;
end
end