Description of determineLikelihoodFromZeroModel
Home > fun > ext > markerDataCleaning > old > old_markerModels > determineLikelihoodFromZeroModel.m
determineLikelihoodFromZeroModel
PURPOSE
Computes a likelihood for a set of marker positions given a 'zero-model'
SYNOPSIS
function [lp,p] = determineLikelihoodFromZeroModel(X,D,sD)
DESCRIPTION
Computes a likelihood for a set of marker positions given a 'zero-model'
(naive bayes) which assumes independent gaussian distributions for each
distance between models.
------
INPUTS:
X is a Nx3xM matrix of N marker positions in 3D, samples M times.
D is a NxN matrix containing the expected distances between the N markers
sD is a NxN matrix containing the standard deviation of the distances
across time
------
OUTPUT:
p is a NxM matrix containing log-likelihoods for each of the N markers in each
of the M samples
CROSS-REFERENCE INFORMATION
This function calls:
computeDistanceMatrix UNTITLED2 Summary of this function goes here
This function is called by:
determineLikelihoodFromOneModel Computes a likelihood for a set of marker positions given a 'zero-model'
determineLikelihoodFromZeroPlusModel Computes a likelihood for a set of marker positions given a 'zero-model'
getBestReconsFromOneModel UNTITLED Summary of this function goes here
getBestReconsFromZeroModel UNTITLED Summary of this function goes here
SUBFUNCTIONS
function bool=issquare(D)
SOURCE CODE
function [lp,p] = determineLikelihoodFromZeroModel(X,D,sD)
%Computes a likelihood for a set of marker positions given a 'zero-model'
%(naive bayes) which assumes independent gaussian distributions for each
%distance between models.
%------
%INPUTS:
%X is a Nx3xM matrix of N marker positions in 3D, samples M times.
%D is a NxN matrix containing the expected distances between the N markers
%sD is a NxN matrix containing the standard deviation of the distances
%across time
%------
%OUTPUT:
%p is a NxM matrix containing log-likelihoods for each of the N markers in each
%of the M samples
[N,tres,M]=size(X);
if size(D,1)~=N || ~issquare(D)
    error()
end
if size(sD,1)~=N || ~issquare(sD)
    error()
end
if tres~=3
    error()
end
lp=nan(N,M);
%D=D+eye(size(D));
%sD=sD+eye(size(D));
for i=1:M %For each frame
   dist=computeDistanceMatrix(X(:,:,i));
   pp=(-(dist(:)-D(:)).^2./(2*sD(:).^2));%./(sqrt(2*pi)*sD(:)); %Fake log-likelihood: it is a mahalanobis distance squared
   pp=reshape(pp,N,N);
   lp(:,i)=nanmean(-sqrt(-pp));
end
p=[];
end
function bool=issquare(D)
bool = size(D,1)==size(D,2);
end