Description of getBestReconsFromZeroPlusModel
Home > fun > ext > markerDataCleaning > old > old_markerModels > getBestReconsFromZeroPlusModel.m
getBestReconsFromZeroPlusModel
PURPOSE
UNTITLED Summary of this function goes here
SYNOPSIS
function [altPos] = getBestReconsFromZeroPlusModel(measuredPos,D,sD,meanPos,I,biasPos)
DESCRIPTION
UNTITLED Summary of this function goes here
   Detailed explanation goes here
CROSS-REFERENCE INFORMATION
This function calls:
expandDataForZeroPlus UNTITLED3 Summary of this function goes here
getBestReconsFromZeroModel UNTITLED Summary of this function goes here
This function is called by:
createZeroPlusModel UNTITLED6 Summary of this function goes here
SOURCE CODE
function [altPos] = getBestReconsFromZeroPlusModel(measuredPos,D,sD,meanPos,I,biasPos)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
altPos=nan(size(measuredPos));
if nargin<6 || isempty(biasPos)
    biasPos=zeros(size(measuredPos));
end
for i=1:size(measuredPos,1) %Only reconstructing actual markers
    X1=measuredPos;
    X1(i,:)=nan;
    [X2] = expandDataForZeroPlus(X1,I);
    [altPos(i,:)] = getBestReconsFromZeroModel(X2,D,sD,meanPos,i,biasPos); %Only reconstructing i-th marker
end
end